Repository xorbitsai/inference, pull requests merged in 2023-08, with the labels that each got.

#279 REF: split supervisor and worker
  xinference/client.py
  xinference/core/api.py
  xinference/core/restful_api.py
  xinference/core/supervisor.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/deploy/supervisor.py
  xinference/deploy/worker.py
Labels: gpu, refactor

#282 FEAT: pytorch model embeddings
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/tests/test_opt.py
Labels: feature

#287 FEAT: support falcon-instruct 7b and 40b pytorch model
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/falcon.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: feature

#247 DOC: add docstring to client methods
  xinference/client.py
Labels: documentation

#281 TST: add benchmark script
  benchmark/benchmark_script.py
  setup.cfg
Labels: testing

#294 FEAT: support qwen 7b
  xinference/model/llm/llm_family.json
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: feature

#293 ENH: select q4_0 as default quantization method for ggmlv3 model in benchmark
  benchmark/benchmark_script.py
Labels: enhancement

#297 BUG: llm_family.json encoding
  xinference/model/llm/__init__.py
Labels: bug

#299 ENH: disable gradio telemetry
  examples/gradio_chatinterface.py
Labels: enhancement

#290 FEAT: custom model
  benchmark/benchmark_script.py
  xinference/client.py
  xinference/constants.py
  xinference/core/gradio.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/tests/test_chatglm.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
  xinference/tests/test_client.py
Labels: feature

#309 BUG: handle ChatGLM ggml specific case for RESTful API
  xinference/core/restful_api.py
Labels: bug

#307 BUG: handle Qwen update
  setup.cfg
  xinference/model/llm/pytorch/utils.py
Labels: bug

#314 DOC: fix doc warnings
  doc/source/getting_started/index.rst
  doc/source/reference/index.rst
  doc/source/user_guide/examples/AI_Podcast.rst
  doc/source/user_guide/examples/chat.rst
  doc/source/user_guide/faq.rst
  doc/source/user_guide/index.rst
Labels: documentation

#284 ENH: accelerate 4-bit quantization for pytorch model
  xinference/model/llm/pytorch/core.py
Labels: enhancement

#325 DOC: custom models
  README.md
  README_zh_CN.md
Labels: documentation

#329 ENH: remove chatglmcpp from deps
  setup.cfg
Labels: enhancement

#322 ENH: auto detect device in pytorch model
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/core.py
Labels: enhancement

#320 ENH: Include model revision
  xinference/core/worker.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/llm/tests/test_llm_family.py
Labels: enhancement

#331 BUG: fix mps and cuda device detection for pytorch model
  xinference/model/llm/core.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/pytorch/core.py
Labels: bug, gpu

#336 Bug: Fix grammar mistake in examples
  examples/AI_podcast.py
  examples/gradio_chatinterface.py
Labels: bug

#335 BUG: Fix log level on subprocess
  xinference/deploy/cmdline.py
  xinference/deploy/worker.py
Labels: bug

#332 DOC: framework
  README.md
  README_zh_CN.md
  doc/source/examples/ai_podcast.rst
  doc/source/examples/chatbot.rst
  doc/source/examples/index.rst
  doc/source/getting_started.rst
  doc/source/getting_started/index.rst
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/qwen.rst
  doc/source/models/index.rst
  doc/source/reference/index.rst
  doc/source/user_guide/backends.rst
  doc/source/user_guide/cache_management.rst
  doc/source/user_guide/faq.rst
  doc/source/user_guide/index.rst
Labels: documentation

#289 FEAT: Support Ctransformers
  .github/workflows/python.yaml
  setup.cfg
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/ggml/ctransformers_util.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_ctransformers.py
  xinference/model/llm/llm_family.json
Labels: feature

#342 BLD: fix readthedocs
  .readthedocs.yaml
Labels: build

#338 DOC: models
  README.md
  README_zh_CN.md
  doc/source/conf.py
  doc/source/models/builtin/baichuan-chat.rst
  doc/source/models/builtin/baichuan.rst
  doc/source/models/builtin/chatglm.rst
  doc/source/models/builtin/chatglm2-32k.rst
  doc/source/models/builtin/chatglm2.rst
  doc/source/models/builtin/falcon-instruct.rst
  doc/source/models/builtin/falcon.rst
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/llama-2-chat.rst
  doc/source/models/builtin/llama-2.rst
  doc/source/models/builtin/opt.rst
  doc/source/models/builtin/orca_mini.rst
  doc/source/models/builtin/qwen-chat.rst
  doc/source/models/builtin/qwen.rst
  doc/source/models/builtin/starchat-beta.rst
  doc/source/models/builtin/starcoder.rst
  doc/source/models/builtin/starcoderplus.rst
  doc/source/models/builtin/vicuna-v1.3.rst
  doc/source/models/builtin/wizardlm-v1.0.rst
  doc/source/models/custom.rst
  doc/source/models/index.rst
  doc/source/user_guide/backends.rst
  doc/source/user_guide/index.rst
  xinference/core/worker.py
  xinference/model/llm/llm_family.json
Labels: documentation

#324 ENH: Use Llama 2 chat for inference in LangChain QA demo
  examples/LangChain_QA.ipynb
Labels: enhancement

#349 BUG: Chatglm max_length doesn't work
  xinference/model/llm/ggml/chatglm.py
Labels: bug

#354 DOC: fix README.md
  README.md
  README_zh_CN.md
Labels: documentation

#350 ENH: cache from URI
  doc/source/models/custom.rst
  setup.cfg
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: enhancement

#353 BUG: builtin stop_token_ids changes
  xinference/model/llm/pytorch/core.py
Labels: bug

#352 FEAT: internlm
  doc/source/models/builtin/chatglm2-32k.rst
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/internlm-chat-8k.rst
  doc/source/models/builtin/internlm-chat.rst
  doc/source/models/builtin/internlm.rst
  doc/source/models/builtin/starcoder.rst
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/utils.py
  xinference/deploy/worker.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: feature

#359 ENH: Update System Prompt for llama-2-chat
  xinference/model/llm/llm_family.json
Labels: enhancement

#343 FEAT: Support Vicuna-v1.5 and Vicuna-v1.5-16k
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/vicuna-v1.5-16k.rst
  doc/source/models/builtin/vicuna-v1.5.rst
  xinference/model/llm/llm_family.json
Labels: feature

#351 FEAT: wizardmath
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/wizardmath-v1.0.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: feature

#360 ENH: RESTful client supports custom model APIs
  xinference/client.py
  xinference/core/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/tests/test_client.py
Labels: enhancement

#364 BUG: custom model related bugs
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
Labels: bug

#365 DOC: update builtin models
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#363 FEAT: support generate/chat/create_embedding/register/unregister/registrations method in cmdline
  README.md
  README_zh_CN.md
  doc/source/models/custom.rst
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
Labels: feature

#368 FEAT: Adding support for stream returning completion results
  xinference/client.py
Labels: feature

#374 ENH: including default context length into model family
  doc/source/models/custom.rst
  xinference/client.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
  xinference/deploy/test/test_cmdline.py
  xinference/model/llm/ggml/tests/test_chatglm.py
  xinference/model/llm/ggml/tests/test_ctransformers.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/tests/test_client.py
Labels: enhancement

#383 BUG: llm class match
  xinference/core/worker.py
  xinference/model/llm/__init__.py
Labels: bug

#382 BUG: return chat model handle
  xinference/client.py
Labels: bug

#380 BUG: xinference cache dir doesn't exist
  xinference/model/llm/llm_family.py
Labels: bug

#386 ENH: Update max_tokens to 32k
  xinference/core/restful_api.py
Labels: enhancement

#387 FEAT: Support Llama-2 PyTorch model
  doc/source/models/builtin/llama-2-chat.rst
  doc/source/models/builtin/llama-2.rst
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/llama_2.py
Labels: feature

#390 DOC: readme enhancements
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/index.rst
Labels: documentation

#398 BUG: last token is duplicated
  xinference/model/llm/pytorch/utils.py
Labels: bug

#402 FEAT: code-llama
  doc/source/models/builtin/code-llama-python.rst
  doc/source/models/builtin/code-llama.rst
  doc/source/models/builtin/index.rst
  xinference/model/llm/llm_family.json
Labels: feature

#357 BUG: fix subprocess log on linux
  xinference/deploy/utils.py
Labels: bug

#407 BUG: Asking to pad but the tokenizer does not have a padding token
  xinference/model/llm/pytorch/llama_2.py
Labels: bug

#367 ENH: help message for CLI
  xinference/deploy/cmdline.py
Labels: enhancement
