Repository xorbitsai/inference, pull requests merged in 2023-10, with the labels that each got.

#470 REF: Use restful client as default client
  xinference/client.py
  xinference/deploy/cmdline.py
  xinference/model/llm/ggml/tests/test_ctransformers.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/tests/test_client.py
Labels: refactor

#517 DOC: hardware specific installations
  doc/source/getting_started/installation.rst
  doc/source/user_guide/backends.rst
  setup.cfg
Labels: documentation

#513 TST: fix tiny llama
  xinference/conftest.py
  xinference/model/llm/core.py
  xinference/model/llm/ggml/tests/test_gguf.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_llm_family.py
  xinference/tests/test_client.py
Labels: testing

#522 FEAT: Add BAAI/BGE v1.5 family models
  xinference/model/embedding/model_spec.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#528 REF: refactor client codes for xinference-client
  .github/workflows/python.yaml
  xinference/client/__init__.py
  xinference/client/common.py
  xinference/client/oscar/__init__.py
  xinference/client/oscar/actor_client.py
  xinference/client/restful/__init__.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/__init__.py
  xinference/client/tests/test_client.py
  xinference/deploy/cmdline.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_ctransformers.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/types.py
Labels: refactor

#527 DOC: update installation
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/getting_started/installation.rst
Labels: documentation

#510 FEAT: Support Mistral & Mistral-Instruct
  setup.cfg
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/llm_family.json
Labels: feature

#514 BUG: Fix listing embedding models
  xinference/core/supervisor.py
  xinference/deploy/cmdline.py
  xinference/model/core.py
Labels: bug

#539 FEAT: wizardcoder python
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/wizardcoder-python-v1.0.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#543 DOC: Add Client API reference
  doc/source/reference/index.rst
  xinference/client/handlers.py
  xinference/client/restful/restful_client.py
Labels: documentation

#532 ENH: Download embedding models from ModelScope
  xinference/model/embedding/__init__.py
  xinference/model/embedding/core.py
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/ggml/tests/test_chatglm.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/utils.py
Labels: enhancement

#525 FEAT: Support grammar-based sampling for ggml models
  README.md
  README_zh_CN.md
  xinference/core/restful_api.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_gguf.py
  xinference/types.py
Labels: feature

#549 ENH: lock transformers version
  setup.cfg
Labels: enhancement

#555 BUG: set trust_remote_code to true by default
  xinference/model/llm/pytorch/falcon.py
Labels: bug

#547 DOC: Add client doc to the user guide
  doc/source/user_guide/client_api.rst
  doc/source/user_guide/index.rst
  xinference/core/supervisor.py
  xinference/deploy/cmdline.py
  xinference/model/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: documentation

#562 BUG: add quantization to valid file name
  xinference/model/llm/ggml/llamacpp.py
Labels: bug

#557 ENH: Support downloading code-llama family models from ModelScope
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#556 BUG: remove "generate" ability from Baichuan-2-chat json config
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#567 ENH: Add gguf format of codellama-instruct
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#558 ENH: display language tags
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement

#559 ENH: filter models by type
  xinference/web/ui/src/scenes/launch_model/index.js
Labels: enhancement

#570 ENH: disable create embeddings using LLMs
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#551 DOC: Incompatibility Between NVIDIA Driver and PyTorch Version
  doc/source/getting_started/troubleshooting.rst
Labels: documentation

#571 BUG: Fix `bge-base-zh` and `bge-large-zh` from ModelScope
  xinference/model/embedding/model_spec_modelscope.json
Labels: bug

#561 DOC: Examples and resources page
  doc/source/examples/ai_podcast.rst
  doc/source/examples/chatbot.rst
  doc/source/examples/gradio_chatinterface.rst
  doc/source/examples/index.rst
  doc/source/examples/pdf_chatbot.rst
Labels: documentation

#566 ENH: configurable `XINFERENCE_HOME` env
  doc/source/getting_started/using_xinference.rst
  xinference/constants.py
Labels: enhancement

#573 BUG: When change model revision, xinference still uses the previous model
  xinference/model/embedding/core.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/utils.py
Labels: bug

#579 BUG: incorrect vLLM config
  xinference/core/supervisor.py
  xinference/model/llm/core.py
  xinference/model/llm/vllm/core.py
Labels: bug

#580 BUG: fix llama-2 stop words
  xinference/model/llm/llm_family.json
Labels: bug

#587 FEAT: chatglm3
  README.md
  README_zh_CN.md
  doc/source/models/builtin/chatglm3-32k.rst
  doc/source/models/builtin/chatglm3.rst
  doc/source/models/builtin/index.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: feature

#553 DOC: Download model from ModelScope
  doc/source/getting_started/troubleshooting.rst
  doc/source/models/builtin/bge-base-en-v1.5.rst
  doc/source/models/builtin/bge-base-zh-v1.5.rst
  doc/source/models/builtin/bge-large-en-v1.5.rst
  doc/source/models/builtin/bge-large-zh-v1.5.rst
  doc/source/models/builtin/bge-small-en-v1.5.rst
  doc/source/models/builtin/bge-small-zh-v1.5.rst
  doc/source/models/builtin/index.rst
  doc/source/models/index.rst
  doc/source/models/sources/sources.rst
Labels: documentation

#594 BUG: Fix chat system messages
  xinference/core/restful_api.py
  xinference/core/tests/test_restful_api.py
Labels: bug
