Repository xorbitsai/inference, pull requests merged in 2023-07, with the labels that each got.

#105 ENH: Support alpaca Chinses
  xinference/model/llm/__init__.py
  xinference/model/llm/alpaca_chinese.py
Labels: enhancement

#107 ENH: Add meta file to check if model is downloaded
  xinference/core/gradio.py
  xinference/deploy/cmdline.py
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
  xinference/model/__init__.py
  xinference/model/llm/__init__.py
Labels: enhancement

#108 FEAT: slot based model allocation
  xinference/client.py
  xinference/conftest.py
  xinference/core/common.py
  xinference/core/model.py
  xinference/core/service.py
  xinference/deploy/cmdline.py
  xinference/deploy/local.py
  xinference/deploy/test/test_cmdline.py
  xinference/deploy/utils.py
  xinference/deploy/worker.py
  xinference/tests/test_client.py
Labels: feature

#109 BUG: Raise KeyError when get model which is not launched
  xinference/core/service.py
Labels: bug

#110 BUG: fix chatglm download url
  xinference/model/llm/__init__.py
Labels: bug

#111 ENH: basic exception handling for RESTful api
  xinference/client.py
  xinference/core/restful_api.py
Labels: enhancement

#112 BUG: load chatglm
  xinference/core/model.py
  xinference/core/service.py
Labels: bug

#117 ENH: client provides chat and gen interface
  xinference/client.py
  xinference/conftest.py
  xinference/core/api.py
  xinference/core/gradio.py
  xinference/core/service.py
  xinference/core/tests/__init__.py
  xinference/core/tests/test_api.py
  xinference/deploy/supervisor.py
  xinference/tests/test_client.py
Labels: enhancement

#119 ENH: logging for subprocess
  xinference/deploy/cmdline.py
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
  xinference/deploy/utils.py
  xinference/deploy/worker.py
Labels: enhancement

#121 DOC: readme
  README.md
  assets/xinference-downloading.png
  examples/chat.py
  xinference/client.py
  xinference/core/gradio.py
  xinference/core/model.py
  xinference/core/restful_api.py
  xinference/model/llm/chatglm.py
  xinference/model/llm/core.py
  xinference/types.py
Labels: documentation

#126 BUG: worker timeout during downloading
  xinference/core/service.py
Labels: bug

#130 BUG: fix example
  examples/chat.py
Labels: bug

#128 BUG: remove chinese_alpaca model
  README.md
  xinference/model/llm/__init__.py
  xinference/model/llm/alpaca_chinese.py
Labels: bug

#129 BUG: Use sync client in gradio
  xinference/core/api.py
  xinference/core/gradio.py
  xinference/core/tests/test_api.py
  xinference/deploy/supervisor.py
Labels: bug

#118 BUG: chatglm hangs
  examples/chat.py
  xinference/model/llm/chatglm.py
  xinference/model/tests/test_chatglm.py
Labels: bug

#131 DOC: roadmap
  README.md
Labels: documentation

#133 DOC: license
  LICENSE
Labels: documentation

#127 BUG: add error handling when the endpoint port is not available
  xinference/core/restful_api.py
  xinference/deploy/cmdline.py
  xinference/deploy/supervisor.py
Labels: bug

#132 BUG: fix default host in cmdline
  xinference/constants.py
  xinference/deploy/cmdline.py
Labels: bug

#134 TST: Add tests for RESTful API
  xinference/core/tests/test_restful_api.py
Labels: testing

#139 BUG: Include json files in MANIFEST.in
  MANIFEST.in
  README.md
Labels: bug

#143 ENH: auto find available port for API
  xinference/deploy/supervisor.py
Labels: enhancement

#144 ENH: Disable httpx logs
  setup.cfg
  xinference/core/restful_api.py
Labels: enhancement

#146 ENH: socket binding
  xinference/deploy/supervisor.py
Labels: enhancement

#147 ENH: log when worker started
  xinference/core/service.py
  xinference/deploy/supervisor.py
  xinference/deploy/worker.py
Labels: enhancement

#151 BUG: Use utf-8 encoding when open json file
  xinference/locale/utils.py
Labels: bug

#152 ENH: Remove baichuan in gradio dropdown
  xinference/core/gradio.py
Labels: enhancement

#153 ENH: optimize error msg for foundation models
  README.md
  xinference/core/model.py
Labels: enhancement

#155 DOC: Add explicit hint to join slack
  README.md
Labels: documentation

#156 BUG: Fix model selection on gradio page
  xinference/core/gradio.py
Labels: bug

#158 DOC: add logo; make words more concise
  README.md
  assets/xorbits-logo.png
Labels: documentation

#165 BUG: fix example chat
  examples/chat.py
Labels: bug

#161 FEAT: implement chat and generate in RESTful client
  xinference/client.py
  xinference/core/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/tests/test_client.py
Labels: feature

#183 FEAT: support wizard-v1.1
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
Labels: feature

#157 FEAT: support pytorch models
  .github/workflows/python.yaml
  setup.cfg
  xinference/client.py
  xinference/core/restful_api.py
  xinference/model/__init__.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/pytorch/__init__.py
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/utils.py
  xinference/model/llm/pytorch/vicuna.py
  xinference/model/llm/utils.py
  xinference/model/tests/test_model_availablity.py
Labels: feature

#189 DOC: sphinx init
  .readthedocs.yaml
  doc/Makefile
  doc/make.bat
  doc/source/_static/favicon.svg
  doc/source/conf.py
  doc/source/getting_started/index.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/user_guide.po
  doc/source/norm_zh.py
  doc/source/reference/index.rst
  doc/source/user_guide/index.rst
  setup.cfg
Labels: documentation

#191 DOC: chinese readme
  README.md
  README_zh_CN.md
Labels: documentation

#171 ENH: Implement RESTful API stream generate
  setup.cfg
  xinference/client.py
  xinference/core/restful_api.py
  xinference/core/service.py
  xinference/core/tests/test_restful_api.py
  xinference/tests/test_client.py
Labels: enhancement

#192 FEAT: support vicuna-v1.3 33B
  xinference/model/llm/__init__.py
Labels: feature

#190 FEAT: support baichuan-chat pytorch model
  .github/workflows/python.yaml
  setup.cfg
  xinference/client.py
  xinference/model/__init__.py
  xinference/model/llm/__init__.py
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/core.py
Labels: feature

#197 BUG: fix pytorch int8
  xinference/model/llm/pytorch/core.py
Labels: bug

#194 FEAT: Embedding
  xinference/client.py
  xinference/core/model.py
  xinference/core/restful_api.py
  xinference/core/tests/test_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/core.py
  xinference/model/llm/pytorch/core.py
  xinference/tests/test_client.py
Labels: feature

#205 ENH: set default device to `mps` on MacOS
  xinference/model/llm/core.py
  xinference/model/llm/pytorch/core.py
Labels: enhancement

#206 ENH: Set default mlock to true and mmap to false
  xinference/model/llm/core.py
Labels: enhancement

#209 BUG: RuntimeError when launching model using kwargs whose value is of type int
  xinference/client.py
Labels: bug

#200 BUG: Fix some gradio issues
  xinference/core/gradio.py
Labels: bug

#203 FEAT: LLaMA-2
  README.md
  README_zh_CN.md
  xinference/client.py
  xinference/core/gradio.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/llama2.py
  xinference/tests/test_client.py
Labels: feature

#208 ENH: add Gradio ChatInterface chatbot to example
  examples/gradio_chatinterface.py
Labels: enhancement

#213 DOC: Add notes for metal GPU acceleration
  README.md
  README_zh_CN.md
  xinference/core/gradio.py
  xinference/locale/zh_CN.json
Labels: documentation, gpu

#202 BUG: baichuan-chat and baichuan-base don't support MacOS
  .github/workflows/python.yaml
  setup.cfg
  xinference/core/service.py
Labels: bug

#210 BUG: fix pytorch model generate bug when stream is True
  xinference/model/llm/pytorch/utils.py
Labels: bug

#217 BUG: fix baichuan-chat configure
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/core.py
Labels: bug

#216 BUG: Update requirements of gradio
  setup.cfg
Labels: bug

#222 BUG: chat stopwords
  xinference/core/restful_api.py
  xinference/core/tests/test_restful_api.py
Labels: bug

#225 BUG: disable vicuna pytorch model
  xinference/model/llm/__init__.py
Labels: bug

#228 DOC: Add Japanese README
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#196 DOC: Adding Examples to documentation
  doc/source/getting_started/index.rst
  doc/source/reference/index.rst
  doc/source/user_guide/examples/AI_Podcast.rst
  doc/source/user_guide/examples/chat.rst
  doc/source/user_guide/faq.rst
  doc/source/user_guide/index.rst
Labels: documentation

#236 BUG: Set default embedding to be True
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/core.py
  xinference/tests/test_client.py
Labels: bug

#238 FEAT: support fp4 and int8 quantization for pytorch model
  .github/workflows/python.yaml
  setup.cfg
  xinference/core/gradio.py
  xinference/core/service.py
  xinference/model/__init__.py
  xinference/model/llm/__init__.py
  xinference/model/llm/pytorch/compression.py
  xinference/model/llm/pytorch/core.py
Labels: feature

#250 BUG: disable baichuan-chat and baichuan-base on macos
  xinference/core/service.py
  xinference/model/llm/pytorch/core.py
Labels: bug

#259 TST: Update ChatGLM Tests
  xinference/model/llm/ggml/tests/test_chatglm.py
Labels: testing

#258 BUG: delete tqdm_class in snapshot_download
  xinference/core/gradio.py
  xinference/core/service.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: bug

#262 BUG: ChatGLM Parameter Switch
  xinference/core/service.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/pytorch/core.py
Labels: bug

#257 FEAT: support llama-2-chat-70b ggml
  setup.cfg
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
Labels: feature

#264 ENH: skip 4-bit quantization for non-linux or non-cuda local deployment
  xinference/core/api.py
  xinference/core/gradio.py
  xinference/core/service.py
  xinference/model/llm/__init__.py
Labels: enhancement, gpu

#265 BUG: refresh related fields when format changes
  xinference/core/gradio.py
Labels: bug

#253 DOC: Update installation part in readme
  README.md
  README_ja_JP.md
  README_zh_CN.md
  setup.cfg
Labels: documentation

#266 ENH: handle legacy cache
  xinference/core/gradio.py
  xinference/core/service.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: enhancement

#207 DOC: update readme for pytorch model
  README.md
  README_zh_CN.md
Labels: documentation

#267 BUG: Show downloading progress in gradio
  xinference/core/gradio.py
Labels: bug

#268 BUG: LLM json not included
  MANIFEST.in
Labels: bug

#269 DOC: Update README_ja_JP.md
  README_ja_JP.md
Labels: documentation

#274 BUG: fix import torch error even if user don't want to launch torch model
  xinference/model/llm/pytorch/core.py
Labels: bug

#276 BUG: empty legacy model dir
  xinference/model/llm/llm_family.py
Labels: bug

#263 FEAT: add opt-125m pytorch model and add ut
  xinference/core/gradio.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/tests/__init__.py
  xinference/model/llm/pytorch/tests/test_opt.py
Labels: feature
