Repository xorbitsai/inference, pull requests merged in 2023-09, with the labels that each got.

#415 BUG: empty results for non-stream inference
  xinference/model/llm/pytorch/utils.py
Labels: bug

#394 BUG: Make context_length optional in model family
  doc/source/models/custom.rst
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: bug

#418 FEAT: Add embedding models support
  .github/workflows/python.yaml
  examples/LangChain_QA.ipynb
  setup.cfg
  xinference/client.py
  xinference/core/api.py
  xinference/core/model.py
  xinference/core/restful_api.py
  xinference/core/supervisor.py
  xinference/core/tests/test_api.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/core.py
  xinference/model/embedding/__init__.py
  xinference/model/embedding/core.py
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/tests/__init__.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/core.py
  xinference/tests/test_client.py
Labels: feature

#410 FEAT: Support replica
  xinference/client.py
  xinference/core/api.py
  xinference/core/restful_api.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_utils.py
  xinference/core/utils.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
  xinference/model/llm/core.py
  xinference/tests/test_client.py
Labels: feature

#423 DOC: update readme
  README.md
  README_ja_JP.md
  README_zh_CN.md
  assets/index.jpg
Labels: documentation

#428 BUG: cmdline chat duplicates user msg
  xinference/deploy/cmdline.py
Labels: bug

#425 FEAT: support baichuan2
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/models/builtin/baichuan-2-chat.rst
  doc/source/models/builtin/baichuan-2.rst
  doc/source/models/builtin/index.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/core.py
Labels: feature, new model

#431 BUG: Searching in UI results in white screen
  xinference/web/ui/src/scenes/launch_model/index.js
Labels: bug

#435 BUG: Include json in MANIFEST.in
  MANIFEST.in
Labels: bug

#421 DOC: Embedding models
  README.md
  doc/source/models/builtin/bge-base-en.rst
  doc/source/models/builtin/bge-base-zh.rst
  doc/source/models/builtin/bge-large-en.rst
  doc/source/models/builtin/bge-large-zh-noinstruct.rst
  doc/source/models/builtin/bge-large-zh.rst
  doc/source/models/builtin/bge-small-zh.rst
  doc/source/models/builtin/e5-large-v2.rst
  doc/source/models/builtin/gte-base.rst
  doc/source/models/builtin/gte-large.rst
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/multilingual-e5-large.rst
Labels: documentation

#432 DOC: fix baichuan-2 and make naming consistent
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/llama-2-chat.rst
Labels: documentation

#439 BUG: Fix restful client for embedding models
  xinference/client.py
  xinference/tests/test_client.py
Labels: bug

#441 BUG: cmdline double line breaker
  xinference/deploy/cmdline.py
Labels: bug

#442 ENH: client support desc model
  xinference/client.py
Labels: enhancement

#419 ENH: caching from self-hosted storage
  .github/workflows/python.yaml
  README.md
  README_ja_JP.md
  README_zh_CN.md
  setup.cfg
  xinference/constants.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: enhancement

#443 BUG: no error raised on unsupported fmt
  xinference/model/llm/llm_family.py
Labels: bug

#437 ENH: Assign worker sub pool at runtime instead of pre-allocated
  xinference/client.py
  xinference/conftest.py
  xinference/core/restful_api.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/local.py
  xinference/deploy/utils.py
  xinference/deploy/worker.py
  xinference/model/llm/pytorch/core.py
  xinference/tests/test_client.py
Labels: enhancement

#453 TST: skip self-hosted storage tests
  xinference/model/llm/tests/test_llm_family.py
Labels: testing

#446 FEAT: Support gguf
  .github/workflows/python.yaml
  setup.cfg
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_gguf.py
  xinference/model/llm/ggml/tools/__init__.py
  xinference/model/llm/ggml/tools/convert_ggml_to_gguf.py
  xinference/model/llm/ggml/tools/gguf.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: feature

#456 DOC: update hot topics
  README.md
  README_zh_CN.md
  doc/source/index.rst
  doc/source/models/builtin/llama-2-chat.rst
  doc/source/models/builtin/llama-2.rst
Labels: documentation

#452 BUG: Xinferecen list failed if embedding models are launched
  xinference/deploy/cmdline.py
Labels: bug

#451 ENH: add benchmark script
  benchmark/benchmark_serving.py
Labels: enhancement

#444 FEAT: Support OpenBuddy
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/openbuddy.rst
  examples/AI_translate.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/utils.py
Labels: feature

#465 BUG: stop auto download from self-hosted storage for locale zh_CN
  xinference/model/llm/llm_family.py
Labels: bug

#455 TST: Fix windows CI
  xinference/model/llm/ggml/tests/test_ctransformers.py
  xinference/tests/test_client.py
Labels: testing

#460 DOC: Getting started guide for beginners
  doc/source/getting_started.rst
  doc/source/getting_started/accessing_models.rst
  doc/source/getting_started/index.rst
  doc/source/getting_started/installation.rst
  doc/source/getting_started/launching_models.rst
  doc/source/getting_started/troubleshooting.rst
  doc/source/getting_started/using_xinference.rst
  doc/source/index.rst
  doc/source/installation.rst
  doc/source/models/builtin/index.rst
  doc/source/user_guide/faq.rst
Labels: documentation

#471 ENH: shorten OpenBuddy's desc
  xinference/model/llm/llm_family.json
Labels: enhancement

#445 FEAT: incorporate vLLM
  doc/source/models/builtin/llama-2.rst
  doc/source/models/custom.rst
  setup.cfg
  xinference/core/model.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/falcon.py
  xinference/model/llm/pytorch/llama_2.py
  xinference/model/llm/pytorch/vicuna.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/__init__.py
  xinference/model/llm/vllm/core.py
Labels: feature

#420 FEAT: add register model page for dashboard
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/web/ui/public/index.html
  xinference/web/ui/src/App.js
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/index.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/running_models/index.js
  xinference/web/ui/src/theme.js
Labels: feature

#473 BUG: llama-cpp version dismatch
  setup.cfg
Labels: bug

#472 ENH: enable vLLM on Linux with cuda
  xinference/model/llm/core.py
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/vllm/core.py
Labels: enhancement, gpu

#474 BUG: incorrect endpoint on host 0.0.0.0
  xinference/core/restful_api.py
  xinference/deploy/supervisor.py
Labels: bug

#477 ENH: vLLM engine supports more models
  xinference/model/llm/vllm/core.py
Labels: enhancement

#478 ENH: remove subpool on failure
  xinference/core/worker.py
Labels: enhancement

#479 ENH: support trust_remote_code when launching a model
  xinference/deploy/cmdline.py
  xinference/model/llm/pytorch/core.py
Labels: enhancement

#480 ENH: vLLM auto tensor parallel
  xinference/model/llm/core.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#486 FEAT: internlm 20b
  README.md
  README_ja_JP.md
  README_zh_CN.md
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature

#489 BUG: prompt style not set as expected on web UI
  xinference/web/ui/src/scenes/register_model/index.js
Labels: bug

#490 FEAT: support glaive coder
  README.md
  README_ja_JP.md
  README_zh_CN.md
  xinference/model/llm/llm_family.json
Labels: feature

#475 FEAT: Support download models from modelscope
  .github/workflows/python.yaml
  README.md
  README_ja_JP.md
  README_zh_CN.md
  setup.cfg
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/vllm/core.py
  xinference/tests/test_client.py
Labels: feature

#491 DOC: vLLM
  doc/source/getting_started/accessing_models.rst
  doc/source/getting_started/troubleshooting.rst
  doc/source/models/builtin/baichuan-2-chat.rst
  doc/source/models/builtin/baichuan-2.rst
  doc/source/models/builtin/openbuddy.rst
  doc/source/models/builtin/wizardmath-v1.0.rst
  doc/source/user_guide/backends.rst
  doc/source/user_guide/index.rst
Labels: documentation

#449 ENH: Safe iterate stream of ggml model
  .github/workflows/python.yaml
  setup.cfg
  xinference/client.py
  xinference/core/model.py
  xinference/core/restful_api.py
  xinference/tests/test_client.py
Labels: enhancement

#495 ENH: Skip download if model exists
  xinference/model/llm/llm_family.py
Labels: enhancement

#476 ENH: validate model URI on register
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: enhancement

#499 ENH: Skip download for embedding models
  xinference/model/embedding/core.py
Labels: enhancement

#500 ENH: set `trust_remote_code` to true
  xinference/deploy/cmdline.py
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/falcon.py
  xinference/model/llm/vllm/core.py
Labels: enhancement
