Repository xorbitsai/inference, pull requests merged in 2023-11, with the labels that each got.

#600 BUG: fix transformers compatibility
  setup.cfg
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#575 FEAT: stable diffusion with controlnet
  setup.cfg
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/core/restful_api.py
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: feature

#604 ENH: increase heartbeat interval
  xinference/core/worker.py
Labels: enhancement

#605 DOC: Stable Diffusion with ControlNet example
  examples/StableDiffusionControlNet.ipynb
Labels: documentation

#595 ENH: Support more models downloading from modelscope
  doc/source/models/sources/sources.rst
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#590 ENH: Supports rotating file log
  .github/workflows/release.yaml
  doc/source/getting_started/using_xinference.rst
  xinference/constants.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
Labels: enhancement

#603 TST: Compatible with `llama-cpp-python` 0.2.12
  .github/workflows/python.yaml
  xinference/client/tests/test_client.py
  xinference/deploy/test/test_cmdline.py
Labels: testing

#546 ENH: stateless supervisor and worker
  xinference/api/__init__.py
  xinference/api/restful_api.py
  xinference/conftest.py
  xinference/core/api.py
  xinference/core/chat_interface.py
  xinference/core/supervisor.py
  xinference/core/tests/test_worker.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
  xinference/deploy/test/test_cmdline.py
  xinference/deploy/utils.py
  xinference/deploy/worker.py
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#610 ENH: add command xinference-local
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/getting_started/using_xinference.rst
  examples/gradio_chatinterface.py
  setup.cfg
  xinference/deploy/cmdline.py
Labels: enhancement

#614 ENH: Don't check dead nodes
  xinference/core/supervisor.py
Labels: enhancement

#617 DOC: Change links for some tutorials
  doc/source/examples/index.rst
Labels: documentation

#619 BUG: Compatible with openai 1.1
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/common.py
  xinference/client/tests/test_client.py
  xinference/core/model.py
  xinference/core/tests/test_restful_api.py
Labels: bug

#596 ENH: Supports request limits for the model
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
Labels: enhancement

#628 BUG: fix spec decoding
  xinference/api/restful_api.py
Labels: bug

#611 BUG: `No slot available` error for embedding and LLM model on one card
  xinference/core/model.py
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
Labels: bug, gpu

#626 ENH: running model location & accelerators
  xinference/client/tests/test_client.py
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
  xinference/model/core.py
  xinference/model/embedding/core.py
  xinference/model/image/core.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#618 BUG: Rotating log does not create a new one when recreate the xinference cluster
  .github/workflows/python.yaml
  xinference/conftest.py
  xinference/deploy/__init__.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
  xinference/deploy/utils.py
Labels: bug

#622 ENH: Create completion restful api compatibility
  setup.cfg
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_types.py
  xinference/fields.py
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/spec_decoding_utils.py
  xinference/model/llm/pytorch/spec_model.py
  xinference/model/llm/pytorch/tests/test_spec_decoding.py
  xinference/model/llm/pytorch/utils.py
  xinference/types.py
Labels: enhancement

#629 FEAT: Support Yi Model
  README.md
  README_zh_CN.md
  doc/source/models/builtin/Yi-200k.rst
  doc/source/models/builtin/Yi.rst
  doc/source/models/builtin/index.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#631 DOC: About Logging in Xinference
  doc/source/getting_started/index.rst
  doc/source/getting_started/logging.rst
  doc/source/getting_started/using_xinference.rst
Labels: documentation

#641 TST: disable test_is_self_hosted
  xinference/model/llm/tests/test_llm_family.py
Labels: testing

#565 DOC: Init for Chinese doc
  doc/source/locale/zh_CN/LC_MESSAGES/examples/ai_podcast.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/chatbot.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/accessing_models.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/launching_models.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/builtin/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/custom.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/cache_management.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/client_api.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/user_guide.po
Labels: documentation

#494 FEAT: qwen-chat-14b
  doc/source/models/builtin/qwen-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#648 BUG: Fix restful api serialization slow
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/tests/test_client.py
  xinference/core/model.py
  xinference/core/utils.py
Labels: bug

#645 FEAT: Support gptq quantization
  setup.cfg
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
Labels: feature

#638 DOC: update pot files
  doc/source/locale/ja_JP/LC_MESSAGES/examples/index.po
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/logging.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/builtin/Yi-200k.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/builtin/Yi.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/builtin/index.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/builtin/qwen-chat.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/sources/sources.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/logging.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/builtin/Yi-200k.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/builtin/Yi.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/builtin/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/builtin/qwen-chat.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/sources/sources.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/index.po
  doc/source/models/builtin/qwen-chat.rst
Labels: documentation

#674 BUG: Fix custom model missing config json
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/model/llm/llm_family.py
Labels: bug

#657 BUG: Fix http error is not raised
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
Labels: bug

#671 ENH: Add `generate` interface for `chatglm` with `ggml` format
  xinference/client/restful/restful_client.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/tests/test_chatglm.py
Labels: enhancement

#651 DOC: A more detailed beginner's guide has been created, covering various aspects of the first-time usage experience for new users.
  .github/workflows/python.yaml
  doc/source/conf.py
  doc/source/getting_started/accessing_models.rst
  doc/source/getting_started/index.rst
  doc/source/getting_started/launching_models.rst
  doc/source/getting_started/using_xinference.rst
  setup.cfg
Labels: documentation

#679 BUG: Fix pip install xinference[all]
  setup.cfg
Labels: bug

#667 FEAT: Support registering custom embedding model
  xinference/client/tests/test_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/embedding/__init__.py
  xinference/model/embedding/core.py
  xinference/model/embedding/custom.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
  xinference/model/utils.py
Labels: feature

#675 FEAT: Supports `qwen.cpp` for `qwen-chat` with `ggml` format
  xinference/api/restful_api.py
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/qwen.py
  xinference/model/llm/ggml/tests/test_qwen.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/types.py
Labels: feature

#677 DOC: documentation for using xinference
  doc/source/getting_started/using_xinference.rst
Labels: documentation

#678 FEAT: Xverse
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/xverse-chat.rst
  doc/source/models/builtin/xverse.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: feature

#672 FEAT: Support rerank models
  .github/workflows/python.yaml
  doc/source/models/builtin/bge-reranker-base.rst
  doc/source/models/builtin/bge-reranker-large
  doc/source/models/builtin/index.rst
  doc/source/user_guide/client_api.rst
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/model/core.py
  xinference/model/embedding/core.py
  xinference/model/image/core.py
  xinference/model/rerank/__init__.py
  xinference/model/rerank/core.py
  xinference/model/rerank/model_spec.json
  xinference/model/rerank/model_spec_modelscope.json
  xinference/model/rerank/tests/__init__.py
  xinference/model/rerank/tests/test_rerank.py
  xinference/types.py
Labels: feature

#683 DOC: Register custom embedding model
  doc/source/models/builtin/qwen-chat.rst
  doc/source/models/custom.rst
Labels: documentation

#684 Doc: Fix some incorrect links in documentation
  doc/source/models/builtin/bge-reranker-large.rst
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/xverse-chat.rst
  doc/source/models/builtin/xverse.rst
  doc/source/user_guide/client_api.rst
Labels: documentation

#688 ENH: Specify actor pool port for distributed deployment
  xinference/deploy/cmdline.py
  xinference/deploy/supervisor.py
Labels: enhancement

#690 BUG: Fix xinference start failed if invalid custom model found
  xinference/model/embedding/__init__.py
  xinference/model/embedding/custom.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/llm_family.py
Labels: bug

#699 ENH: Remove `xorbits` dependency
  setup.cfg
  xinference/constants.py
  xinference/core/resource.py
  xinference/core/worker.py
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
  xinference/deploy/worker.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/utils.py
Labels: enhancement

#682 ENH: User can just specify a string for prompt style when registering custom LLM models
  doc/source/examples/langchain_streamlit_doc_chat.rst
  doc/source/models/builtin/bge-reranker-large.rst
  doc/source/models/builtin/index.rst
  doc/source/models/custom.rst
  xinference/api/restful_api.py
  xinference/client/tests/test_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/web/ui/src/scenes/register_model/index.js
Labels: enhancement

#704 FEAT: Support jina embedding models
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/jina-embeddings-v2-base-en.rst
  doc/source/models/builtin/jina-embeddings-v2-small-en.rst
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
Labels: feature
