Repository xorbitsai/inference, pull requests merged in 2023-12, with the labels that each got.

#706 ENH: Add more models supported by vllm
  xinference/constants.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: enhancement

#661 DOC: documentation for docker and k8s
  doc/source/getting_started/using_xinference.rst
Labels: documentation

#700 FEAT: Support Yi-chat
  doc/source/models/builtin/Yi-chat.rst
  doc/source/models/builtin/index.rst
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#701 FEAT: ChatGLM3 tool calls
  .github/workflows/python.yaml
  examples/FunctionCall.ipynb
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/conftest.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_types.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: feature

#710 BUG: Auto patch trust remote code for embedding model
  xinference/client/tests/test_client.py
  xinference/model/embedding/core.py
  xinference/model/utils.py
Labels: bug

#712 ENH: upgrade insecure requests when necessary
  xinference/web/ui/public/index.html
Labels: enhancement

#714 ENH: [UI] Using tab in running models
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#711 ENH: [UI] supports launching rerank models
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchRerank.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#728 BUG: Fix vLLM backend
  xinference/core/model.py
  xinference/model/llm/vllm/core.py
Labels: bug

#721 ENH: [UI] Error can be shown on web UI directly via Snackbar
  xinference/web/ui/src/components/apiContext.js
  xinference/web/ui/src/components/errorMessageSnackBar.js
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/register_model/index.js
Labels: enhancement

#730 ENH: [UI] Supports `n_gpu` config when launching LLM models on web ui
  xinference/api/restful_api.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement, gpu

#738 ENH: [UI] `n_gpu` default value `auto`
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement, gpu

#694 ENH: Auto recover model actor
  setup.cfg
  xinference/client/tests/test_client.py
  xinference/core/model.py
  xinference/core/worker.py
  xinference/deploy/utils.py
  xinference/types.py
Labels: enhancement

#741 ENH: allow rerank models run with LLM models on same device
  xinference/core/worker.py
Labels: enhancement

#746 ENH: [UI] Supports `model_uid` input when launching models
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#748 BUG: Fix `cached` tag on UI
  .pre-commit-config.yaml
  xinference/api/restful_api.py
  xinference/core/chat_interface.py
  xinference/core/supervisor.py
  xinference/deploy/utils.py
  xinference/model/embedding/__init__.py
  xinference/model/embedding/core.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/rerank/__init__.py
  xinference/model/rerank/core.py
  xinference/model/utils.py
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchEmbedding.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/launchRerank.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#756 ENH: Add more vllm supported models
  .github/workflows/python.yaml
  .pre-commit-config.yaml
  xinference/api/restful_api.py
  xinference/core/chat_interface.py
  xinference/core/supervisor.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#758 BUG: Fix stream arg for vllm backend
  xinference/model/llm/vllm/core.py
Labels: bug

#759 DOC: Fix `model_uri` missing in `Custom Models`
  doc/source/models/custom.rst
Labels: documentation

#757 FEAT: Supports `qwen-chat` 1.8B
  .pre-commit-config.yaml
  doc/source/models/builtin/llm/qwen-chat.rst
  doc/source/models/builtin/rerank/bge-reranker-base.rst
  doc/source/models/builtin/rerank/bge-reranker-large.rst
  xinference/model/llm/core.py
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#760 FEAT: Support gorilla openfunctions v1
  xinference/api/restful_api.py
  xinference/client/tests/test_client.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: feature

#764 BUG: [UI] Fix model size selection crash issue
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#763 FEAT: qwen function call
  create_test_data.py
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/utils.py
Labels: feature

#767 ENH: Handle tool call failed
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/utils.py
Labels: enhancement

#743 DOC: Update readme
  README.md
  README_zh_CN.md
  doc/source/index.rst
Labels: documentation

#773 DOC: Update FunctionCall.ipynb
  examples/FunctionCall.ipynb
Labels: documentation

#772 BUG: UI Crash on Search when `model_format` and `model_size` have been selected
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#776 FEAT: Support OpenHermes 2.5
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/openhermes-2.5.rst
  xinference/model/llm/llm_family.json
Labels: feature, gpu

#777 BUG: When changing `XINFERENCE_HOME` env, the model files are still stored where they were.
  xinference/constants.py
Labels: bug

#788 BUG: Remove the modelscope import
  doc/source/models/sources/sources.rst
  setup.cfg
  xinference/deploy/__init__.py
  xinference/model/llm/vllm/core.py
Labels: bug, gpu

#779 BUG: when terminating worker by `ctrl+C`, supervisor does not remove worker information
  xinference/core/supervisor.py
  xinference/core/worker.py
Labels: bug

#784 ENH: Enable streaming on Ctransformer
  xinference/types.py
Labels: enhancement

#785 ENH: vllm backend support tool calls
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#778 ENH: qwen switch to llama cpp
  .github/workflows/python.yaml
  setup.cfg
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/qwen.py
  xinference/model/llm/ggml/tests/test_qwen.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
  xinference/model/utils.py
Labels: enhancement

#794 FEAT: Support tool message
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: feature

#782 FEAT: Support Mixtral-8x7B-v0.1 models
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/mixtral-instruct-v0.1.rst
  doc/source/models/builtin/llm/mixtral-v0.1.rst
  xinference/client/restful/restful_client.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
Labels: feature

#790 BUG: Xinference does not release custom model name when registering failed
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/embedding/custom.py
  xinference/model/llm/llm_family.py
Labels: bug

#791 ENH: [UI] register custom embedding model
  xinference/model/embedding/custom.py
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/register_embedding.js
Labels: enhancement

#796 FEAT: Support mistral instruct v0.2
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/mistral-instruct-v0.2.rst
  doc/source/models/builtin/llm/qwen-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#800 BUG: Worker starts failed on windows
  xinference/core/worker.py
  xinference/model/llm/tests/test_llm_family.py
Labels: bug

#804 DOC: add function calling in read me
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#808 BUG: launch method exception (#807)
  xinference/deploy/cmdline.py
Labels: bug

#797 FEAT: Support sd-turbo
  .github/workflows/python.yaml
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: feature

#809 FEAT: Support Skywork models
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/skywork-math.rst
  doc/source/models/builtin/llm/skywork.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#820 DOC: remove version limit of sphinx
  setup.cfg
Labels: documentation

#816 FEAT: Support sdxl-turbo
  xinference/model/image/model_spec.json
  xinference/model/image/tests/test_stable_diffusion.py
Labels: feature

#821 DOC: polish function call description
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#822 DOC: add switcher.json
  doc/source/_static/switcher.json
Labels: documentation

#823 DOC: add document language switcher
  doc/source/conf.py
Labels: documentation

#812 BUG: Model description does not support Chinese from UI registering
  xinference/web/ui/src/scenes/register_model/index.js
Labels: bug

#824 DOC: use wechat and zhihu for zh doc
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/conf.py
Labels: documentation

#818 ENH: Custom model can use tool calls
  xinference/api/restful_api.py
Labels: enhancement

#833 DOC: Chinese doc for getting started
  doc/source/getting_started/installation.rst
  doc/source/locale/ja_JP/LC_MESSAGES/examples/ai_podcast.po
  doc/source/locale/ja_JP/LC_MESSAGES/examples/index.po
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/logging.po
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/ja_JP/LC_MESSAGES/index.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/builtin/index.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/custom.po
  doc/source/locale/ja_JP/LC_MESSAGES/models/sources/sources.po
  doc/source/locale/ja_JP/LC_MESSAGES/reference/index.po
  doc/source/locale/ja_JP/LC_MESSAGES/user_guide/client_api.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/accessing_models.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/launching_models.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
Labels: documentation

#835 BUG: Find correct class for customized model
  xinference/model/llm/pytorch/core.py
Labels: bug

#825 FEAT: Supports registering rerank models
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/rerank/__init__.py
  xinference/model/rerank/core.py
  xinference/model/rerank/custom.py
  xinference/model/rerank/tests/test_rerank.py
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchRerank.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/register_rerank.js
Labels: feature

#826 DOC: simplify entry doc
  README.md
  README_ja_JP.md
  README_zh_CN.md
  assets/screenshot.png
Labels: documentation

#838 DOC: Chinese doc for `example` part
  doc/source/locale/zh_CN/LC_MESSAGES/examples/ai_podcast.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/chatbot.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/gradio_chatinterface.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/langchain_streamlit_doc_chat.po
  doc/source/locale/zh_CN/LC_MESSAGES/examples/pdf_chatbot.po
Labels: documentation

#828 FEAT: Support Phi-2
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/phi-2.rst
  doc/source/models/builtin/llm/skywork-math.rst
  doc/source/models/builtin/llm/skywork.rst
  setup.cfg
  xinference/model/llm/llm_family.json
Labels: feature

#832 FEAT: Support vllm gptq
  doc/source/getting_started/installation.rst
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  setup.cfg
  xinference/model/llm/llm_family.py
  xinference/model/llm/vllm/core.py
Labels: feature

#831 ENH: Replace uuid with model name for `model_uid`
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_utils.py
  xinference/core/utils.py
  xinference/model/embedding/custom.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/rerank/custom.py
  xinference/model/rerank/tests/test_rerank.py
  xinference/model/utils.py
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/register_embedding.js
  xinference/web/ui/src/scenes/register_model/register_rerank.js
Labels: enhancement

#829 FEAT: Support qwen vl chat
  create_test_data.py
  xinference/core/supervisor.py
  xinference/model/core.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/spec_model.py
  xinference/model/multimodal/__init__.py
  xinference/model/multimodal/core.py
  xinference/model/multimodal/model_spec.json
  xinference/model/multimodal/qwen_vl.py
  xinference/model/multimodal/tests/__init__.py
  xinference/model/multimodal/tests/test_multimodal.py
  xinference/model/utils.py
Labels: feature

#842 DOC: Multimodal example
  examples/chat_vl.ipynb
  xinference/client/restful/restful_client.py
  xinference/model/multimodal/core.py
  xinference/model/multimodal/qwen_vl.py
  xinference/model/multimodal/tests/test_multimodal.py
Labels: documentation
