Repository xorbitsai/inference, pull requests merged in 2024-05, with the labels that each got.

#1417 DOC: update docker doc in using xinference
  README.md
  README_zh_CN.md
  doc/source/getting_started/using_docker_image.rst
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
Labels: documentation

#1420 BUG: Fix tool calls return invalid usage
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/utils.py
Labels: bug

#1380 FEAT: Support query engine with cmdline
  xinference/client/restful/restful_client.py
  xinference/deploy/cmdline.py
Labels: feature

#1408 FEAT: Ascend support
  .pre-commit-config.yaml
  xinference/core/supervisor.py
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
  xinference/deploy/utils.py
  xinference/device_utils.py
  xinference/model/llm/__init__.py
  xinference/model/llm/pytorch/deepseek_vl.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/thirdparty/omnilmm/chat.py
  xinference/thirdparty/omnilmm/model/omnilmm.py
Labels: feature, gpu

#1427 TST: Pin `huggingface-hub` to pass CI since it has some break changes
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
Labels: testing

#1367 REF: Add the `model_engine` parameter for launching process
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/core/supervisor.py
  xinference/core/tests/test_metrics.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
  xinference/model/core.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/ggml/tests/test_gguf.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/llm/tests/test_llm_family.py
Labels: refactor

#1402 FEAT: Audio support verbose_json and timestamp
  .github/workflows/python.yaml
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/model/audio/tests/test_whisper.py
  xinference/model/audio/whisper.py
Labels: feature

#1436 CLN: Remove actor client
  xinference/client/oscar/__init__.py
  xinference/client/oscar/actor_client.py
  xinference/client/tests/test_client.py
  xinference/model/audio/tests/test_whisper.py
Labels: enhancement

#1425 ENH: make qwen_vl support streaming output
  xinference/api/oauth2/auth_service.py
  xinference/core/cache_tracker.py
  xinference/core/event.py
  xinference/core/status_guard.py
  xinference/fields.py
  xinference/model/llm/ggml/tools/convert_ggml_to_gguf.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/types.py
Labels: enhancement

#1429 ENH: Removed the max tokens limitation and boost performance by avoid unnecessary repeated cuda device detection.
  xinference/fields.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement, gpu

#1451 DOC: add the missing backslash in shell command
  benchmark/README.md
Labels: documentation

#1447 BUG: Fix tools ability
  xinference/core/supervisor.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
Labels: bug

#1443 ENH: make yi_vl support streaming output
  xinference/model/llm/pytorch/yi_vl.py
Labels: enhancement

#1435 CLN: Remove all speculative-related codes
  doc/source/_static/speculative.gif
  doc/source/_static/speculative_decoding.jpeg
  doc/source/locale/ja_JP/LC_MESSAGES/user_guide/spec_decoding.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/spec_decoding.po
  doc/source/user_guide/index.rst
  doc/source/user_guide/spec_decoding.rst
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/llm/core.py
  xinference/model/llm/pytorch/spec_decoding_utils.py
  xinference/model/llm/pytorch/spec_model.py
  xinference/model/llm/pytorch/tests/test_spec_decoding.py
Labels: enhancement

#1453 ENH: Some minor changes
  xinference/core/worker.py
  xinference/model/llm/core.py
Labels: enhancement

#1457 BUG: Install error on MacOS due to `auto-gptq`
  setup.cfg
Labels: bug

#1442 BUG: fix some issues in query engine interface
  xinference/model/llm/__init__.py
  xinference/model/llm/tests/test_llm_family.py
Labels: bug

#1456 FEAT: [UI] Add engine option when launching LLM
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1444 ENH: make deepseek_vl support streaming output
  xinference/model/llm/pytorch/deepseek_vl.py
Labels: enhancement

#1466 ENH: Rename `model_engine` for more clear inference backend
  xinference/client/tests/test_client.py
  xinference/core/tests/test_metrics.py
  xinference/core/tests/test_restful_api.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/tests/test_gguf.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/llm/tests/test_llm_family.py
Labels: enhancement

#1468 DOC: Usage about `model_engine`
  doc/source/getting_started/installation.rst
  doc/source/getting_started/troubleshooting.rst
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/client_api.po
  doc/source/user_guide/backends.rst
  doc/source/user_guide/client_api.rst
  setup.cfg
  xinference/api/restful_api.py
  xinference/deploy/docker/cpu.Dockerfile
Labels: documentation

#1461 BUG: fix top_k for vllm backend
  xinference/model/llm/vllm/core.py
Labels: bug

#1482 DOC: update quick start ipynb
  README.md
  examples/Xinference_Quick_Start.ipynb
Labels: documentation

#1493 DOC: Update readme for being integrated by RAGFlow
  README.md
  README_zh_CN.md
Labels: documentation

#1489 FEAT: support Yi-1.5 series
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/codeqwen1.5-chat.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/yi-1.5-chat.rst
  doc/source/models/builtin/llm/yi-1.5.rst
  doc/source/models/builtin/llm/yi-200k.rst
  doc/source/models/builtin/llm/yi-chat.rst
  doc/source/models/builtin/llm/yi-vl-chat.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1491 FEAT: [UI] embedding and rerank support the specified GPU and CPU.
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature, gpu

#1485 BUG: Docker image issue due to `torchvision`
  .github/workflows/docker-cd.yaml
  xinference/deploy/docker/Dockerfile
Labels: bug

#1470 ENH: Refactoring the LoRa adaptation method for the LLM model.
  doc/source/models/lora.rst
  xinference/core/chat_interface.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
Labels: enhancement

#1506 DOC: Lora usage
  doc/source/locale/zh_CN/LC_MESSAGES/models/lora.po
  doc/source/models/lora.rst
Labels: documentation

#1507 BUG: Docker image crash during startup due to `llama-cpp-python`
  xinference/deploy/docker/Dockerfile
Labels: bug

#1512 BUG: Fix prompt is needed when docker image builds
  xinference/deploy/docker/Dockerfile
Labels: bug

#1508 ENH: Add stream_options support
  xinference/core/model.py
  xinference/fields.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_chatglm.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/deepseek_vl.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/utils.py
  xinference/model/llm/pytorch/yi_vl.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/tests/test_stream_options.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
Labels: enhancement

#1513 BUG: `llama.cpp` model failed when chat due to `lora`
  xinference/model/llm/ggml/llamacpp.py
  xinference/types.py
Labels: bug

#1521 BLD: adapt to langchain 0.2.x, which has breaking changes
  setup.cfg
Labels: build

#1460 FEAT: Add command cal-model-mem
  .gitignore
  xinference/deploy/cmdline.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/memory.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/tests/test_memory_estimate.py
Labels: feature, gpu

#1514 ENH: Compatible with `huggingface-hub` `v0.23.0`
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/utils.py
Labels: enhancement

#1527 BLD: Fix pre commit
  doc/source/development/xinference_internals.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/xinference_internals.po
  xinference/thirdparty/deepseek_vl/models/processing_vlm.py
  xinference/thirdparty/deepseek_vl/models/siglip_vit.py
  xinference/thirdparty/deepseek_vl/serve/app_deepseek.py
  xinference/thirdparty/deepseek_vl/serve/app_modules/utils.py
  xinference/thirdparty/deepseek_vl/serve/assets/custom.css
  xinference/thirdparty/llava/mm_utils.py
  xinference/thirdparty/llava/model/llava_arch.py
Labels: build

#1535 FEAT: add codeqwen1.5
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/codeqwen1.5.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1534 BLD: compatible with torch 2.3.0
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
  xinference/thirdparty/omnilmm/chat.py
Labels: build, gpu

#1539 BUG: Fix start worker failed due to None device name
  .github/workflows/python.yaml
  xinference/core/worker.py
Labels: bug

#1538 FEAT: Auto detect rerank type for unknown rerank type
  xinference/model/rerank/core.py
  xinference/model/rerank/tests/test_rerank.py
Labels: feature

#1536 ENH: Support Intern-VL-Chat model
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/intern_vl.py
Labels: enhancement

#1522 FEAT: Provide the functionality to query information on various cached models hosted on the query node.
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/core/cache_tracker.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
Labels: feature

#1543 BUG: fix launch model error when use torch 2.3.0
  xinference/model/llm/pytorch/intern_vl.py
Labels: bug

#1544 FEAT: support Yi-1.5-chat-16k
  README.md
  README_zh_CN.md
  doc/source/gen_docs.py
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/starling-lm.rst
  doc/source/models/builtin/llm/yi-1.5-chat-16k.rst
  doc/source/models/builtin/llm/yi-1.5-chat.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1559 BUG: fix vl-model img path error
  xinference/core/chat_interface.py
Labels: bug

#1547 FEAT: Support XINFERENCE_DISABLE_METRICS env
  doc/source/getting_started/environments.rst
  xinference/api/restful_api.py
  xinference/constants.py
  xinference/core/tests/test_metrics.py
  xinference/core/worker.py
Labels: feature

#1561 ENH: add additional_option at vl gradio
  xinference/core/chat_interface.py
  xinference/model/llm/pytorch/intern_vl.py
Labels: enhancement

#1551 FEAT: Support new model CogVLM
  doc/source/models/builtin/llm/cogvlm2.rst
  doc/source/models/builtin/llm/index.rst
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/cogvlm2.py
  xinference/model/llm/pytorch/core.py
Labels: feature

#1566 DOC: update readme and fix description about model engine
  README.md
  README_zh_CN.md
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/environments.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/vision.po
  doc/source/models/index.rst
  doc/source/models/model_abilities/vision.rst
Labels: documentation

#1567 FEAT: telechat model
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/telechat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#1555 ENH: add real paths column
  xinference/core/cache_tracker.py
  xinference/core/supervisor.py
Labels: enhancement
