Repository xorbitsai/inference, pull requests merged in 2024-07, with the labels that each got.

#1753 BLD: Supports Aliyun docker image
  .github/workflows/docker-cd.yaml
Labels: build

#1747 BUG: Fix glm4 tool call
  xinference/api/restful_api.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/utils.py
Labels: bug

#1759 BLD: GPU docker use `vllm` image as base
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/requirements.txt
Labels: build, gpu

#1763 TST: Fix `llama-cpp-python` issue in CI
  .github/workflows/python.yaml
  xinference/deploy/docker/cpu.Dockerfile
  xinference/deploy/docker/requirements_cpu.txt
Labels: testing

#1767 BLD: Pin `llama-cpp-python` to `v0.2.77` in Docker for stability
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
Labels: build

#1771 ENH: Add more log modules
  xinference/deploy/utils.py
Labels: enhancement

#1772 BUG: [UI] Fix authentication mode related bugs
  xinference/web/ui/src/App.js
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/Title.js
  xinference/web/ui/src/components/fetchWrapper.js
  xinference/web/ui/src/router/index.js
  xinference/web/ui/src/scenes/cluster_info/index.js
  xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#1724 ENH: Continuous batching supports `vision` model ability
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/core/tests/test_continuous_batching.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/cogvlm2.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/glm4v.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/utils.py
Labels: enhancement

#1680 ENH: Add guard for model launching
  xinference/core/worker.py
Labels: enhancement, gpu

#1785 DOC: Update continuous batching and docker usage
  doc/source/getting_started/using_docker_image.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/continuous_batching.po
  doc/source/user_guide/continuous_batching.rst
Labels: documentation

#1765 FEAT: support MLX engine
  .github/workflows/python.yaml
  doc/source/models/builtin/llm/qwen2-instruct.rst
  setup.cfg
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/mlx/__init__.py
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/tests/__init__.py
  xinference/model/llm/mlx/tests/test_mlx.py
  xinference/model/llm/utils.py
Labels: feature

#1794 BUG: Fix LLM based reranker may raise a TypeError
  xinference/model/rerank/core.py
Labels: bug

#1795 BUG: fix deepseek-vl-chat
  xinference/thirdparty/deepseek_vl/serve/__init__.py
  xinference/thirdparty/deepseek_vl/serve/app_modules/__init__.py
Labels: bug

#1774 FEAT: add gemma-2-it
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#1776 ENH: Update ChatTTS
  .github/workflows/python.yaml
  setup.cfg
  xinference/model/audio/chattts.py
  xinference/model/audio/tests/test_chattts.py
  xinference/thirdparty/ChatTTS/__init__.py
  xinference/thirdparty/ChatTTS/core.py
  xinference/thirdparty/ChatTTS/experimental/__init__.py
  xinference/thirdparty/ChatTTS/experimental/llm.py
  xinference/thirdparty/ChatTTS/infer/__init__.py
  xinference/thirdparty/ChatTTS/infer/api.py
  xinference/thirdparty/ChatTTS/model/__init__.py
  xinference/thirdparty/ChatTTS/model/dvae.py
  xinference/thirdparty/ChatTTS/model/gpt.py
  xinference/thirdparty/ChatTTS/utils/__init__.py
  xinference/thirdparty/ChatTTS/utils/gpu_utils.py
  xinference/thirdparty/ChatTTS/utils/infer_utils.py
  xinference/thirdparty/ChatTTS/utils/io_utils.py
Labels: enhancement

#1810 FIX: [UI] Historical parameter echo bugs.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#1821 DOC: Define a custom Rerank model
  doc/source/locale/ja_JP/LC_MESSAGES/models/custom.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/custom.po
  doc/source/models/custom.rst
Labels: documentation

#1841 FEAT: support choose download hub
  xinference/api/restful_api.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/audio/core.py
  xinference/model/core.py
  xinference/model/embedding/core.py
  xinference/model/image/core.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/rerank/core.py
Labels: feature

#1840 FEAT: [UI] Specify download hub.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1815 DOC: update readme
  README.md
  README_zh_CN.md
Labels: documentation

#1844 REF: Remove `chatglm-cpp` and Fix latest `llama-cpp-python` issue
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_chatglm.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/types.py
Labels: gpu, refactor

#1671 FEAT: Add support for Flexible Model
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/core.py
  xinference/model/flexible/__init__.py
  xinference/model/flexible/core.py
  xinference/model/flexible/launchers/__init__.py
  xinference/model/flexible/launchers/transformers_launcher.py
  xinference/model/flexible/tests/__init__.py
  xinference/model/flexible/tests/test_flexible_models.py
  xinference/model/flexible/utils.py
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#1849 BUG: cache status missing for model id with quantization placeholder
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#1773 ENH: Added the parameter 'worker_ip' to the 'register' model.
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/image/custom.py
Labels: enhancement

#1865 BUG: Fix stream unicode issue for chinese characters when using vllm backend
  xinference/core/model.py
Labels: bug

#1879 FEAT: support sd inpainting models
  doc/source/gen_docs.py
  doc/source/models/builtin/image/stable-diffusion-2-inpainting.rst
  doc/source/models/builtin/image/stable-diffusion-inpainting.rst
  doc/templates/image.rst.jinja
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: feature

#1812 FEAT: Stream ChatTTS
  .github/workflows/python.yaml
  doc/source/getting_started/environments.rst
  doc/source/models/model_abilities/audio.rst
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/constants.py
  xinference/core/model.py
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/chattts.py
  xinference/model/audio/tests/test_chattts.py
Labels: feature

#1874 ENH: added gguf formats for gemma-2-it
  doc/source/models/builtin/llm/chatglm.rst
  doc/source/models/builtin/llm/chatglm2.rst
  doc/source/models/builtin/llm/chatglm3.rst
  doc/source/models/builtin/llm/gemma-2-it.rst
  doc/source/models/builtin/llm/glm4-chat-1m.rst
  doc/source/models/builtin/llm/glm4-chat.rst
  doc/source/models/builtin/llm/index.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#1888 FEAT: support codegeex4
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/codegeex4.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1901 BUG: sglang stream error while stream_option not set
  xinference/model/llm/sglang/core.py
Labels: bug

#1887 FEAT: support internlm2.5-chat & internlm2.5-chat-1m
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/image/index.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internlm2-chat.rst
  doc/source/models/builtin/llm/internlm2.5-chat-1m.rst
  doc/source/models/builtin/llm/internlm2.5-chat.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/tests/test_tensorizer.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1907 BUG: fix inpainting and flexible infer due to inner API change
  doc/source/models/builtin/image/index.rst
  doc/source/models/builtin/image/stable-diffusion-xl-inpainting.rst
  xinference/core/chat_interface.py
  xinference/core/model.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
Labels: bug

#1916 FEAT: support csg-wukong-chat-v0.1
  doc/source/models/builtin/llm/csg-wukong-chat-v0.1.rst
  doc/source/models/builtin/llm/index.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_csghub.json
Labels: feature

#1908 ENH: added MLX for llama-3-instruct, codestral, Yi-1.5-chat, internlm2.5-chat
  doc/source/models/builtin/llm/c4ai-command-r-v01-4bit.rst
  doc/source/models/builtin/llm/c4ai-command-r-v01.rst
  doc/source/models/builtin/llm/codestral-v0.1.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internlm2.5-chat.rst
  doc/source/models/builtin/llm/llama-3-instruct.rst
  doc/source/models/builtin/llm/yi-1.5-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#1934 ENH: add gptq for llama-3-instruct
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#1922 FEAT: [UI]Add configuration for image and audio models.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1936 FEAT: support mistral-nemo-instruct
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/mistral-nemo-instruct.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1932 FEAT: add llama-3.1, llama-3.1-instruct
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/llama-3.1-instruct.rst
  doc/source/models/builtin/llm/llama-3.1.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#1944 FEAT: support mistral-large-instruct
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/mistral-large-instruct.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1935 Feat: support for llama 3.1 for vllm
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/llama-3.1-instruct.rst
  doc/source/user_guide/backends.rst
  setup.cfg
  xinference/model/llm/vllm/core.py
Labels: feature

#1946 DOC: update new models to readme
  README.md
  README_zh_CN.md
Labels: documentation

#1917 FEAT: add rembg flexible model to remove background of image
  doc/source/models/builtin/image/index.rst
  xinference/core/scheduler.py
  xinference/model/flexible/launchers/__init__.py
  xinference/model/flexible/launchers/image_process_launcher.py
  xinference/model/llm/pytorch/cogvlm2.py
Labels: feature

#1947 ENH: Add support of sglang for llama 3 qwen 2
  xinference/model/llm/sglang/core.py
Labels: enhancement

#1966 BUG: Fix GLM chat
  xinference/model/llm/pytorch/chatglm.py
Labels: bug

#1953 REF: enable sglang by default
  doc/source/getting_started/environments.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/environments.po
  xinference/constants.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: refactor

#1954 ENH: add cache_limit_gb option for MLX
  xinference/model/llm/mlx/core.py
Labels: enhancement

#1955 BUG: fix match for transformers from model registered
  xinference/model/llm/pytorch/deepseek_vl.py
  xinference/model/llm/pytorch/falcon.py
  xinference/model/llm/pytorch/llama_2.py
  xinference/model/llm/pytorch/omnilmm.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/vicuna.py
  xinference/model/llm/pytorch/yi_vl.py
Labels: bug

#1974 BUG: Load llama.so failed in docker image
  xinference/deploy/docker/Dockerfile
Labels: bug

#1961 ENH: [benchmark] Add api-key support
  benchmark/benchmark_latency.py
  benchmark/benchmark_long.py
  benchmark/benchmark_rerank.py
  benchmark/benchmark_serving.py
  benchmark/utils.py
Labels: enhancement

#1978 DOC: ascend support
  doc/source/getting_started/installation.rst
  doc/source/getting_started/installation_npu.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation_npu.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
Labels: documentation
