Repository xorbitsai/inference, pull requests merged in 2024-01, with the labels that each got.

#841 DOC: CUDA Version recommendation
  doc/source/getting_started/troubleshooting.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
Labels: documentation, gpu

#843 DOC: new doc cover
  doc/source/conf.py
  doc/source/index.rst
  doc/source/locale/ja_JP/LC_MESSAGES/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  setup.cfg
Labels: documentation

#846 DOC: Add multimodal feature in README
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#847 DOC: Chinese doc for user guide
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/troubleshooting.po
  doc/source/locale/ja_JP/LC_MESSAGES/user_guide/backends.po
  doc/source/locale/ja_JP/LC_MESSAGES/user_guide/spec_decoding.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/client_api.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/examples/AI_Podcast.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/examples/chat.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/faq.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/spec_decoding.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/user_guide.po
  doc/source/user_guide/backends.rst
  doc/source/user_guide/spec_decoding.rst
Labels: documentation

#837 ENH: Offload all response serialization to ModelActor
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/tests/test_client.py
  xinference/core/model.py
  xinference/model/llm/pytorch/tests/test_opt.py
Labels: enhancement

#854 DOC: add notebook for quickstart
  examples/Xinference_Quick_Start.ipynb
Labels: documentation

#856 BUG: Fix typing_extension version problem in notebook
  examples/Xinference_Quick_Start.ipynb
Labels: bug

#851 DOC: Add jupyter notebook quick start tutorial
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#857 FEAT: text2vec
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/embedding/text2vec-base-chinese-paraphrase.rst
  doc/source/models/builtin/embedding/text2vec-base-chinese-sentence.rst
  doc/source/models/builtin/embedding/text2vec-base-chinese.rst
  doc/source/models/builtin/embedding/text2vec-base-multilingual.rst
  doc/source/models/builtin/embedding/text2vec-large-chinese.rst
  xinference/model/embedding/model_spec.json
Labels: feature

#850 BUG: Fix multimodal cmdline
  setup.cfg
  xinference/deploy/cmdline.py
Labels: bug

#855 BLD: Docker image
  .dockerignore
  .github/workflows/docker-cd.yaml
  doc/source/getting_started/index.rst
  doc/source/getting_started/using_docker_image.rst
  xinference/deploy/docker/Dockerfile
Labels: build

#858 BUG: Fix generate of chatglm3
  xinference/core/model.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/utils.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
Labels: bug

#861 ENH: Custom model uses vLLM
  xinference/api/restful_api.py
  xinference/client/tests/test_client.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/deploy/test/test_cmdline.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/vllm/core.py
  xinference/web/ui/src/scenes/register_model/index.js
Labels: enhancement

#865 DOC: docker image translation
  README.md
  README_zh_CN.md
  doc/source/getting_started/using_docker_image.rst
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
Labels: documentation

#863 DOC: register model with `model_family`
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/custom.po
  doc/source/models/custom.rst
Labels: documentation

#859 ENH: Stream use xoscar generator
  .github/workflows/python.yaml
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/tests/test_client.py
  xinference/core/model.py
Labels: enhancement

#864 DOC: Add OpenAI Client API doc
  doc/source/user_guide/client_api.rst
  xinference/api/restful_api.py
Labels: documentation

#869 FEAT: qwen 1.8b gptq
  xinference/core/model.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#874 BUG: Fix image model b64_json output
  doc/source/models/builtin/llm/qwen-chat.rst
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
  xinference/model/llm/llm_family.json
Labels: bug

#878 DOC: add docker instructions
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#877 REF: Add `model_hub` property in `EmbeddingModelSpec`
  doc/source/models/builtin/embedding/text2vec-base-chinese-paraphrase.rst
  doc/source/models/builtin/embedding/text2vec-base-chinese.rst
  doc/source/models/builtin/embedding/text2vec-large-chinese.rst
  xinference/model/embedding/core.py
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/llm/llm_family.py
Labels: refactor

#868 FEAT: docker compose support
  docker-compose.yml
Labels: feature

#881 ENH: make the size param of *_to_image more compatible
  xinference/model/image/stable_diffusion/core.py
Labels: enhancement

#883 BUG: fix libcuda.so.1: cannot open shared object file
  xinference/deploy/docker/Dockerfile
Labels: bug, gpu

#885 BUG: Fix auto recover kwargs
  xinference/core/worker.py
Labels: bug

#876 FEAT: Yi chat gptq
  doc/source/models/builtin/llm/yi-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#886 BLD: Update package-lock.json
  xinference/web/ui/package-lock.json
Labels: build

#889 BUG: Fix prompt template of chatglm3-32k
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#890 BUG: invalid volumn in docker compose yml
  docker-compose.yml
  xinference/deploy/docker/docker-compose.yml
Labels: bug

#879 ENH: Launch model asynchronously
  xinference/api/restful_api.py
  xinference/core/status_guard.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
Labels: enhancement

#901 DOC: Update the documentation about use of docker
  doc/source/getting_started/using_docker_image.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
  xinference/deploy/docker/docker-compose.yml
Labels: documentation

#903 BUG: Revert #883
  xinference/deploy/docker/Dockerfile
Labels: bug

#898 BUG: Fix chatglm backend
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/utils.py
Labels: bug

#899 BUG: Fix tool calls on custom model
  xinference/core/supervisor.py
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#902 ENH: qwen vl modelscope
  xinference/model/multimodal/__init__.py
  xinference/model/multimodal/model_spec_modelscope.json
Labels: enhancement

#904 ENH: Add "tools" in model ability
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/fields.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#907 BUG: Fix is_valid_model_name
  xinference/model/llm/tests/test_utils.py
  xinference/model/utils.py
Labels: bug

#893 FEAT: Auto recover limit
  xinference/client/tests/test_client.py
  xinference/core/worker.py
Labels: feature

#910 ENH: Add quantization support for qwen chat
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: enhancement

#911 DOC:ADD FAQ IN troubleshooting.rst
  doc/source/getting_started/troubleshooting.rst
Labels: documentation

#906 FEAT: Prometheus metrics exporter
  .github/workflows/python.yaml
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/tests/test_client.py
  xinference/conftest.py
  xinference/core/metrics.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/tests/test_metrics.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/local.py
  xinference/deploy/worker.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
Labels: feature

#913 FEAT: Add internlm2-chat support
  doc/source/models/builtin/llm/chatglm3.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internlm2-chat.rst
  doc/source/models/builtin/llm/qwen-chat.rst
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/utils.py
Labels: feature

#914 DOC: Update readme
  README.md
  README_zh_CN.md
Labels: documentation

#915 DOC: Display contributors in readme
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#896 ENH: Launch model by `version`
  xinference/api/restful_api.py
  xinference/core/cache_tracker.py
  xinference/core/status_guard.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/model/core.py
  xinference/model/embedding/__init__.py
  xinference/model/embedding/core.py
  xinference/model/embedding/utils.py
  xinference/model/image/__init__.py
  xinference/model/image/core.py
  xinference/model/image/utils.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/utils.py
  xinference/model/multimodal/core.py
  xinference/model/rerank/__init__.py
  xinference/model/rerank/core.py
  xinference/model/rerank/utils.py
  xinference/model/utils.py
Labels: enhancement

#916 FEAT: Support events
  xinference/api/restful_api.py
  xinference/core/event.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
Labels: feature, gpu

#917 ENH: Move multimodal to LLM
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen-vl-chat.rst
  examples/chat_vl.ipynb
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/chat_interface.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/core.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/tests/test_multimodal.py
  xinference/model/multimodal/__init__.py
  xinference/model/multimodal/core.py
  xinference/model/multimodal/model_spec.json
  xinference/model/multimodal/model_spec_modelscope.json
  xinference/model/multimodal/tests/__init__.py
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/launchMultimodal.js
  xinference/web/ui/src/scenes/launch_model/multimodalCard.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#925 REF: Move auth code to service for better scalability
  xinference/api/oauth2/auth_service.py
  xinference/api/oauth2/common.py
  xinference/api/oauth2/core.py
  xinference/api/restful_api.py
Labels: refactor

#924 BLD: Resolve conflicts during installation
  setup.cfg
Labels: build

#923 DOC: Merge multimodal to LLM
  doc/source/index.rst
Labels: documentation

#929 FEAT: Support audio model
  .github/workflows/python.yaml
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/client/tests/test_client_with_auth.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/audio/__init__.py
  xinference/model/audio/core.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/__init__.py
  xinference/model/audio/tests/common_voice_zh-CN_38026095.mp3
  xinference/model/audio/tests/test_whisper.py
  xinference/model/audio/utils.py
  xinference/model/audio/whisper.py
  xinference/model/core.py
Labels: feature

#927 ENH: Support `use_fp16` for rerank model
  xinference/model/rerank/core.py
Labels: enhancement

#933 FEAT: Support orion series models
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/orion-chat-rag.rst
  doc/source/models/builtin/llm/orion-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#920 ENH: record instance count and version count when detailed listing model registrations
  xinference/core/cache_tracker.py
  xinference/core/status_guard.py
  xinference/core/supervisor.py
Labels: enhancement

#936 Feat: Support Mixtral-8x7B-Instruct-v0.1-AWQ
  doc/source/models/builtin/llm/mixtral-instruct-v0.1.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/register_model/index.js
Labels: feature

#937 DOC: Audio doc
  doc/source/index.rst
  doc/source/reference/index.rst
  doc/source/user_guide/client_api.rst
  doc/source/user_guide/model_abilities/audio.rst
  doc/source/user_guide/model_abilities/index.rst
  examples/audio_to_text.ipynb
  xinference/client/handlers.py
Labels: documentation

#938 DOC: Update readme
  README.md
  README_zh_CN.md
Labels: documentation

#941 ENH: Record gpu mem status in workers
  .github/workflows/python.yaml
  setup.cfg
  xinference/api/restful_api.py
  xinference/core/resource.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/utils.py
Labels: enhancement, gpu

#944 FEAT: add whisper.small and belle distilwhisper model, fix parameter in rerank
  xinference/model/audio/model_spec.json
  xinference/model/rerank/core.py
Labels: feature

#947 DOC: Add image model doc
  doc/source/gen_docs.py
  doc/source/models/builtin/image/index.rst
  doc/source/models/builtin/image/sd-turbo.rst
  doc/source/models/builtin/image/sdxl-turbo.rst
  doc/source/models/builtin/image/stable-diffusion-v1.5.rst
  doc/source/models/builtin/image/stable-diffusion-xl-base-1.0.rst
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internlm2-chat.rst
  doc/source/models/builtin/llm/mixtral-instruct-v0.1.rst
  doc/source/models/builtin/llm/orion-chat-rag.rst
  doc/source/models/builtin/llm/orion-chat.rst
  doc/source/models/builtin/llm/qwen-vl-chat.rst
  doc/templates/image.rst.jinja
  doc/templates/image_index.rst.jinja
Labels: documentation

#948 FEAT: Support jina-embeddings-v2-base-zh
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/embedding/jina-embeddings-v2-base-zh.rst
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
Labels: feature

#949 BUG: Fix roles in chat UI
  xinference/core/chat_interface.py
  xinference/model/llm/core.py
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#946 FEAT: Support Yi VL
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/yi-vl-chat.rst
  setup.cfg
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/yi_vl.py
  xinference/model/llm/tests/test_multimodal.py
  xinference/thirdparty/__init__.py
  xinference/thirdparty/llava/__init__.py
  xinference/thirdparty/llava/conversation.py
  xinference/thirdparty/llava/mm_utils.py
  xinference/thirdparty/llava/model/__init__.py
  xinference/thirdparty/llava/model/clip_encoder/__init__.py
  xinference/thirdparty/llava/model/clip_encoder/builder.py
  xinference/thirdparty/llava/model/clip_encoder/clip_encoder.py
  xinference/thirdparty/llava/model/constants.py
  xinference/thirdparty/llava/model/llava_arch.py
  xinference/thirdparty/llava/model/llava_llama.py
  xinference/thirdparty/llava/model/multimodal_projector/__init__.py
  xinference/thirdparty/llava/model/multimodal_projector/builder.py
Labels: feature
