Repository xorbitsai/inference, pull requests merged in 2024-11, with the labels that each got.

#2503 BLD: Remove Python 3.8 & Support Python 3.12
  .github/workflows/docker-cd.yaml
  .github/workflows/python.yaml
  pyproject.toml
  setup.cfg
  xinference/core/tests/test_continuous_batching.py
Labels: build

#2516 REF: Remove replica total count in internal `replica_model_uid`
  .github/workflows/python.yaml
  setup.cfg
  xinference/core/supervisor.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/core.py
Labels: refactor

#1891 ENH: Display model name in process
  setup.cfg
  xinference/constants.py
  xinference/core/model.py
  xinference/core/tests/test_model.py
  xinference/core/worker.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: enhancement, gpu

#2520 BUG: Compat with ChatTTS 0.2.1
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/test_chattts.py
Labels: bug

#2530 BUG: transformers logs missing
  xinference/conftest.py
  xinference/deploy/cmdline.py
  xinference/deploy/utils.py
Labels: bug

#2533 DOC: Add paper citation
  README.md
  README_ja_JP.md
  README_zh_CN.md
Labels: documentation

#2528 FEAT: Basic cancel support for image model
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/constants.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/utils.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: feature

#2543 FEAT: Add qwen2.5-coder 0.5B 1.5B 3B 14B 32B
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#2534 FEAT: support kvcache in multi-round chat for MLX
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/tests/test_mlx.py
Labels: feature

#2547 BUG: fix variant error for image model
  xinference/model/image/stable_diffusion/core.py
Labels: bug

#2509 ENH: add normalize to rerank model
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/model/rerank/core.py
  xinference/model/rerank/tests/test_rerank.py
Labels: enhancement

#2542 ENH: Support fish speech reference audio
  doc/source/models/model_abilities/audio.rst
  xinference/client/restful/restful_client.py
  xinference/model/audio/fish_speech.py
  xinference/model/audio/tests/test_fish_speech.py
Labels: enhancement

#2562 FEAT: Fish speech stream
  xinference/model/audio/fish_speech.py
  xinference/model/audio/tests/test_fish_speech.py
Labels: feature

#2540 FEAT: support sparse vector for bge-m3
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/model/embedding/core.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/types.py
Labels: feature

#2571 BUG: request_limits does not work with streaming interfaces
  xinference/api/restful_api.py
  xinference/core/model.py
Labels: bug

#2587 DOC: update builtin models
  .gitignore
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/whisper-base-mlx.rst
  doc/source/models/builtin/audio/whisper-base.en-mlx.rst
  doc/source/models/builtin/audio/whisper-large-v3-mlx.rst
  doc/source/models/builtin/audio/whisper-large-v3-turbo-mlx.rst
  doc/source/models/builtin/audio/whisper-medium-mlx.rst
  doc/source/models/builtin/audio/whisper-medium.en-mlx.rst
  doc/source/models/builtin/audio/whisper-small-mlx.rst
  doc/source/models/builtin/audio/whisper-small.en-mlx.rst
  doc/source/models/builtin/audio/whisper-tiny-mlx.rst
  doc/source/models/builtin/audio/whisper-tiny.en-mlx.rst
  doc/source/models/builtin/embedding/gte-qwen2.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/llama-3.1-instruct.rst
  doc/source/models/builtin/llm/llama-3.2-vision-instruct.rst
  doc/source/models/builtin/llm/llama-3.2-vision.rst
  doc/source/models/builtin/llm/qwen2-vl-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-coder-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-coder.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#2590 BUG: Fix Codestral v0.1 URI for Pytorch Format
  doc/source/models/builtin/llm/codestral-v0.1.rst
  xinference/model/llm/llm_family.json
Labels: bug

#2391 feat: support guided decoding for vllm async engine
  xinference/_compat.py
  xinference/api/restful_api.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2602 FEAT: support QwQ-32B-Preview
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwq-32b-preview.rst
  doc/source/user_guide/backends.rst
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2600 BUG: Correct the input bytes data by langchain_openai #2589
  xinference/model/embedding/core.py
Labels: bug

#2582 FEAT: support glm-edge-chat model
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/glm_edge_v.py
  xinference/model/llm/utils.py
Labels: feature

#2613 BUG: llama-cpp-python 0.3.2 build issue in cpu Docker
  xinference/deploy/docker/cpu.Dockerfile
Labels: bug
