Repository xorbitsai/inference, pull requests merged in 2024-02, with the labels that each got.

#957 BUG: Fix heartbeat
  setup.cfg
  xinference/constants.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
Labels: bug

#959 FEAT: Support more embedding and rerank models
  .github/workflows/python.yaml
  doc/source/models/builtin/embedding/bce-embedding-base_v1.rst
  doc/source/models/builtin/embedding/bge-m3.rst
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/rerank/bce-reranker-base_v1.rst
  doc/source/models/builtin/rerank/index.rst
  setup.cfg
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/rerank/model_spec.json
  xinference/model/rerank/model_spec_modelscope.json
Labels: feature

#960 ENH: Allow chat max_tokens is None
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_types.py
  xinference/model/llm/pytorch/utils.py
  xinference/types.py
Labels: enhancement

#961 DOC: Reorge model related docs
  doc/source/models/builtin/index.rst
  doc/source/models/builtin/rerank/index.rst
  doc/source/models/index.rst
  doc/source/models/model_abilities/audio.rst
  doc/source/models/model_abilities/chat.rst
  doc/source/models/model_abilities/embed.rst
  doc/source/models/model_abilities/image.rst
  doc/source/models/model_abilities/index.rst
  doc/source/models/model_abilities/rerank.rst
  doc/source/models/model_abilities/tools.rst
  doc/source/models/model_abilities/vision.rst
Labels: documentation

#962 ENH: `chatglm` `ggml` format supports `system_prompt`
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/worker.py
  xinference/model/llm/ggml/chatglm.py
  xinference/model/llm/ggml/tests/test_chatglm.py
  xinference/model/llm/pytorch/yi_vl.py
Labels: enhancement

#970 BUG: Remove flash-attn dependency
  setup.cfg
Labels: bug

#967 DOC: Auto gen metrics doc
  doc/source/gen_docs.py
  doc/source/models/builtin/embedding/bce-embedding-base_v1.rst
  doc/source/models/builtin/embedding/bge-m3.rst
  doc/source/models/builtin/rerank/bce-reranker-base_v1.rst
  doc/source/user_guide/index.rst
  doc/source/user_guide/metrics.rst
  doc/templates/metrics.jinja
  setup.cfg
Labels: documentation

#969 DOC: Update README.md
  README.md
  README_zh_CN.md
Labels: documentation

#978 BUG: Fix custom model tool calls
  doc/source/user_guide/index.rst
  doc/source/user_guide/metrics.rst
  doc/templates/metrics.jinja
  doc/templates/rerank_index.rst.jinja
  xinference/api/restful_api.py
Labels: bug

#979 ENH: [UI] Fix too long LLM model name
  xinference/web/ui/src/components/titleTypography.js
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
Labels: enhancement

#977 BUG: Fix chat template
  xinference/core/chat_interface.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
Labels: bug

#981 ENH: Add gguf models of llama-2-chat
  xinference/model/llm/llm_family.json
Labels: enhancement

#990 [DOC] Polish troubleshooting page
  doc/source/getting_started/troubleshooting.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
Labels: documentation

#983 REF: Supports `pydantic` v2
  setup.cfg
  xinference/_compat.py
  xinference/api/oauth2/auth_service.py
  xinference/api/oauth2/types.py
  xinference/api/restful_api.py
  xinference/core/status_guard.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_types.py
  xinference/core/utils.py
  xinference/fields.py
  xinference/model/audio/core.py
  xinference/model/embedding/core.py
  xinference/model/image/core.py
  xinference/model/llm/llm_family.py
  xinference/model/rerank/core.py
  xinference/types.py
Labels: refactor

#992 BUG: Fix load yi vl model to multiple cards
  xinference/model/llm/pytorch/yi_vl.py
Labels: bug

#987 BUG: client compatible with old version of xinference
  xinference/client/restful/restful_client.py
Labels: bug

#985 FEAT: Implemented web UI for launching the text2image model.
  xinference/web/ui/src/scenes/launch_model/imageCard.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchImage.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#980 ENH: Download stable diffusion model from modelscope
  xinference/model/core.py
  xinference/model/embedding/core.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/image/__init__.py
  xinference/model/image/core.py
  xinference/model/image/model_spec_modelscope.json
  xinference/model/rerank/core.py
  xinference/model/rerank/tests/test_rerank.py
  xinference/model/utils.py
Labels: enhancement

#994 FEAT: Support qwen-1.5 series
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/llama-2-chat.rst
  doc/source/models/builtin/llm/qwen1.5-chat.rst
  xinference/api/restful_api.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/utils.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1000 DOC: Polish model operation command doc
  doc/source/locale/zh_CN/LC_MESSAGES/models/index.po
  doc/source/models/index.rst
Labels: documentation

#1008 BUG: fix chat completion error when indexing body.messages
  xinference/api/restful_api.py
Labels: bug

#1013 BUG: Fix cache sd 1.5 error
  xinference/model/image/core.py
Labels: bug

#968 FEAT: Refactor device related code and add initial Intel GPU support
  setup.cfg
  xinference/__init__.py
  xinference/api/restful_api.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/worker.py
  xinference/device_utils.py
  xinference/model/audio/whisper.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/llm/pytorch/compression.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/spec_decoding_utils.py
  xinference/model/llm/pytorch/spec_model.py
  xinference/model/llm/pytorch/utils.py
  xinference/model/llm/pytorch/yi_vl.py
  xinference/model/utils.py
  xinference/thirdparty/llava/mm_utils.py
Labels: feature, gpu

#1011 ENH: [UI] Supports `replica` when launching LLM models
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement

#1012 DOC: Fix note on secret_key generation and algorithm selection for OAuth2
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/auth_system.po
  doc/source/user_guide/auth_system.rst
Labels: documentation

#1026 BUG: fix typo in modelscope llama-2-13b-chat-GGUF
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#1015 ENH: [UI] Show cluster resource information
  xinference/api/restful_api.py
  xinference/core/resource.py
  xinference/core/supervisor.py
  xinference/deploy/docker/Dockerfile
  xinference/web/ui/package-lock.json
  xinference/web/ui/package.json
  xinference/web/ui/src/App.js
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/tableTitle.js
  xinference/web/ui/src/components/utils.js
  xinference/web/ui/src/scenes/cluster_info/index.js
  xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
  xinference/web/ui/src/scenes/cluster_info/style.js
Labels: enhancement

#1027 BUG: Fix missing qwen 1.5 7b gguf
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#1024 FEAT: Support gemma series model
  doc/source/models/builtin/llm/gemma-it.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/llama-2-chat.rst
  doc/source/models/builtin/llm/qwen1.5-chat.rst
  xinference/deploy/docker/Dockerfile
  xinference/model/llm/llm_family.json
  xinference/model/llm/utils.py
Labels: feature

#1035 ENH: Support downloading gemma from modelscope
  setup.cfg
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#1045 DOC: Update readme
  README.md
  README_zh_CN.md
Labels: documentation

#1054 DOC: Fix readme
  README_zh_CN.md
Labels: documentation

#1055 DOC: Fix wechat links
  README_zh_CN.md
  doc/source/conf.py
  doc/source/index.rst
Labels: documentation

#1056 ENH: Restful client supports multiple system prompts for chat
  xinference/client/restful/restful_client.py
Labels: enhancement

#1057 ENH: supports disabling worker reporting status
  .github/workflows/python.yaml
  xinference/conftest.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
Labels: enhancement
