Repository xorbitsai/inference, pull requests merged in 2024-03, with the labels that each got.

#1066 BUG: Fix some models that cannot download from `modelscope`
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#1048 ENH: Extra params for `xinference launch` command line
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
  xinference/deploy/cmdline.py
  xinference/deploy/utils.py
Labels: enhancement

#1068 FEAT: Docker for cpu only
  .github/workflows/docker-cd.yaml
  xinference/deploy/docker/cpu.Dockerfile
Labels: feature

#1061 BUG: Fix early truncation due to `max_token` being default to `16` instead of `1024`
  xinference/api/restful_api.py
  xinference/types.py
Labels: bug

#1077 DOC: Extra parameters for launching models
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
Labels: documentation

#1076 FEAT: Add a command / SDK interface to query which models are able to…
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/deploy/cmdline.py
Labels: feature

#1070 ENH: Supports `n_gpu_layers` parameter for `llama-cpp-python`
  xinference/model/llm/ggml/llamacpp.py
Labels: enhancement, gpu

#1075 FEAT: Support download and merge multiple parts of gguf files
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_llm_family.py
Labels: feature

#1073 ENH: Add a dropdown to the web UI to support adjusting GPU offload layers for llama.cpp loader
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement, gpu

#1093 ENH: [UI] Show `replica` on running model page
  xinference/core/supervisor.py
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#1062 ENH: Add "[DONE]" to the end of stream generation for better openai SDK compatibility
  xinference/api/restful_api.py
  xinference/client/common.py
  xinference/client/tests/test_client.py
Labels: enhancement

#1092 DOC: contribution doc
  doc/source/conf.py
  doc/source/development/contributing_codebase.rst
  doc/source/development/contributing_environment.rst
  doc/source/development/index.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_codebase.po
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
  doc/source/locale/zh_CN/LC_MESSAGES/development/index.po
Labels: documentation

#1080 FEAT: Supports LoRA for LLM and image models
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/core.py
  xinference/model/image/core.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/falcon.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/pytorch/llama_2.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/vicuna.py
  xinference/model/llm/pytorch/yi_vl.py
Labels: feature, gpu

#1096 ENH: [UI] Support setting `CPU` when selecting n_gpu
  xinference/device_utils.py
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement, gpu

#1106 ENH: update cmd help info
  xinference/deploy/cmdline.py
Labels: enhancement

#1121 TST: Remove testing LLM model creating embedding
  xinference/core/tests/test_restful_api.py
Labels: testing

#1118 DOC: fix CPU docker image & refine
  README.md
  README_zh_CN.md
  doc/source/getting_started/environments.rst
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/environments.po
Labels: documentation

#1117 FEAT: Add Yi-9B
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#1130 BUG: fix the useless fstring.
  xinference/core/supervisor.py
Labels: bug

#1111 BUG: Fixing the issue of model list loading failure caused by a large number of invalid requests on the model list page.
  xinference/web/ui/src/scenes/launch_model/launchEmbedding.js
  xinference/web/ui/src/scenes/launch_model/launchImage.js
  xinference/web/ui/src/scenes/launch_model/launchRerank.js
Labels: bug

#1134 ENH: Remove quantization limits for Apple METAL device when running model via `llama-cpp-python`
  xinference/model/llm/ggml/llamacpp.py
Labels: enhancement

#1135 BUG: Fix cache status for embedding, rerank and image models on the web UI
  xinference/model/image/__init__.py
  xinference/model/image/core.py
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/imageCard.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
Labels: bug

#1127 ENH: Make GET /v1/models compatible with OpenAI API.
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/tests/test_restful_api.py
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#1140 BUG: Fix missing information for `xinference registrations` and `xinference list` command
  xinference/deploy/cmdline.py
Labels: bug

#1145 ENH: support vllm>=0.3.1
  setup.cfg
  xinference/client/tests/test_client.py
  xinference/conftest.py
  xinference/core/tests/test_metrics.py
  xinference/deploy/docker/cpu.Dockerfile
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
  xinference/model/llm/pytorch/tests/test_opt.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#1144 BUG: Fix cannot continue to chat after canceling the streaming chat via `ctrl+c`
  xinference/api/restful_api.py
Labels: bug

#1150 BUG: remove `best_of` from benchmark
  benchmark/benchmark_latency.py
  benchmark/benchmark_serving.py
  benchmark/utils.py
Labels: bug

#1098 BUG: fix _eval_qwen_chat_arguments parsing problem
  xinference/model/llm/utils.py
Labels: bug

#1155 ENH: vLLM latest models support
  doc/source/user_guide/backends.rst
  xinference/model/llm/vllm/core.py
Labels: enhancement

#1159 BUG: Fix OpenAI compatibility issue during chat
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/utils.py
Labels: bug

#1166 FEAT: Support CodeShell model
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
Labels: feature

#1161 FEAT: Supports `sglang` backend
  setup.cfg
  xinference/constants.py
  xinference/model/llm/__init__.py
  xinference/model/llm/sglang/__init__.py
  xinference/model/llm/sglang/core.py
Labels: feature

#1178 DOC: internal design
  doc/source/_static/actor.svg
  doc/source/development/index.rst
  doc/source/development/xinference_internals.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/xinference_internals.po
Labels: documentation

#1182 BUG: Fix the incorrect model interface address caused a 307 redirect to HTTP, blocking the request and preventing the display of the model list.
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#1176 Doc: update readme and models doc
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/codeshell-chat.rst
  doc/source/models/builtin/llm/codeshell.rst
  doc/source/models/builtin/llm/index.rst
Labels: documentation

#1190 BLD: add autoawq in setup
  setup.cfg
Labels: build

#1102 FEAT: launch UI of audio model.
  xinference/web/ui/src/scenes/launch_model/audioCard.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchAudio.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#1171 FEAT: Supports `OmniLMM` chat model
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/omnilmm.py
  xinference/thirdparty/omnilmm/LICENSE
  xinference/thirdparty/omnilmm/__init__.py
  xinference/thirdparty/omnilmm/chat.py
  xinference/thirdparty/omnilmm/constants.py
  xinference/thirdparty/omnilmm/conversation.py
  xinference/thirdparty/omnilmm/model/__init__.py
  xinference/thirdparty/omnilmm/model/omnilmm.py
  xinference/thirdparty/omnilmm/model/resampler.py
  xinference/thirdparty/omnilmm/model/utils.py
  xinference/thirdparty/omnilmm/train/train_utils.py
  xinference/thirdparty/omnilmm/utils.py
Labels: feature

#1203 BUG: fix doc fail introduced by #1171 & update readme
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/omnilmm.rst
  setup.cfg
  xinference/thirdparty/omnilmm/train/__init__.py
Labels: bug

#1195 FEAT: force to specify worker ip and gpu idx when launching models
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/supervisor.py
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
Labels: feature, gpu

#1201 BUG: Increase validator types for thie 'input' parameter of embeddings to match OpenAI API
  xinference/api/restful_api.py
Labels: bug

#1168 FEAT: OAuth system supports api-key
  doc/source/development/contributing_environment.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
  xinference/api/oauth2/auth_service.py
  xinference/api/oauth2/types.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client_with_auth.py
  xinference/conftest.py
  xinference/deploy/cmdline.py
Labels: feature

#1210 DOC: Doc for oauth system with api-key
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/auth_system.po
  doc/source/user_guide/auth_system.rst
Labels: documentation

#1175 FEAT: Support deepseek vl
  .github/workflows/python.yaml
  doc/source/models/builtin/llm/deepseek-vl-chat.rst
  doc/source/models/builtin/llm/index.rst
  setup.cfg
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/deepseek_vl.py
  xinference/model/llm/tests/test_multimodal.py
  xinference/model/llm/vllm/core.py
  xinference/thirdparty/deepseek_vl/__init__.py
  xinference/thirdparty/deepseek_vl/models/__init__.py
  xinference/thirdparty/deepseek_vl/models/clip_encoder.py
  xinference/thirdparty/deepseek_vl/models/image_processing_vlm.py
  xinference/thirdparty/deepseek_vl/models/modeling_vlm.py
  xinference/thirdparty/deepseek_vl/models/processing_vlm.py
  xinference/thirdparty/deepseek_vl/models/projector.py
  xinference/thirdparty/deepseek_vl/models/sam.py
  xinference/thirdparty/deepseek_vl/models/siglip_vit.py
  xinference/thirdparty/deepseek_vl/serve/app_deepseek.py
  xinference/thirdparty/deepseek_vl/serve/app_modules/gradio_utils.py
  xinference/thirdparty/deepseek_vl/serve/app_modules/overwrites.py
  xinference/thirdparty/deepseek_vl/serve/app_modules/presets.py
  xinference/thirdparty/deepseek_vl/serve/app_modules/utils.py
  xinference/thirdparty/deepseek_vl/serve/assets/Kelpy-Codos.js
  xinference/thirdparty/deepseek_vl/serve/assets/avatar.png
  xinference/thirdparty/deepseek_vl/serve/assets/custom.css
  xinference/thirdparty/deepseek_vl/serve/assets/custom.js
  xinference/thirdparty/deepseek_vl/serve/assets/favicon.ico
  xinference/thirdparty/deepseek_vl/serve/examples/app.png
  xinference/thirdparty/deepseek_vl/serve/examples/chart.png
  xinference/thirdparty/deepseek_vl/serve/examples/mirror.png
  xinference/thirdparty/deepseek_vl/serve/examples/pipeline.png
  xinference/thirdparty/deepseek_vl/serve/examples/puzzle.png
  xinference/thirdparty/deepseek_vl/serve/examples/rap.jpeg
  xinference/thirdparty/deepseek_vl/serve/inference.py
  xinference/thirdparty/deepseek_vl/utils/__init__.py
  xinference/thirdparty/deepseek_vl/utils/conversation.py
  xinference/thirdparty/deepseek_vl/utils/io.py
Labels: feature, gpu

#1204 FEAT: support some builtin new models
  .pre-commit-config.yaml
  doc/source/models/builtin/llm/aquila2-chat-16k.rst
  doc/source/models/builtin/llm/aquila2-chat.rst
  doc/source/models/builtin/llm/aquila2.rst
  doc/source/models/builtin/llm/chatglm3-128k.rst
  doc/source/models/builtin/llm/gorilla-openfunctions-v2.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/minicpm-2b-dpo-bf16.rst
  doc/source/models/builtin/llm/minicpm-2b-dpo-fp16.rst
  doc/source/models/builtin/llm/minicpm-2b-dpo-fp32.rst
  doc/source/models/builtin/llm/minicpm-2b-sft-bf16.rst
  doc/source/models/builtin/llm/minicpm-2b-sft-fp32.rst
  doc/source/models/builtin/llm/platypus2-70b-instruct.rst
  setup.cfg
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
Labels: feature

#1213 BUG: Fix docker cpu build
  xinference/deploy/docker/cpu.Dockerfile
Labels: bug

#1217 BUG: Fix cannot start xinference in docker due to `cv2`
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
Labels: bug
