Repository xorbitsai/inference, pull requests merged in 2024-12, with the labels that each got.

#2603 BUG: Cleanup Isolation tasks
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/isolation.py
Labels: bug

#2632 DOC: update new models
  .github/workflows/python.yaml
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/glm-edge-chat.rst
  doc/source/models/builtin/llm/glm-edge-v.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/model_abilities/tools.rst
  doc/source/models/model_abilities/vision.rst
Labels: documentation

#2623 ENH: Optimize error message when user parameters are passed incorrectly
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
Labels: enhancement

#2626 FEAT: Support F5 TTS
  .github/workflows/python.yaml
  setup.cfg
  setup.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/core.py
  xinference/model/audio/f5tts.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/tests/test_f5tts.py
  xinference/thirdparty/f5_tts/__init__.py
  xinference/thirdparty/f5_tts/api.py
  xinference/thirdparty/f5_tts/configs/E2TTS_Base_train.yaml
  xinference/thirdparty/f5_tts/configs/E2TTS_Small_train.yaml
  xinference/thirdparty/f5_tts/configs/F5TTS_Base_train.yaml
  xinference/thirdparty/f5_tts/configs/F5TTS_Small_train.yaml
  xinference/thirdparty/f5_tts/eval/README.md
  xinference/thirdparty/f5_tts/eval/ecapa_tdnn.py
  xinference/thirdparty/f5_tts/eval/eval_infer_batch.py
  xinference/thirdparty/f5_tts/eval/eval_infer_batch.sh
  xinference/thirdparty/f5_tts/eval/eval_librispeech_test_clean.py
  xinference/thirdparty/f5_tts/eval/eval_seedtts_testset.py
  xinference/thirdparty/f5_tts/eval/utils_eval.py
  xinference/thirdparty/f5_tts/infer/README.md
  xinference/thirdparty/f5_tts/infer/SHARED.md
  xinference/thirdparty/f5_tts/infer/examples/basic/basic.toml
  xinference/thirdparty/f5_tts/infer/examples/basic/basic_ref_en.wav
  xinference/thirdparty/f5_tts/infer/examples/basic/basic_ref_zh.wav
  xinference/thirdparty/f5_tts/infer/examples/multi/country.flac
  xinference/thirdparty/f5_tts/infer/examples/multi/main.flac
  xinference/thirdparty/f5_tts/infer/examples/multi/story.toml
  xinference/thirdparty/f5_tts/infer/examples/multi/story.txt
  xinference/thirdparty/f5_tts/infer/examples/multi/town.flac
  xinference/thirdparty/f5_tts/infer/examples/vocab.txt
  xinference/thirdparty/f5_tts/infer/infer_cli.py
  xinference/thirdparty/f5_tts/infer/infer_gradio.py
  xinference/thirdparty/f5_tts/infer/speech_edit.py
  xinference/thirdparty/f5_tts/infer/utils_infer.py
  xinference/thirdparty/f5_tts/model/__init__.py
  xinference/thirdparty/f5_tts/model/backbones/README.md
  xinference/thirdparty/f5_tts/model/backbones/dit.py
  xinference/thirdparty/f5_tts/model/backbones/mmdit.py
  xinference/thirdparty/f5_tts/model/backbones/unett.py
  xinference/thirdparty/f5_tts/model/cfm.py
  xinference/thirdparty/f5_tts/model/dataset.py
  xinference/thirdparty/f5_tts/model/modules.py
  xinference/thirdparty/f5_tts/model/trainer.py
  xinference/thirdparty/f5_tts/model/utils.py
  xinference/thirdparty/f5_tts/scripts/count_max_epoch.py
  xinference/thirdparty/f5_tts/scripts/count_params_gflops.py
  xinference/thirdparty/f5_tts/socket_server.py
  xinference/thirdparty/f5_tts/train/README.md
  xinference/thirdparty/f5_tts/train/datasets/prepare_csv_wavs.py
  xinference/thirdparty/f5_tts/train/datasets/prepare_emilia.py
  xinference/thirdparty/f5_tts/train/datasets/prepare_libritts.py
  xinference/thirdparty/f5_tts/train/datasets/prepare_ljspeech.py
  xinference/thirdparty/f5_tts/train/datasets/prepare_wenetspeech4tts.py
  xinference/thirdparty/f5_tts/train/finetune_cli.py
  xinference/thirdparty/f5_tts/train/finetune_gradio.py
  xinference/thirdparty/f5_tts/train/train.py
Labels: feature

#2647 BUG: fix qwq gguf download hub for modelscope
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#2649 BUG: fix ImportError when optional dependency FlagEmbedding is not installed
  xinference/model/embedding/core.py
Labels: bug

#2641 FIX: fix launching bge-m3 with hybrid mode
  .github/workflows/python.yaml
  xinference/model/embedding/core.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/embedding/tests/test_integrated_embedding.py
Labels: bug

#2655 ENH: bypass the sampling parameter skip_special_tokens to vLLM backend
  xinference/api/restful_api.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#2654 DOC: add doc about offline usage for SenseVoiceSmall
  .github/workflows/python.yaml
  README.md
  README_zh_CN.md
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/audio.po
  doc/source/models/builtin/audio/f5-tts.rst
  doc/source/models/builtin/audio/index.rst
  doc/source/models/model_abilities/audio.rst
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: documentation

#2657 FEAT: [UI] Add a hint for model running.
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#2658 ENH: unify prompt_text as cosyvoice for fish speech
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/audio.po
  doc/source/models/model_abilities/audio.rst
  xinference/model/audio/fish_speech.py
Labels: enhancement

#2638 FEAT: support VL models for MLX
  .github/workflows/python.yaml
  setup.cfg
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/tests/fish.png
  xinference/model/llm/mlx/tests/test_mlx.py
Labels: feature

#2637 FEAT: Add support for CLIP model
  .github/workflows/python.yaml
  xinference/api/restful_api.py
  xinference/model/embedding/core.py
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/embedding/tests/test_integrated_embedding.py
Labels: feature

#2663 BUG: `stop` parameter leads to failure with `transformers` backend
  .github/workflows/python.yaml
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/transformers/utils.py
Labels: bug

#2660 ENH: Update glm4 chat model to new weights
  setup.cfg
  xinference/core/model.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/utils.py
Labels: enhancement

#2667 BUG: fix FishSpeech Negative code found
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: bug

#2668 ENH: upgrade sglang in Docker
  xinference/deploy/docker/requirements.txt
Labels: enhancement

#2671 FEAT: support F5-TTS-MLX
  .github/workflows/python.yaml
  setup.cfg
  xinference/model/audio/core.py
  xinference/model/audio/f5tts_mlx.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/test_f5tts_mlx.py
Labels: feature

#2673 ENH: Guided Decoding OpenAIClient compatibility
  xinference/_compat.py
  xinference/api/restful_api.py
Labels: enhancement

#2670 ENH: support no images for MLX vlm
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/tests/test_mlx.py
Labels: enhancement

#2680 BUG: Fix f5tts audio ref
  xinference/model/audio/f5tts.py
Labels: bug

#2681 FEAT: Support qwen2.5-coder-instruct model for tool calls
  xinference/model/llm/utils.py
Labels: feature

#2672 ENH: Update fish speech 1.5
  xinference/model/audio/fish_speech.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/basic_ref_en.wav
  xinference/model/audio/tests/test_fish_speech.py
  xinference/thirdparty/fish_speech/fish_speech/conversation.py
  xinference/thirdparty/fish_speech/fish_speech/models/text2semantic/llama.py
  xinference/thirdparty/fish_speech/fish_speech/text/clean.py
  xinference/thirdparty/fish_speech/fish_speech/text/spliter.py
  xinference/thirdparty/fish_speech/fish_speech/tokenizer.py
  xinference/thirdparty/fish_speech/fish_speech/train.py
  xinference/thirdparty/fish_speech/fish_speech/webui/manage.py
  xinference/thirdparty/fish_speech/tools/__init__.py
  xinference/thirdparty/fish_speech/tools/api.py
  xinference/thirdparty/fish_speech/tools/api_client.py
  xinference/thirdparty/fish_speech/tools/api_server.py
  xinference/thirdparty/fish_speech/tools/download_models.py
  xinference/thirdparty/fish_speech/tools/fish_e2e.py
  xinference/thirdparty/fish_speech/tools/inference_engine/__init__.py
  xinference/thirdparty/fish_speech/tools/inference_engine/reference_loader.py
  xinference/thirdparty/fish_speech/tools/inference_engine/utils.py
  xinference/thirdparty/fish_speech/tools/inference_engine/vq_manager.py
  xinference/thirdparty/fish_speech/tools/llama/eval_in_context.py
  xinference/thirdparty/fish_speech/tools/llama/generate.py
  xinference/thirdparty/fish_speech/tools/msgpack_api.py
  xinference/thirdparty/fish_speech/tools/run_webui.py
  xinference/thirdparty/fish_speech/tools/schema.py
  xinference/thirdparty/fish_speech/tools/server/agent/__init__.py
  xinference/thirdparty/fish_speech/tools/server/agent/generate.py
  xinference/thirdparty/fish_speech/tools/server/agent/generation_utils.py
  xinference/thirdparty/fish_speech/tools/server/agent/pre_generation_utils.py
  xinference/thirdparty/fish_speech/tools/server/api_utils.py
  xinference/thirdparty/fish_speech/tools/server/exception_handler.py
  xinference/thirdparty/fish_speech/tools/server/inference.py
  xinference/thirdparty/fish_speech/tools/server/model_manager.py
  xinference/thirdparty/fish_speech/tools/server/model_utils.py
  xinference/thirdparty/fish_speech/tools/server/views.py
  xinference/thirdparty/fish_speech/tools/webui.py
  xinference/thirdparty/fish_speech/tools/webui/__init__.py
  xinference/thirdparty/fish_speech/tools/webui/inference.py
  xinference/thirdparty/fish_speech/tools/webui/variables.py
Labels: enhancement

#2684 ENH: Update cosyvoice 2
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/tests/test_cosyvoice.py
  xinference/thirdparty/cosyvoice/bin/__init__.py
  xinference/thirdparty/cosyvoice/bin/average_model.py
  xinference/thirdparty/cosyvoice/bin/export_jit.py
  xinference/thirdparty/cosyvoice/bin/export_onnx.py
  xinference/thirdparty/cosyvoice/bin/export_trt.py
  xinference/thirdparty/cosyvoice/bin/export_trt.sh
  xinference/thirdparty/cosyvoice/bin/inference.py
  xinference/thirdparty/cosyvoice/bin/train.py
  xinference/thirdparty/cosyvoice/cli/cosyvoice.py
  xinference/thirdparty/cosyvoice/cli/frontend.py
  xinference/thirdparty/cosyvoice/cli/model.py
  xinference/thirdparty/cosyvoice/dataset/dataset.py
  xinference/thirdparty/cosyvoice/dataset/processor.py
  xinference/thirdparty/cosyvoice/flow/__init__.py
  xinference/thirdparty/cosyvoice/flow/decoder.py
  xinference/thirdparty/cosyvoice/flow/flow.py
  xinference/thirdparty/cosyvoice/flow/flow_matching.py
  xinference/thirdparty/cosyvoice/flow/length_regulator.py
  xinference/thirdparty/cosyvoice/hifigan/__init__.py
  xinference/thirdparty/cosyvoice/hifigan/discriminator.py
  xinference/thirdparty/cosyvoice/hifigan/f0_predictor.py
  xinference/thirdparty/cosyvoice/hifigan/generator.py
  xinference/thirdparty/cosyvoice/hifigan/hifigan.py
  xinference/thirdparty/cosyvoice/llm/__init__.py
  xinference/thirdparty/cosyvoice/llm/llm.py
  xinference/thirdparty/cosyvoice/tokenizer/assets/multilingual_zh_ja_yue_char_del.tiktoken
  xinference/thirdparty/cosyvoice/tokenizer/tokenizer.py
  xinference/thirdparty/cosyvoice/transformer/embedding.py
  xinference/thirdparty/cosyvoice/transformer/encoder_layer.py
  xinference/thirdparty/cosyvoice/transformer/upsample_encoder.py
  xinference/thirdparty/cosyvoice/utils/common.py
  xinference/thirdparty/cosyvoice/utils/executor.py
  xinference/thirdparty/cosyvoice/utils/file_utils.py
  xinference/thirdparty/cosyvoice/utils/frontend_utils.py
  xinference/thirdparty/cosyvoice/utils/losses.py
  xinference/thirdparty/cosyvoice/utils/scheduler.py
  xinference/thirdparty/cosyvoice/utils/train_utils.py
  xinference/thirdparty/matcha/utils/utils.py
Labels: enhancement

#2695 BUG: `glm4-chat` cannot apply for continuous batching with transformers backend
  xinference/core/model.py
Labels: bug

#2697 FEAT: Support minicpm-4B on vllm
  xinference/model/llm/vllm/core.py
Labels: feature

#2700 FEAT: support scheduling-policy for vllm
  xinference/model/llm/vllm/core.py
Labels: feature

#2711 FEAT: Reduce code redundancy by setting default values
  xinference/model/llm/llm_family.py
Labels: feature

#2712 FEAT: Support QvQ-72B-Preview
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/qwen2_vl.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2721 FEAT: support HunyuanVideo
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/minicpm3-4b.rst
  doc/source/models/builtin/llm/qvq-72b-preview.rst
  doc/source/models/builtin/video/hunyuanvideo.rst
  doc/source/models/builtin/video/index.rst
  doc/source/user_guide/backends.rst
  xinference/model/video/diffusers.py
  xinference/model/video/model_spec.json
Labels: feature, gpu

#2724 BUG: adapt mlx-vlm v0.1.7
  setup.cfg
  xinference/model/llm/mlx/core.py
Labels: bug
