Repository xorbitsai/inference, pull requests merged in 2024-09, with the labels that each got.

#2211 DOC: Modify the installation documentation to change single quotes to double quotes for Windows compatibility.
  doc/source/getting_started/installation.rst
Labels: documentation

#2207 BUG: Fix docker image startup issue due to entrypoint
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/web/ui/package-lock.json
  xinference/web/ui/package.json
Labels: bug

#2208 BUG: fix init xinference fail when custom path is fault
  xinference/core/worker.py
  xinference/model/__init__.py
  xinference/model/audio/__init__.py
  xinference/model/audio/chattts.py
  xinference/model/audio/core.py
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/fish_speech.py
  xinference/model/audio/funasr.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/whisper.py
  xinference/model/embedding/__init__.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/flexible/__init__.py
  xinference/model/image/__init__.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/llm/__init__.py
  xinference/model/rerank/__init__.py
  xinference/model/video/__init__.py
Labels: bug

#2214 BUG: use `default_uid` to replace `uid` of actors which may override the xoscar actor's uid property
  xinference/api/restful_api.py
  xinference/conftest.py
  xinference/core/cache_tracker.py
  xinference/core/event.py
  xinference/core/model.py
  xinference/core/status_guard.py
  xinference/core/supervisor.py
  xinference/core/tests/test_metrics.py
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
  xinference/deploy/local.py
  xinference/deploy/supervisor.py
  xinference/deploy/utils.py
  xinference/deploy/worker.py
Labels: bug

#2219 BUG: fix rerank max length
  xinference/model/rerank/core.py
  xinference/model/rerank/model_spec.json
  xinference/model/rerank/model_spec_modelscope.json
  xinference/model/rerank/tests/test_rerank.py
Labels: bug

#2215 BUG: logger bug of function using generator decoration
  xinference/core/model.py
Labels: bug

#2193 REF: Use `chat_template` for LLM instead of `prompt_style`
  doc/source/getting_started/using_xinference.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/models/custom.po
  doc/source/models/custom.rst
  doc/source/models/lora.rst
  doc/source/models/model_abilities/chat.rst
  doc/source/user_guide/client_api.rst
  doc/source/user_guide/continuous_batching.rst
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/core/chat_interface.py
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/core/supervisor.py
  xinference/core/tests/test_continuous_batching.py
  xinference/core/tests/test_metrics.py
  xinference/core/tests/test_restful_api.py
  xinference/core/tests/test_types.py
  xinference/deploy/cmdline.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_csghub.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/lmdeploy/core.py
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/tests/test_mlx.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/tests/test_multimodal.py
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/cogvlm2_video.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/deepseek_vl.py
  xinference/model/llm/transformers/glm4v.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/transformers/internlm2.py
  xinference/model/llm/transformers/llama_2.py
  xinference/model/llm/transformers/minicpmv25.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/omnilmm.py
  xinference/model/llm/transformers/qwen_vl.py
  xinference/model/llm/transformers/tests/test_tensorizer.py
  xinference/model/llm/transformers/utils.py
  xinference/model/llm/transformers/yi_vl.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
  xinference/web/ui/package-lock.json
  xinference/web/ui/package.json
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
  xinference/web/ui/src/scenes/register_model/components/addStop.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
Labels: refactor

#2228 BUG: fix rerank calculation of tokens number
  xinference/model/rerank/core.py
  xinference/model/rerank/model_spec_modelscope.json
  xinference/model/rerank/tests/test_rerank.py
Labels: bug

#2232 ENH: include openai-whisper into thirdparty
  MANIFEST.in
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/thirdparty/whisper/__init__.py
  xinference/thirdparty/whisper/__main__.py
  xinference/thirdparty/whisper/assets/gpt2.tiktoken
  xinference/thirdparty/whisper/assets/mel_filters.npz
  xinference/thirdparty/whisper/assets/multilingual.tiktoken
  xinference/thirdparty/whisper/audio.py
  xinference/thirdparty/whisper/decoding.py
  xinference/thirdparty/whisper/model.py
  xinference/thirdparty/whisper/normalizers/__init__.py
  xinference/thirdparty/whisper/normalizers/basic.py
  xinference/thirdparty/whisper/normalizers/english.json
  xinference/thirdparty/whisper/normalizers/english.py
  xinference/thirdparty/whisper/timing.py
  xinference/thirdparty/whisper/tokenizer.py
  xinference/thirdparty/whisper/transcribe.py
  xinference/thirdparty/whisper/triton_ops.py
  xinference/thirdparty/whisper/utils.py
  xinference/thirdparty/whisper/version.py
Labels: enhancement

#2192 FEAT: cosyvoice model support streaming reply
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/tests/test_cosyvoice.py
  xinference/thirdparty/cosyvoice/bin/export_jit.py
  xinference/thirdparty/cosyvoice/bin/export_trt.py
  xinference/thirdparty/cosyvoice/bin/inference.py
  xinference/thirdparty/cosyvoice/cli/cosyvoice.py
  xinference/thirdparty/cosyvoice/cli/model.py
  xinference/thirdparty/cosyvoice/flow/flow.py
  xinference/thirdparty/cosyvoice/flow/length_regulator.py
  xinference/thirdparty/cosyvoice/hifigan/generator.py
  xinference/thirdparty/cosyvoice/llm/llm.py
  xinference/thirdparty/cosyvoice/transformer/attention.py
  xinference/thirdparty/cosyvoice/transformer/decoder.py
  xinference/thirdparty/cosyvoice/transformer/embedding.py
  xinference/thirdparty/cosyvoice/transformer/encoder.py
  xinference/thirdparty/cosyvoice/utils/common.py
  xinference/thirdparty/cosyvoice/utils/file_utils.py
Labels: feature

#2221 BUG: fix embedding token calculation & optimize memory
  xinference/model/embedding/core.py
  xinference/model/embedding/tests/test_embedding_models.py
Labels: bug

#2238 ENH: `MiniCPM-V-2.6` Supports continuous batching with transformers engine
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/continuous_batching.po
  doc/source/user_guide/continuous_batching.rst
  xinference/constants.py
  xinference/core/model.py
  xinference/model/llm/transformers/minicpmv26.py
Labels: enhancement

#2205 FEAT: support qwen2-vl-instruct
  .github/workflows/python.yaml
  setup.cfg
  xinference/core/worker.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/qwen2_vl.py
  xinference/model/llm/transformers/qwen_vl.py
Labels: feature

#2173 ENH: Refine request log and add optional request_id
  xinference/constants.py
  xinference/core/model.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#2249 ENH: Update CosyVoice Huggingface
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/test_cosyvoice.py
Labels: enhancement

#2251 FEAT: Support qwen2-vl-instruct GPTQ format and AWQ format
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#2263 FEAT: Support minicpm-4B
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#2248 FEAT: support sdapi/txt2img
  xinference/api/restful_api.py
  xinference/core/image_interface.py
  xinference/core/model.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/fish_speech.py
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/sdapi.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: feature

#2265 ENH: Supports multi functions in tool call for qwen2
  xinference/model/llm/utils.py
Labels: enhancement

#2285 DOC: update readme & builtin models
  README.md
  README_zh_CN.md
  doc/source/models/builtin/audio/cosyvoice-300m-instruct.rst
  doc/source/models/builtin/audio/cosyvoice-300m-sft.rst
  doc/source/models/builtin/audio/cosyvoice-300m.rst
  doc/source/models/builtin/image/sd3-medium.rst
  doc/source/models/builtin/llm/chatglm3-128k.rst
  doc/source/models/builtin/llm/chatglm3-32k.rst
  doc/source/models/builtin/llm/chatglm3.rst
  doc/source/models/builtin/llm/gorilla-openfunctions-v1.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internvl2.rst
  doc/source/models/builtin/llm/llama-2-chat.rst
  doc/source/models/builtin/llm/llama-2.rst
  doc/source/models/builtin/llm/minicpm3-4b.rst
  doc/source/models/builtin/llm/qwen-chat.rst
  doc/source/models/builtin/llm/qwen2-vl-instruct.rst
  doc/source/models/builtin/llm/wizardcoder-python-v1.0.rst
  doc/source/models/builtin/llm/wizardmath-v1.0.rst
  doc/source/models/builtin/llm/zephyr-7b-alpha.rst
  doc/source/models/builtin/llm/zephyr-7b-beta.rst
  doc/source/models/builtin/video/cogvideox-5b.rst
  doc/source/models/builtin/video/index.rst
  doc/source/models/model_abilities/vision.rst
  doc/templates/audio.rst.jinja
Labels: documentation

#2283 ENH: add `print-error` option in benchmark
  benchmark/README.md
  benchmark/benchmark_latency.py
  benchmark/benchmark_long.py
  benchmark/benchmark_rerank.py
  benchmark/benchmark_runner.py
  benchmark/benchmark_serving.py
Labels: enhancement

#2268 FEAT: [UI] Auto-fill chat_template parameter on registration page.
  xinference/core/supervisor.py
  xinference/web/ui/src/scenes/register_model/components/addStop.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
Labels: feature

#2279 BUG: tts stream mode not working
  xinference/client/restful/restful_client.py
Labels: bug

#2288 FEAT: support sdapi/sd-models and sdapi/samplers
  xinference/api/restful_api.py
  xinference/core/image_interface.py
  xinference/model/image/stable_diffusion/core.py
Labels: feature

#2290 BUG: fix issue with model launch failing when .safetensors file is missing (#2094)
  xinference/model/audio/whisper.py
Labels: bug

#2292 FEAT: support deepseek-v2 and 2.5
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/deepseek_v2.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2289 FEAT: Update Qwen2-VL-Model to support flash_attention_2 implementation
  xinference/model/llm/transformers/qwen2_vl.py
Labels: feature

#2295 ENH: Support fish speech 1.4
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/fish_speech.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/test_fish_speech.py
  xinference/thirdparty/fish_speech/fish_speech/configs/firefly_gan_vq.yaml
  xinference/thirdparty/fish_speech/fish_speech/configs/text2semantic_finetune.yaml
  xinference/thirdparty/fish_speech/fish_speech/i18n/locale/en_US.json
  xinference/thirdparty/fish_speech/fish_speech/i18n/locale/es_ES.json
  xinference/thirdparty/fish_speech/fish_speech/i18n/locale/ja_JP.json
  xinference/thirdparty/fish_speech/fish_speech/i18n/locale/pt_BR.json
  xinference/thirdparty/fish_speech/fish_speech/i18n/locale/zh_CN.json
  xinference/thirdparty/fish_speech/fish_speech/models/text2semantic/llama.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/__init__.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/lit_module.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/modules/discriminator.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/modules/firefly.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/modules/fsq.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/modules/reference.py
  xinference/thirdparty/fish_speech/fish_speech/models/vqgan/modules/wavenet.py
  xinference/thirdparty/fish_speech/fish_speech/text/clean.py
  xinference/thirdparty/fish_speech/fish_speech/text/spliter.py
  xinference/thirdparty/fish_speech/fish_speech/train.py
  xinference/thirdparty/fish_speech/fish_speech/webui/manage.py
  xinference/thirdparty/fish_speech/tools/api.py
  xinference/thirdparty/fish_speech/tools/auto_rerank.py
  xinference/thirdparty/fish_speech/tools/commons.py
  xinference/thirdparty/fish_speech/tools/download_models.py
  xinference/thirdparty/fish_speech/tools/file.py
  xinference/thirdparty/fish_speech/tools/gen_ref.py
  xinference/thirdparty/fish_speech/tools/llama/build_dataset.py
  xinference/thirdparty/fish_speech/tools/llama/generate.py
  xinference/thirdparty/fish_speech/tools/llama/merge_lora.py
  xinference/thirdparty/fish_speech/tools/llama/quantize.py
  xinference/thirdparty/fish_speech/tools/merge_asr_files.py
  xinference/thirdparty/fish_speech/tools/msgpack_api.py
  xinference/thirdparty/fish_speech/tools/post_api.py
  xinference/thirdparty/fish_speech/tools/sensevoice/fun_asr.py
  xinference/thirdparty/fish_speech/tools/smart_pad.py
  xinference/thirdparty/fish_speech/tools/vqgan/extract_vq.py
  xinference/thirdparty/fish_speech/tools/vqgan/inference.py
  xinference/thirdparty/fish_speech/tools/webui.py
Labels: enhancement

#2293 FEAT: support sdapi/img2img
  xinference/api/restful_api.py
  xinference/core/model.py
  xinference/model/image/sdapi.py
  xinference/types.py
Labels: feature

#2296 FEAT: support flux.1 image2image and inpainting
  .github/workflows/python.yaml
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/stable_diffusion/core.py
Labels: feature

#2302 FEAT: Support yi-coder-chat
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2301 BUG: fix sampler_name for img2img
  xinference/model/image/sdapi.py
  xinference/model/image/stable_diffusion/core.py
Labels: bug

#2271 FEAT: qwen2 audio
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/qwen2_audio.py
Labels: feature

#2311 BUG: modify vllm image version
  xinference/deploy/docker/Dockerfile
Labels: bug

#2312 Bug: modify vllm image version
  xinference/deploy/docker/Dockerfile
Labels: bug

#2315 BUG: [UI] Fix registration page bug.
  xinference/web/ui/src/scenes/register_model/registerModel.js
Labels: bug

#2320 BUG: Fix CosyVoice missing output
  xinference/model/audio/cosyvoice.py
Labels: bug

#2325 FEAT: Support Qwen 2.5
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2335 BUG: support old register llm format
  xinference/model/llm/__init__.py
Labels: bug

#2336 BUG: fix stable diffusion from dify tool
  xinference/core/model.py
  xinference/model/image/stable_diffusion/core.py
Labels: bug

#2330 DOC: update models for doc and readme
  README.md
  README_zh_CN.md
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/audio/fishspeech-1.2-sft.rst
  doc/source/models/builtin/audio/fishspeech-1.4.rst
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/image/flux.1-dev.rst
  doc/source/models/builtin/image/flux.1-schnell.rst
  doc/source/models/builtin/llm/deepseek-v2-chat-0628.rst
  doc/source/models/builtin/llm/deepseek-v2-chat.rst
  doc/source/models/builtin/llm/deepseek-v2.5.rst
  doc/source/models/builtin/llm/deepseek-v2.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen2-audio-instruct.rst
  doc/source/models/builtin/llm/qwen2-audio.rst
  doc/source/models/builtin/llm/qwen2.5-instruct.rst
  doc/source/models/builtin/llm/yi-coder-chat.rst
  doc/source/models/builtin/llm/yi-coder.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#2332 FEAT: support qwen2.5-coder-instruct and qwen2.5 sglang
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2353 BUG: [UI] Fix 'Model Format' bug on model registration page.
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
Labels: bug

#2379 Feat: Support jina-embedding-v3
  setup.cfg
  xinference/client/tests/test_client.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/embedding/core.py
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/rerank/core.py
  xinference/model/utils.py
Labels: feature

#2313 FEAT: Support deepcache with sd models
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/model/image/stable_diffusion/core.py
Labels: feature

#2385 BUG: Fix default value of max_model_len for vLLM backend.
  xinference/model/llm/vllm/core.py
Labels: bug

#2384 FEAT: add vllm restart check and support internvl multi-image chat
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/model/llm/vllm/utils.py
Labels: feature
