Repository xorbitsai/inference, pull requests merged in 2024-04, with the labels that each got.

#1219 BUG: Cannot start xinference in docker
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
Labels: bug

#1227 BUG: Fix `opencv` issue in docker container
  setup.cfg
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
Labels: bug

#1241 BUG: Fix the launch bug of OmnilMM 12B.
  xinference/thirdparty/omnilmm/chat.py
Labels: bug

#1242 TST: Fix tests due to `llama-cpp-python` `v0.2.58`
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
Labels: testing

#1224 ENH: make function create_embedding could receive extra args
  xinference/api/restful_api.py
  xinference/client/oscar/actor_client.py
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/model/embedding/core.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/rerank/core.py
  xinference/model/rerank/tests/test_rerank.py
Labels: enhancement

#1243 ENH: support more GPTQ and AWQ format for some models
  xinference/model/llm/llm_family.json
Labels: enhancement

#1247 BUG: style spell error
  xinference/web/ui/src/scenes/launch_model/index.js
Labels: bug

#1249 FEAT: add support for qwen1.5 32B chat model
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#1231 BUG: Fix issue with supervisor not clearing information after worker exit
  xinference/core/supervisor.py
Labels: bug

#1254 REF: Refactor launch model for Web UI
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/audioCard.js
  xinference/web/ui/src/scenes/launch_model/embeddingCard.js
  xinference/web/ui/src/scenes/launch_model/imageCard.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchAudio.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchEmbedding.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/launchRerank.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/rerankCard.js
  xinference/web/ui/src/scenes/launch_model/styles/launchModelStyle.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.js
Labels: refactor

#1234 DOC: auto gen vllm doc & add chatglm3-{32k, 128k} support for vllm
  doc/source/gen_docs.py
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
  xinference/model/llm/vllm/core.py
Labels: documentation

#1236 ENH: support multi gpus for qwen-vl and yi-vl
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/yi_vl.py
Labels: enhancement, gpu

#1246 DOC: update models doc
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/llama-2-chat.rst
  doc/source/models/builtin/llm/llama-2.rst
  doc/source/models/builtin/llm/mistral-instruct-v0.1.rst
  doc/source/models/builtin/llm/mistral-instruct-v0.2.rst
  doc/source/models/builtin/llm/mixtral-instruct-v0.1.rst
  doc/source/models/builtin/llm/mixtral-v0.1.rst
  doc/source/models/builtin/llm/qwen1.5-chat.rst
Labels: documentation

#1263 FEAT: Support Qwen MoE model for huggingface and modelscope
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen1.5-moe-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1229 ENH: support llamacpp multiple gpu
  xinference/types.py
Labels: enhancement, gpu

#1268 DOC: update readme
  README.md
  README_zh_CN.md
  doc/source/models/model_abilities/chat.rst
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
Labels: documentation

#1271 BUG: fix system prompts for chatglm3 and internlm2 pytorch
  doc/source/getting_started/installation.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/vllm/core.py
Labels: bug

#1267 REF: Remove ctransformers supports
  .github/workflows/python.yaml
  doc/source/getting_started/installation.rst
  doc/source/locale/ja_JP/LC_MESSAGES/user_guide/backends.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
  setup.cfg
  xinference/core/tests/test_types.py
  xinference/model/llm/__init__.py
  xinference/model/llm/ggml/ctransformers.py
  xinference/model/llm/ggml/ctransformers_util.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/ggml/tests/test_ctransformers.py
  xinference/model/llm/llm_family.json
  xinference/types.py
Labels: refactor

#1215 FEAT: Enable streaming in tool calls for Qwen when using vllm
  xinference/api/restful_api.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
Labels: feature

#1276 BUG: Fix authority and jump issue
  xinference/web/ui/src/App.js
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/Title.js
  xinference/web/ui/src/components/authAlertDialog.js
  xinference/web/ui/src/components/fetcher.js
  xinference/web/ui/src/router/index.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/login/login.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/register_embedding.js
  xinference/web/ui/src/scenes/register_model/register_rerank.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#1261 ENH: UI: paper material for cards
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.js
Labels: enhancement

#1280 BUG: fix custom vision model
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/tests/test_llm_family.py
Labels: bug

#1279 ENH: Support custom audio model
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/audio/__init__.py
  xinference/model/audio/core.py
  xinference/model/audio/custom.py
  xinference/model/audio/tests/test_whisper.py
Labels: enhancement

#1306 FEAT: [UI] Add replica configuration when launching `embedding` and `rerank` models
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1277 ENH: support int and str compare for model size
  xinference/client/restful/restful_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/core.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/utils.py
Labels: enhancement

#1273 FEAT: Lora multi support
  doc/source/models/lora.rst
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/core.py
  xinference/model/image/core.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/pytorch/baichuan.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/falcon.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/pytorch/llama_2.py
  xinference/model/llm/pytorch/vicuna.py
  xinference/types.py
  xinference/utils.py
Labels: feature

#1310 FEAT: Support SeaLLM-7B and c4ai-command-r-v01
  xinference/model/llm/llm_family.json
Labels: feature

#1305 FEAT: Support BAAI/bge-reranker-v2-* rerank model
  .github/workflows/python.yaml
  setup.cfg
  xinference/model/rerank/core.py
  xinference/model/rerank/model_spec.json
  xinference/model/rerank/model_spec_modelscope.json
  xinference/model/rerank/tests/test_rerank.py
Labels: feature

#1318 BLD: Add `FlagEmbedding` in cpu docker
  xinference/deploy/docker/cpu.Dockerfile
Labels: build

#1320 FEAT: UI supports multi lora
  xinference/types.py
  xinference/web/ui/src/scenes/launch_model/components/addPair.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1321 FEAT: Add_cia4command_modelscope
  doc/source/models/builtin/llm/c4ai-command-r-v01-4bit.rst
  doc/source/models/builtin/llm/c4ai-command-r-v01.rst
  doc/source/models/builtin/llm/gpt-2.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/seallm_v2.5.rst
  doc/source/models/builtin/llm/seallm_v2.rst
  doc/source/models/builtin/rerank/bge-reranker-v2-gemma.rst
  doc/source/models/builtin/rerank/bge-reranker-v2-m3.rst
  doc/source/models/builtin/rerank/bge-reranker-v2-minicpm-layerwise.rst
  doc/source/models/builtin/rerank/index.rst
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1294 REF: support query for engine feature
  xinference/api/restful_api.py
  xinference/core/supervisor.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: refactor

#1298 FEAT: support m3e embedding models
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
Labels: feature

#1287 FEAT: hotkey to active search
  xinference/web/ui/src/components/hotkeyFocusTextField.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
Labels: feature

#1322 FEAT: support codeqwen1.5-chat
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/embedding/m3e-base.rst
  doc/source/models/builtin/embedding/m3e-large.rst
  doc/source/models/builtin/embedding/m3e-small.rst
  doc/source/models/builtin/llm/codeqwen1.5-chat.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1330 BUG: Fix `xinference-client` package depends on internal code
  xinference/client/restful/restful_client.py
Labels: bug

#1331 BUG: Fix restful client depends on specific type
  xinference/client/restful/restful_client.py
Labels: bug

#1343 BUG: Fix Launching embedding or reranking models from commandline fails due to PEFT
  xinference/deploy/cmdline.py
Labels: bug

#1332 FEAT: support llama-3 family
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/llama-3-instruct.rst
  doc/source/models/builtin/llm/llama-3.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_utils.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1351 FEAT: Add Belle-whisper-large-v3-zh
  xinference/model/audio/model_spec.json
Labels: feature

#1348 BUG: Fix extra parameters issue when auto-recovering models
  xinference/core/worker.py
Labels: bug

#1355 DOC: Update README, add FastGPT to integrations
  README.md
  README_zh_CN.md
Labels: documentation

#1354 ENH: fix the max length of codeqwen-7B-chat
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#1350 BUG: Fix old rerank models use flag rerank issue
  xinference/model/rerank/core.py
Labels: bug

#1360 ENH: Clear cache for embedding and rerank
  xinference/model/embedding/core.py
  xinference/model/rerank/core.py
Labels: enhancement

#1342 REF: Query for engine
  xinference/api/restful_api.py
  xinference/core/supervisor.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
Labels: refactor

#1312 ENH: add custom image model
  examples/Custom_StableDiffusion_ControlNet.ipynb
  examples/draft.png
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/image/__init__.py
  xinference/model/image/core.py
  xinference/model/image/custom.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: enhancement

#1370 BUG: Fix llama3-instruct 70B filename error
  xinference/model/llm/llm_family.json
Labels: bug

#1340 FEAT: Support Mixtral-8x22b-instruct-v0.1
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/audio/belle-whisper-large-v3-zh.rst
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/llm/codeqwen1.5-chat.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/mixtral-8x22b-instruct-v0.1.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1378 BUG: no role:user msg or content empty got an error.
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
Labels: bug

#1372 ENH: Support more quantization with VLLM
  doc/source/getting_started/installation.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/vllm/core.py
Labels: enhancement

#1368 REF: [UI] Refactor register model
  xinference/web/ui/package-lock.json
  xinference/web/ui/package.json
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/register_model/components/addControlnet.js
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
  xinference/web/ui/src/scenes/register_model/data/languages.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/register_embedding.js
  xinference/web/ui/src/scenes/register_model/register_rerank.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
Labels: refactor

#1385 DOC: update readme & fix Mac CI
  .github/workflows/python.yaml
  README.md
  README_zh_CN.md
Labels: documentation

#1389 BUG: fix file template of andrewcanis/c4ai-command-r-v01-GGUF
  xinference/model/llm/llm_family.json
Labels: bug

#1379 feat: add phi-3-mini series
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/phi-3-mini-128k-instruct.rst
  doc/source/models/builtin/llm/phi-3-mini-4k-instruct.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
Labels: feature

#1384 FEAT: add Starling model
  xinference/model/llm/llm_family.json
Labels: feature

#1388 FEAT: support qwen1.5 110b
  doc/source/models/builtin/llm/qwen1.5-chat.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_llm_family.py
Labels: feature

#1397 DOC: worker address should be specified for `xinference-worker`
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/ja_JP/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
Labels: documentation

#1400 BUG: Fix using extra gpus due to match in `__init__`
  xinference/client/tests/test_client.py
  xinference/conftest.py
  xinference/core/tests/test_metrics.py
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
Labels: bug, gpu

#1401 ENH: Update chatglm3 6b model version
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#1405 BLD: Use self-hosted aws machine to build docker image
  .github/workflows/docker-cd.yaml
Labels: build

#1381 BUG: Fix qwen tool call paramerter empty issue
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/utils.py
Labels: bug
