Repository xorbitsai/inference, pull requests merged in 2024-06, with the labels that each got.

#1573 BUG: Fix typo for cogvlm2
  doc/source/models/builtin/llm/cogvlm2.rst
  xinference/model/llm/llm_family.json
Labels: bug

#1572 ENH: make CogVLM2 support stream output
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/cogvlm2.py
Labels: enhancement

#1577 FEAT: new model: mini-cpm-llama3-v-2.5
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/minicpmv25.py
Labels: feature

#1584 FEAT: support glm4-chat & glm4-chat-1m
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/glm4-chat-1m.rst
  doc/source/models/builtin/llm/glm4-chat.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1576 FEAT: add mistral-instruct-v0.3
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/mistral-instruct-v0.3.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1575 FEAT: add codestral-v0.1
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/codestral-v0.1.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internvl-chat.rst
  doc/source/models/builtin/llm/telechat.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1578 FEAT: Support ChatTTS
  .github/workflows/python.yaml
  doc/source/models/builtin/audio/chattts.rst
  doc/source/models/builtin/audio/index.rst
  doc/templates/audio.rst.jinja
  pyproject.toml
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/model/audio/chattts.py
  xinference/model/audio/core.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/test_chattts.py
  xinference/thirdparty/ChatTTS/__init__.py
  xinference/thirdparty/ChatTTS/core.py
  xinference/thirdparty/ChatTTS/experimental/llm.py
  xinference/thirdparty/ChatTTS/infer/api.py
  xinference/thirdparty/ChatTTS/model/dvae.py
  xinference/thirdparty/ChatTTS/model/gpt.py
  xinference/thirdparty/ChatTTS/utils/gpu_utils.py
  xinference/thirdparty/ChatTTS/utils/infer_utils.py
  xinference/thirdparty/ChatTTS/utils/io_utils.py
Labels: feature

#1593 DOC: Fix audio doc
  doc/source/getting_started/installation.rst
  doc/source/reference/index.rst
  doc/source/user_guide/backends.rst
  xinference/client/restful/restful_client.py
Labels: documentation

#1589 DOC: Usage about cal-model-memory
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_memory.po
  doc/source/models/index.rst
  doc/source/models/model_memory.rst
Labels: documentation

#1595 BLD: Docker clean all images after building image on self-hosted machine
  .github/workflows/docker-cd.yaml
Labels: build

#1599 DOC: Fix audio doc
  doc/source/locale/zh_CN/LC_MESSAGES/development/xinference_internals.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/audio.po
  doc/source/models/model_abilities/audio.rst
  xinference/model/audio/model_spec.json
Labels: documentation

#1548 FEAT: Continuous batching for chat model on transformers backend
  benchmark/benchmark_serving.py
  benchmark/utils.py
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/constants.py
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/core/supervisor.py
  xinference/core/tests/test_continuous_batching.py
  xinference/isolation.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/utils.py
  xinference/types.py
Labels: feature

#1597 FEAT: support qwen2
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen2-instruct.rst
  doc/source/models/builtin/llm/qwen2-moe-instruct.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#1591 Feat: support glm-4v 9b
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/glm4v.py
Labels: feature

#1602 DOC: Continuous batching
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/continuous_batching.po
  doc/source/user_guide/continuous_batching.rst
  doc/source/user_guide/index.rst
Labels: documentation

#1604 DOC: add new models to readme
  README.md
  README_zh_CN.md
  doc/source/models/builtin/llm/glm-4v.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/model_abilities/vision.rst
Labels: documentation

#1603 BLD: Fix pip is looking multiple versions of some packages while installing
  setup.cfg
  xinference/deploy/docker/cpu.Dockerfile
Labels: build

#1606 BUG: Fix wheel package missing thirdparty ChatTTS
  xinference/thirdparty/ChatTTS/experimental/__init__.py
  xinference/thirdparty/ChatTTS/infer/__init__.py
  xinference/thirdparty/ChatTTS/model/__init__.py
  xinference/thirdparty/ChatTTS/utils/__init__.py
Labels: bug

#1607 ENH: modelscope for audio models
  xinference/model/audio/__init__.py
  xinference/model/audio/core.py
  xinference/model/audio/custom.py
  xinference/model/audio/model_spec_modelscope.json
Labels: enhancement

#1616 BUG: fix XINFERENCE_MODEL_SRC behavior
  xinference/model/utils.py
Labels: bug

#1621 ENH: Supports `generate` interface for continuous batching
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/utils.py
Labels: enhancement

#1598 BUG: Filtering Step for Streaming Responses to Qwen's Tool Calls when using vLLM
  xinference/model/llm/tests/test_stream_options.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#1631 FEAT: qwen2-instruct support tool call
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/utils.py
Labels: feature

#1627 FEAT: Added a method to download models from csghub.
  xinference/constants.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_csghub.json
  xinference/model/utils.py
Labels: feature

#1617 FEAT: glm4-chat support tool call
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/utils.py
Labels: feature

#1637 FEAT: [UI] Supports viewing and deleting cache data.
  xinference/web/ui/src/scenes/cluster_info/index.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
Labels: feature

#1610 ENH: quantization for glm-4v
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/glm4v.py
Labels: enhancement

#1645 BUG: show error when user launch quantized model without device supported
  xinference/model/llm/pytorch/glm4v.py
Labels: bug

#1649 BUG: Fix default rerank type
  xinference/model/rerank/core.py
Labels: bug

#1642 FEAT: Add Tools Support for Qwen Series MOE Models
  xinference/api/restful_api.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/utils.py
Labels: feature

#1660 TST: Fix CI due to `tenacity`
  .github/workflows/python.yaml
Labels: testing

#1656 FEAT: [UI]Modify the deletion function of a custom model.
  xinference/web/ui/src/components/deleteDialog.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1659 ENH: Continuous batching supports all the models with `transformers` backend
  .github/workflows/python.yaml
  xinference/api/restful_api.py
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/core/tests/test_continuous_batching.py
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/pytorch/utils.py
Labels: enhancement

#1663 BUG: chat_completion not response while error appears more than 100
  xinference/core/event.py
Labels: bug

#1670 FEAT: [UI]Custom model presents JSON data and modifies it.
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/copyComponent/copyComponent.js
  xinference/web/ui/src/components/copyComponent/style.css
  xinference/web/ui/src/components/deleteDialog.js
  xinference/web/ui/src/router/index.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/launchModelStyle.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
  xinference/web/ui/src/scenes/register_model/components/addControlnet.js
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
Labels: feature

#1657 FEAT: Add Rerank model token input/output usage
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/model/rerank/core.py
  xinference/model/rerank/tests/test_rerank.py
  xinference/types.py
Labels: feature

#1692 BLD: pin `chatglm-cpp` version `v0.3.x`
  xinference/deploy/docker/Dockerfile
Labels: build

#1707 BUG: [UI] Fix deleting prompt_style when Model Family is other.
  xinference/web/ui/src/scenes/register_model/registerModel.js
Labels: bug

#1710 BUG: GGUF models cannot use GPU in docker
  xinference/deploy/docker/Dockerfile
Labels: bug, gpu

#1666 ENH: Set the CSG Hub endpoint as an environment variable.
  xinference/constants.py
  xinference/model/llm/llm_family.py
Labels: enhancement

#1648 BUG: Fix tool call observation
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#1728 BUG: [UI]fix favorite bug.
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
Labels: bug

#1723 FEAT: add SD3 support
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/image.po
  doc/source/models/builtin/image/index.rst
  doc/source/models/builtin/image/sd3-medium.rst
  doc/source/models/builtin/llm/glm-4v.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen1.5-moe-chat.rst
  doc/source/models/builtin/llm/qwen2-moe-instruct.rst
  doc/source/models/model_abilities/image.rst
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
Labels: feature

#1730 FEAT: [UI] Add the function of automatically obtaining the last configuration information.
  xinference/web/ui/src/scenes/launch_model/components/addPair.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#1732 BUG: curl with stream returns unicode chars rather than chinese character
  xinference/core/model.py
Labels: bug

#1733 FEAT: support jina-rerank-v2
  doc/source/models/builtin/rerank/index.rst
  doc/source/models/builtin/rerank/jina-reranker-v2.rst
  setup.cfg
  xinference/model/rerank/core.py
  xinference/model/rerank/model_spec.json
Labels: feature

#1579 FEAT: `tensorizer` integration
  .github/workflows/python.yaml
  setup.cfg
  xinference/constants.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/pytorch/cogvlm2.py
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/glm4v.py
  xinference/model/llm/pytorch/intern_vl.py
  xinference/model/llm/pytorch/internlm2.py
  xinference/model/llm/pytorch/minicpmv25.py
  xinference/model/llm/pytorch/omnilmm.py
  xinference/model/llm/pytorch/qwen_vl.py
  xinference/model/llm/pytorch/tensorizer_utils.py
  xinference/model/llm/pytorch/tests/test_tensorizer.py
  xinference/types.py
Labels: feature

#1731 BUG: Cluster info can be accessed without authorization in the auth mode
  xinference/api/restful_api.py
  xinference/conftest.py
  xinference/core/tests/test_restful_api.py
  xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
  xinference/web/ui/src/scenes/launch_model/index.js
Labels: bug

#1719 FEAT: Delete cluster
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
Labels: feature
