Repository xorbitsai/inference, pull requests merged in 2024-10, with the labels that each got.

#2388 FEAT: Llama 3.1 Instruct support tool call
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/utils.py
  xinference/model/llm/utils.py
Labels: feature

#2409 FEAT: add whisper-large-v3-turbo audio model
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
Labels: feature

#2346 REF: refactor controlnet for image model
  examples/StableDiffusionControlNet.ipynb
  xinference/model/image/core.py
  xinference/model/image/sdapi.py
  xinference/model/image/stable_diffusion/core.py
Labels: refactor

#2419 BUG: Pin ChatTTS<0.2
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: bug

#2411 FEAT: Add environment variable setting to increase the retry attempts after model download failures
  xinference/constants.py
  xinference/model/audio/core.py
  xinference/model/image/core.py
  xinference/model/utils.py
  xinference/model/video/core.py
Labels: feature

#2416 BUG: tool call streaming output has duplicated list
  xinference/model/llm/utils.py
Labels: bug

#2425 ENH: Launch the ChatTTS model with kwargs
  xinference/model/audio/chattts.py
  xinference/model/audio/tests/test_chattts.py
Labels: enhancement

#2395 FEAT: support getting progress for image model
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/image_interface.py
  xinference/core/model.py
  xinference/core/progress_tracker.py
  xinference/core/supervisor.py
  xinference/core/tests/test_progressor.py
  xinference/core/worker.py
  xinference/model/image/sdapi.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
  xinference/model/llm/transformers/tests/test_opt.py
Labels: feature

#2428 FEAT: support qwenvl2 vllm engine
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/cogvlm2_video.py
  xinference/model/llm/transformers/deepseek_vl.py
  xinference/model/llm/transformers/glm4v.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/transformers/minicpmv25.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/omnilmm.py
  xinference/model/llm/transformers/qwen2_audio.py
  xinference/model/llm/transformers/qwen2_vl.py
  xinference/model/llm/transformers/qwen_vl.py
  xinference/model/llm/transformers/utils.py
  xinference/model/llm/transformers/yi_vl.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/model/llm/vllm/utils.py
Labels: feature

#2435 DOC: update readme & docs
  README.md
  README_ja_JP.md
  README_zh_CN.md
  assets/stay_ahead.gif
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/whisper-large-v3-turbo.rst
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/embedding/jina-embeddings-v3.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen2-vl-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-coder-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-coder.rst
  doc/source/models/builtin/llm/qwen2.5-instruct.rst
  doc/source/models/builtin/llm/qwen2.5.rst
  doc/source/models/builtin/rerank/index.rst
  doc/source/models/builtin/rerank/minicpm-reranker.rst
  doc/source/models/model_abilities/audio.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#2445 FEAT: Adding support for awq/gptq inference to VisionModel such as Qwen2-VL
  xinference/model/llm/vllm/core.py
Labels: feature

#2437 REF: Enable continuous batching for LLM with transformers engine by default
  xinference/constants.py
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/deepseek_v2.py
  xinference/model/llm/transformers/internlm2.py
  xinference/model/llm/transformers/opt.py
  xinference/model/llm/transformers/tests/test_opt.py
  xinference/model/llm/transformers/utils.py
  xinference/model/llm/utils.py
Labels: refactor

#2443 ENH: Speed up cli interaction
  xinference/__init__.py
  xinference/deploy/supervisor.py
  xinference/model/__init__.py
  xinference/utils.py
Labels: enhancement

#2380 FEAT: Dynamic batching for the state-of-the-art FLUX.1 `text_to_image` interface
  .github/workflows/python.yaml
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/continuous_batching.po
  doc/source/user_guide/continuous_batching.rst
  xinference/constants.py
  xinference/core/model.py
  xinference/core/scheduler.py
  xinference/core/utils.py
  xinference/model/image/scheduler/__init__.py
  xinference/model/image/scheduler/flux.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/utils.py
Labels: feature

#2444 FEAT: added MLX for qwen2.5-instruct
  doc/source/models/builtin/llm/qwen2.5-instruct.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
Labels: feature

#2449 ENH: Support ChatTTS 0.2
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/chattts.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/tests/test_chattts.py
Labels: enhancement

#2461 DOC: update enterprise doc links
  README.md
  README_zh_CN.md
Labels: documentation

#2408 FEAT: Add support for Qwen/Qwen2.5-Coder-7B-Instruct gptq format
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#2458 FEAT: Support GOT-OCR2_0
  .github/workflows/python.yaml
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/ocr/__init__.py
  xinference/model/image/ocr/got_ocr2.py
  xinference/model/image/tests/test_got_ocr2.py
Labels: feature

#2479 BUG: fix embedding model gte-Qwen2 dimensions
  doc/source/models/builtin/embedding/gte-qwen2.rst
  xinference/model/embedding/model_spec.json
Labels: bug

#2473 ENH: Pending queue for concurrent requests
  xinference/client/tests/test_client.py
  xinference/core/model.py
  xinference/core/tests/test_model.py
Labels: enhancement

#2482 FEAT: [UI] Image model with the lora_config.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#2459 FEAT: added MLX support for Flux.1
  setup.cfg
  xinference/core/chat_interface.py
  xinference/core/image_interface.py
  xinference/core/scheduler.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/scheduler/flux.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/stable_diffusion/mlx.py
  xinference/thirdparty/mlx/__init__.py
  xinference/thirdparty/mlx/flux/__init__.py
  xinference/thirdparty/mlx/flux/autoencoder.py
  xinference/thirdparty/mlx/flux/clip.py
  xinference/thirdparty/mlx/flux/datasets.py
  xinference/thirdparty/mlx/flux/flux.py
  xinference/thirdparty/mlx/flux/layers.py
  xinference/thirdparty/mlx/flux/lora.py
  xinference/thirdparty/mlx/flux/model.py
  xinference/thirdparty/mlx/flux/sampler.py
  xinference/thirdparty/mlx/flux/t5.py
  xinference/thirdparty/mlx/flux/tokenizers.py
  xinference/thirdparty/mlx/flux/trainer.py
  xinference/thirdparty/mlx/flux/utils.py
Labels: feature

#2485 DOC: modify NPU doc
  doc/source/getting_started/installation_npu.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation_npu.po
Labels: documentation

#2492 DOC: Add doc for ocr
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/image.po
  doc/source/models/builtin/image/got-ocr2_0.rst
  doc/source/models/builtin/image/index.rst
  doc/source/models/model_abilities/image.rst
  xinference/model/image/ocr/got_ocr2.py
Labels: documentation
