Repository xorbitsai/inference, pull requests merged in 2024-08, with the labels that each got.

#1990 BUG: [UI]Modifying 'model format' again resulted in an error message.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#1929 ENH: Support for Gemma 2 and Llama 3.1 Models for vllm & sglang
  doc/source/getting_started/installation.rst
  setup.cfg
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: enhancement, gpu

#1997 ENH: [K8s] worker log dir name
  xinference/deploy/utils.py
Labels: enhancement

#1987 BUG: fix loading multiple gguf parts
  xinference/model/llm/ggml/llamacpp.py
  xinference/model/llm/llm_family.py
Labels: bug

#1986 ENH: support image_to_image
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/image_interface.py
  xinference/core/model.py
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: enhancement

#2004 DOC: Documents for K8s
  README.md
  README_zh_CN.md
  doc/source/getting_started/index.rst
  doc/source/getting_started/using_kubernetes.rst
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_kubernetes.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
Labels: documentation

#1994 FEAT: Support gte-Qwen2-7B-instruct and multi gpu deploy
  xinference/model/embedding/core.py
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/embedding/tests/test_embedding_models.py
Labels: feature, gpu

#2011 BUG: fix flexible model register in worker
  xinference/core/worker.py
Labels: bug

#2009 ENH: Improve internal server error
  doc/source/models/model_abilities/audio.rst
  xinference/api/restful_api.py
Labels: enhancement

#2015 BUG: [UI] Fix the 'model_path' bug.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#2016 BUG: fix custom embedding launch error
  xinference/model/embedding/core.py
Labels: bug

#2008 FEAT: support SenseVoice audio-to-text model
  .github/workflows/python.yaml
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/sensevoicesmall.rst
  doc/source/models/model_abilities/audio.rst
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/core.py
  xinference/model/audio/funasr.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/tests/test_funasr.py
  xinference/model/audio/whisper.py
Labels: feature

#2028 FEAT: support kolors image model
  doc/source/models/builtin/image/kolors.rst
  xinference/core/image_interface.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
Labels: feature

#2025 FEAT: Add support for llama-3.1-instruct 405B model
  setup.cfg
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#2042 TST: Fix some dependency version issues
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: testing

#2043 REF: Mark `Deprecate` for `prompt`, `system_prompt` and `chat_history` parameters in `chat` client interface
  doc/source/locale/ja_JP/LC_MESSAGES/reference/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
  doc/source/reference/index.rst
  xinference/client/handlers.py
  xinference/client/restful/restful_client.py
  xinference/core/chat_interface.py
  xinference/deploy/cmdline.py
  xinference/deploy/docker/cpu.Dockerfile
  xinference/types.py
Labels: refactor

#2047 DOC: Directly launch custom model by `model_path`
  doc/source/locale/zh_CN/LC_MESSAGES/models/custom.po
  doc/source/models/custom.rst
Labels: documentation

#2048 DOC: fix typo in README
  README.md
Labels: documentation

#2038 ENH: Add `stream` option in Benchmark
  benchmark/benchmark_latency.py
  benchmark/benchmark_long.py
  benchmark/benchmark_rerank.py
  benchmark/benchmark_runner.py
  benchmark/benchmark_serving.py
  benchmark/utils.py
Labels: enhancement

#2046 ENH: optimize availability of vLLM
  xinference/core/model.py
  xinference/core/worker.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#1958 ENH: [worker] Allow init supervisor_ref lazy
  xinference/core/worker.py
Labels: enhancement

#2050 ENH: optimize performance of sglang
  xinference/core/model.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#2049 FEAT: Support CogVideoX video model
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/constants.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/core.py
  xinference/model/video/__init__.py
  xinference/model/video/core.py
  xinference/model/video/diffusers.py
  xinference/model/video/model_spec.json
  xinference/model/video/model_spec_modelscope.json
  xinference/model/video/tests/__init__.py
  xinference/model/video/tests/test_diffusers_video.py
  xinference/types.py
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#2031 FEAT: Support MiniCPM-v-2_6
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/pytorch/core.py
  xinference/model/llm/pytorch/minicpmv26.py
Labels: feature

#2056 DOC: update readme & add tips for large image models
  README.md
  README_zh_CN.md
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/audio.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/image.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/vision.po
  doc/source/models/model_abilities/image.rst
Labels: documentation

#2067 BUG: limit AutoAWQ version to fix docker issue
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: bug

#2081 BUG: Fix custom glm4 & remove tool calls of ChatGLM3
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/pytorch/chatglm.py
  xinference/model/llm/utils.py
Labels: bug

#2039 BUG: Infinited loop with login
  xinference/web/ui/src/App.js
  xinference/web/ui/src/components/Title.js
  xinference/web/ui/src/components/authAlertDialog.js
  xinference/web/ui/src/components/fetchWrapper.js
  xinference/web/ui/src/components/fetcher.js
  xinference/web/ui/src/router/index.js
  xinference/web/ui/src/scenes/cluster_info/index.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#2069 FEAT: support FP8 for vllm & sglang engine
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
Labels: feature

#2068 ENH: make MiniCPM v2.6 support video
  .github/workflows/python.yaml
  setup.cfg
  xinference/core/chat_interface.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/pytorch/minicpmv26.py
Labels: enhancement

#2079 Feat: Support internvl2 and internvl stream
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/transformers/utils.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/thirdparty/internvl/__init__.py
  xinference/thirdparty/internvl/conversation.py
Labels: feature

#2096 FEAT: ChatTTS speech voice support encoded speaker str
  xinference/model/audio/chattts.py
  xinference/model/audio/tests/test_chattts.py
Labels: feature

#2105 REF: use utils._decode_image replacing same codes in individual vl files
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/glm4v.py
  xinference/model/llm/transformers/minicpmv25.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/yi_vl.py
Labels: refactor

#2108 DOC: add more doc about ChatTTS
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/audio.po
  doc/source/models/model_abilities/audio.rst
Labels: documentation

#2113 BUG: fix asyncio.Queue error in benchmark
  benchmark/benchmark_runner.py
  benchmark/benchmark_serving.py
Labels: bug

#2114 BUG: fix deleting cache
  xinference/core/worker.py
Labels: bug

#2122 DOC: remove models deleted
  doc/source/gen_docs.py
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/vision.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/models/builtin/llm/baichuan-chat.rst
  doc/source/models/builtin/llm/baichuan.rst
  doc/source/models/builtin/llm/chatglm.rst
  doc/source/models/builtin/llm/chatglm2-32k.rst
  doc/source/models/builtin/llm/chatglm2.rst
  doc/source/models/builtin/llm/falcon-instruct.rst
  doc/source/models/builtin/llm/falcon.rst
  doc/source/models/builtin/llm/glaive-coder.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internlm-20b.rst
  doc/source/models/builtin/llm/internlm-7b.rst
  doc/source/models/builtin/llm/internlm-chat-20b.rst
  doc/source/models/builtin/llm/internlm-chat-7b.rst
  doc/source/models/builtin/llm/internvl-chat.rst
  doc/source/models/builtin/llm/internvl2.rst
  doc/source/models/builtin/llm/llama-2-chat.rst
  doc/source/models/builtin/llm/llama-2.rst
  doc/source/models/builtin/llm/openbuddy.rst
  doc/source/models/builtin/llm/orca.rst
  doc/source/models/builtin/llm/qwen2-instruct.rst
  doc/source/models/builtin/llm/starchat-beta.rst
  doc/source/models/builtin/llm/starcoder.rst
  doc/source/models/builtin/llm/starcoderplus.rst
  doc/source/models/builtin/llm/vicuna-v1.3.rst
  doc/source/models/builtin/llm/vicuna-v1.5-16k.rst
  doc/source/models/builtin/llm/vicuna-v1.5.rst
  doc/source/models/builtin/llm/wizardlm-v1.0.rst
  doc/source/models/model_abilities/vision.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#2129 FEAT: [UI] Add other parameters to other models besides the LLM model.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#2137 FEAT: support SD3-medium inpainting
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/stable_diffusion/core.py
Labels: feature

#2104 ENH: make internvl2 support video
  xinference/core/chat_interface.py
  xinference/model/llm/transformers/intern_vl.py
Labels: enhancement

#2120 feat: 🎸 Added the model dtype parameter for embedding (currently only supported for models gte-Qwen2).
  xinference/model/embedding/core.py
Labels: feature

#2125 [Bug]: Fix concurrent ops in worker initialization
  xinference/core/worker.py
Labels: bug

#2147 Bug: fix audio ability errorwhen get instance info
  xinference/core/worker.py
  xinference/model/audio/core.py
Labels: bug

#2149 DOC: Add doc for fish speech and cogvlm2 video
  doc/source/models/builtin/audio/fishspeech-1.2-sft.rst
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/llm/cogvlm2-video-llama3-chat.rst
  doc/source/models/builtin/llm/index.rst
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: documentation

#2145 FEAT: Support LMDeploy for internvl2 and fix finish reasion miss at internvl stream
  xinference/core/model.py
  xinference/deploy/docker/Dockerfile
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/lmdeploy/__init__.py
  xinference/model/llm/lmdeploy/core.py
  xinference/model/llm/lmdeploy/tests/__init__.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2156 BUG: fix docker conflict
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: bug

#2165 ENH: support padding for sd inpainting model
  xinference/model/image/stable_diffusion/core.py
Labels: enhancement

#2166 ENH: Move matcha to third party
  setup.cfg
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/thirdparty/matcha/VERSION
  xinference/thirdparty/matcha/__init__.py
  xinference/thirdparty/matcha/app.py
  xinference/thirdparty/matcha/cli.py
  xinference/thirdparty/matcha/data/__init__.py
  xinference/thirdparty/matcha/data/components/__init__.py
  xinference/thirdparty/matcha/data/text_mel_datamodule.py
  xinference/thirdparty/matcha/hifigan/LICENSE
  xinference/thirdparty/matcha/hifigan/README.md
  xinference/thirdparty/matcha/hifigan/__init__.py
  xinference/thirdparty/matcha/hifigan/config.py
  xinference/thirdparty/matcha/hifigan/denoiser.py
  xinference/thirdparty/matcha/hifigan/env.py
  xinference/thirdparty/matcha/hifigan/meldataset.py
  xinference/thirdparty/matcha/hifigan/models.py
  xinference/thirdparty/matcha/hifigan/xutils.py
  xinference/thirdparty/matcha/models/__init__.py
  xinference/thirdparty/matcha/models/baselightningmodule.py
  xinference/thirdparty/matcha/models/components/__init__.py
  xinference/thirdparty/matcha/models/components/decoder.py
  xinference/thirdparty/matcha/models/components/flow_matching.py
  xinference/thirdparty/matcha/models/components/text_encoder.py
  xinference/thirdparty/matcha/models/components/transformer.py
  xinference/thirdparty/matcha/models/matcha_tts.py
  xinference/thirdparty/matcha/onnx/__init__.py
  xinference/thirdparty/matcha/onnx/export.py
  xinference/thirdparty/matcha/onnx/infer.py
  xinference/thirdparty/matcha/text/__init__.py
  xinference/thirdparty/matcha/text/cleaners.py
  xinference/thirdparty/matcha/text/numbers.py
  xinference/thirdparty/matcha/text/symbols.py
  xinference/thirdparty/matcha/train.py
  xinference/thirdparty/matcha/utils/__init__.py
  xinference/thirdparty/matcha/utils/audio.py
  xinference/thirdparty/matcha/utils/generate_data_statistics.py
  xinference/thirdparty/matcha/utils/get_durations_from_trained_model.py
  xinference/thirdparty/matcha/utils/instantiators.py
  xinference/thirdparty/matcha/utils/logging_utils.py
  xinference/thirdparty/matcha/utils/model.py
  xinference/thirdparty/matcha/utils/monotonic_align/__init__.py
  xinference/thirdparty/matcha/utils/monotonic_align/core.pyx
  xinference/thirdparty/matcha/utils/monotonic_align/setup.py
  xinference/thirdparty/matcha/utils/pylogger.py
  xinference/thirdparty/matcha/utils/rich_utils.py
  xinference/thirdparty/matcha/utils/utils.py
Labels: enhancement

#2172 ENH: Fix callback status when model die
  xinference/core/worker.py
Labels: enhancement

#2175 ENH: support cosyvoice-300m-instruct without instruction
  xinference/model/audio/chattts.py
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/tests/test_cosyvoice.py
  xinference/model/utils.py
Labels: enhancement

#2179 ENH: Remove opencc and fast_whisper
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/thirdparty/fish_speech/tools/api.py
Labels: enhancement

#2182 ENH: solve the problem of health check for image-to-text model
  xinference/model/llm/vllm/core.py
Labels: enhancement

#2185 BUG: 🐛 fix unable launch qwen2-embedding
  xinference/model/embedding/core.py
Labels: bug

#2188 BUG: configuration key different by sglang's version
  xinference/model/llm/sglang/core.py
Labels: bug

#2194 BUG: fix lora not load in transformers engine
  xinference/model/llm/transformers/core.py
Labels: bug

#2189 BUG: fix register model list error
  xinference/model/audio/custom.py
  xinference/model/embedding/custom.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/flexible/core.py
  xinference/model/image/custom.py
  xinference/model/llm/llm_family.py
  xinference/model/rerank/custom.py
  xinference/model/rerank/tests/test_rerank.py
Labels: bug

#2190 BUG: Fix list video model
  xinference/core/worker.py
  xinference/model/image/tests/test_stable_diffusion.py
Labels: bug

#2200 BUG: fix custom path test error
  xinference/model/image/tests/test_stable_diffusion.py
Labels: bug

#2197 FEAT: support CogVideoX-5b
  xinference/model/video/core.py
  xinference/model/video/diffusers.py
  xinference/model/video/model_spec.json
  xinference/model/video/model_spec_modelscope.json
Labels: feature
