Repository xorbitsai/inference, pull requests merged in 2025-02, with the labels that each got.

#2811 FEAT: support deepseek-r1-distill-llama
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/deepseek-r1-distill-llama.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/model_abilities/tools.rst
  doc/source/user_guide/backends.rst
  xinference/api/restful_api.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/mlx/core.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2817 DOC: Fix a couple of typos
  doc/source/models/model_abilities/multimodal.rst
  doc/source/models/model_abilities/rerank.rst
Labels: documentation

#2821 FEAT: vllm support for qwen2.5-vl-instruct
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/qwen2.5-vl-instruct.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/vllm/core.py
Labels: feature

#2822 BUG: Fix whisper CI
  xinference/model/audio/tests/test_whisper.py
Labels: bug

#2838 BLD: update sglang to v0.4.2.post4 and vllm to v0.7.2
  README.md
  README_zh_CN.md
  setup.cfg
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/requirements.txt
Labels: build

#2841 FEAT: Support qwen-2.5-instruct-1m
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2844 BLD: fix flashinfer installation in dockerfile
  xinference/deploy/docker/Dockerfile
Labels: build

#2852 enh: add gpu utilization info
  xinference/core/resource.py
  xinference/core/utils.py
  xinference/device_utils.py
Labels: enhancement, gpu

#2843 ENH: Update Kokoro model
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/kokoro.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/tests/test_kokoro.py
Labels: enhancement

#2864 FEAT: support deepseek-v3 and deepseek-r1
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/deepseek-r1.rst
  doc/source/models/builtin/llm/deepseek-v3.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#2876 FEAT: [UI] additional parameter tip function.
  xinference/web/ui/src/scenes/launch_model/components/addPair.js
  xinference/web/ui/src/scenes/launch_model/data/data.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#2871 FEAT: [UI] add featured models filtering function.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/LaunchModel.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/index.js
Labels: feature

#2883 TST: Pin CI transformers<4.49
  .github/workflows/python.yaml
Labels: testing

#2850 FEAT: [UI] support form parameters and command line conversion.
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/copyComponent/copyComponent.js
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/components/copyComponent.js
  xinference/web/ui/src/scenes/launch_model/components/drawer.js
  xinference/web/ui/src/scenes/launch_model/components/pasteDialog.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
Labels: feature

#2877 FEAT: support distributed inference for sglang
  xinference/core/model.py
  xinference/core/status_guard.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/llm/sglang/core.py
Labels: feature

#2889 FEAT: [UI] add n_worker parameter for model launch.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
  xinference/web/ui/src/scenes/launch_model/data/data.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#2897 BUG: fix FLUX when a scheduler is specified which is incompatible.
  xinference/model/image/stable_diffusion/core.py
Labels: bug

#2904 BUG: [UI] fix the bug of missing hint during model running.
  xinference/web/ui/src/scenes/running_models/index.js
Labels: bug

#2776 FEAT: InternVL 2.5
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/vllm/core.py
  xinference/thirdparty/internvl/conversation.py
Labels: feature

#2890 ENH: cmdline supports --n-worker, add --model-path and make it compatible with --model_path
  xinference/client/restful/restful_client.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
Labels: enhancement

#2908 DOC: distributed inference
  README.md
  README_zh_CN.md
  doc/source/_static/distributed_inference.png
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/distributed_inference.po
  doc/source/user_guide/backends.rst
  doc/source/user_guide/distributed_inference.rst
  doc/source/user_guide/index.rst
Labels: documentation

#2905 FEAT: support vllm reasoning content
  xinference/deploy/cmdline.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/reasoning_parsers/__init__.py
  xinference/model/llm/reasoning_parsers/abs_reasoning_parsers.py
  xinference/model/llm/reasoning_parsers/deepseek_r1_reasoning_parser.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
Labels: feature

#2911 TST: fix lint error
  xinference/model/llm/reasoning_parsers/abs_reasoning_parsers.py
  xinference/model/llm/reasoning_parsers/deepseek_r1_reasoning_parser.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/utils.py
Labels: testing

#2920 ENH: [UI] add copy button
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/running_models/index.js
Labels: enhancement

#2928 FEAT: Support qwen2.5-instruct-1m
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2944 BUG: fix qwen2.5-vl-7b cannot chat bug
  xinference/model/llm/tests/test_llm_model.py
  xinference/model/llm/vllm/core.py
Labels: bug

#2943 BUG: Fix modelscope model id on Qwen2.5-VL Added support for AWQ quantization format in Qwen2.5-VL
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#2946 BLD: Install ffmpeg 6 for audio & video models
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
Labels: build

#2962 BUG: fix Error while using Langchain-chatchat, because the parameter [max_tokens] passed is None
  xinference/model/llm/transformers/utils.py
Labels: bug

#2963 FEAT: Support moonlight-16b-a3b
  setup.cfg
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2779 FEAT: create_embedding add field model_replica
  xinference/api/restful_api.py
  xinference/core/tests/test_restful_api.py
  xinference/model/embedding/core.py
  xinference/types.py
Labels: feature
