Repository xorbitsai/inference, pull requests merged in 2025-01, with the labels that each got.

#2727 FEAT: support hunyuan-dit text2image
  doc/source/models/builtin/image/hunyuandit-v1.2-distilled.rst
  doc/source/models/builtin/image/hunyuandit-v1.2.rst
  doc/source/models/builtin/image/index.rst
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/video/model_spec_modelscope.json
Labels: feature

#2734 FEAT: support cline for vllm engine
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#1335 FEAT: [UI] theme switch
  xinference/web/ui/src/App.js
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/Title.js
  xinference/web/ui/src/components/themeButton.js
  xinference/web/ui/src/components/themeContext.js
  xinference/web/ui/src/theme.js
Labels: feature

#2741 FEAT: support qwen2vl run on ascend npu
  xinference/model/llm/transformers/qwen2_vl.py
Labels: feature

#2744 FEAT: [UI] Add language toggle for i18n support.
  xinference/web/ui/package-lock.json
  xinference/web/ui/package.json
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/hotkeyFocusTextField.js
  xinference/web/ui/src/components/translateButton.js
  xinference/web/ui/src/i18n.js
  xinference/web/ui/src/index.js
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/cluster_info/index.js
  xinference/web/ui/src/scenes/cluster_info/nodeInfo.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
  xinference/web/ui/src/scenes/register_model/components/addControlnet.js
  xinference/web/ui/src/scenes/register_model/components/addModelSpecs.js
  xinference/web/ui/src/scenes/register_model/components/addStop.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#2747 FIX: [UI] Resolve bug preventing '/' input in model_path.
  xinference/web/ui/src/components/hotkeyFocusTextField.js
  xinference/web/ui/src/scenes/launch_model/LaunchModelComponent.js
  xinference/web/ui/src/scenes/launch_model/launchCustom.js
  xinference/web/ui/src/scenes/launch_model/launchLLM.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#2746 ENH: [UI] Update Button Style and Interaction Logic for Editing Cache in Model Card.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement

#2748 FIX: [UI] Fix dark mode background bug.
  xinference/web/ui/src/scenes/register_model/components/addStop.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
Labels: bug

#2740 FEAT: Support cogagent-9b
  xinference/api/restful_api.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/cogagent.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: feature

#2738 ENH: Improve error message
  xinference/api/restful_api.py
  xinference/client/tests/test_client.py
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/worker.py
Labels: enhancement

#2752 BUG: pin mlx<0.22.0 to prevent qwen2_vl failing in mlx-vlm
  .github/workflows/python.yaml
  setup.cfg
Labels: bug

#2732 FEAT: Xavier: Share KV cache between VLLM replicas
  README.md
  README_zh_CN.md
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/vllm_enhancement.po
  doc/source/user_guide/index.rst
  doc/source/user_guide/vllm_enhancement.rst
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/tests/test_continuous_batching.py
  xinference/core/utils.py
  xinference/core/worker.py
  xinference/model/llm/vllm/core.py
  xinference/model/llm/vllm/xavier/__init__.py
  xinference/model/llm/vllm/xavier/allocator.py
  xinference/model/llm/vllm/xavier/block.py
  xinference/model/llm/vllm/xavier/block_manager.py
  xinference/model/llm/vllm/xavier/block_tracker.py
  xinference/model/llm/vllm/xavier/engine.py
  xinference/model/llm/vllm/xavier/executor.py
  xinference/model/llm/vllm/xavier/scheduler.py
  xinference/model/llm/vllm/xavier/test/__init__.py
  xinference/model/llm/vllm/xavier/test/test_xavier.py
  xinference/model/llm/vllm/xavier/transfer.py
Labels: feature

#2753 FEAT: [UI] Add gguf_quantization, gguf_model_path, and cpu_offload for image models.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#2749 FEAT: Support Marco-o1
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2755 ENH: add model config for Whisper
  xinference/model/audio/whisper.py
Labels: enhancement

#2761 DOC: update new models in README and doc
  README.md
  README_zh_CN.md
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/cogagent.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/marco-o1.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#2763 ENH: support cline style messages for all backend engines
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: enhancement

#2771 FIX: [UI] normalize language input to ensure consistent array format.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#2770 ENH: CosyVoice2 support SFT speakers
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/melotts.py
  xinference/model/audio/tests/test_cosyvoice.py
  xinference/thirdparty/cosyvoice/bin/spk2info.pt
Labels: enhancement

#2775 DOC: using discord instead of slack & updating model to qwen2.5 in getting started doc
  README.md
  README_zh_CN.md
  doc/source/conf.py
  doc/source/getting_started/using_xinference.rst
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/melotts-chinese.rst
  doc/source/models/builtin/audio/melotts-english-v2.rst
  doc/source/models/builtin/audio/melotts-english-v3.rst
  doc/source/models/builtin/audio/melotts-english.rst
  doc/source/models/builtin/audio/melotts-french.rst
  doc/source/models/builtin/audio/melotts-japanese.rst
  doc/source/models/builtin/audio/melotts-korean.rst
  doc/source/models/builtin/audio/melotts-spanish.rst
  doc/source/models/model_abilities/audio.rst
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/llm/memory.py
Labels: documentation

#2781 FEAT: support deepseek-r1-distill-qwen
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/deepseek-r1-distill-qwen.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/core/chat_interface.py
  xinference/deploy/docker/requirements.txt
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#2785 DOC: Update multimodal doc
  doc/source/index.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/audio.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/image.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/multimodal.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/tools.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/vision.po
  doc/source/locale/zh_CN/LC_MESSAGES/reference/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/models/builtin/audio/fishspeech-1.4.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen2-audio.rst
  doc/source/models/index.rst
  doc/source/models/model_abilities/index.rst
  doc/source/models/model_abilities/multimodal.rst
  doc/source/reference/index.rst
  xinference/client/handlers.py
  xinference/core/tests/test_restful_api.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/tests/test_multimodal.py
  xinference/model/llm/transformers/qwen2_audio.py
Labels: documentation

#2786 BUG: fix llama-cpp when some quantizations have multiple parts
  .github/workflows/python.yaml
  README.md
  README_zh_CN.md
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#2788 FEAT: support qwen2.5-vl-instruct
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen2.5-vl-instruct.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/qwen2_vl.py
Labels: feature

#2789 FEAT: Support internlm3
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature
