Repository xorbitsai/inference, pull requests merged in 2025-08, with the labels that each got.

#3882 FEAT: [model] support GLM-4.5 series
  doc/source/models/builtin/llm/codegeex4.rst
  doc/source/models/builtin/llm/cogagent.rst
  doc/source/models/builtin/llm/deepseek-v3-0324.rst
  doc/source/models/builtin/llm/glm-4.1v-thinking.rst
  doc/source/models/builtin/llm/glm-4.5.rst
  doc/source/models/builtin/llm/glm-4v.rst
  doc/source/models/builtin/llm/glm-edge-chat.rst
  doc/source/models/builtin/llm/glm4-0414.rst
  doc/source/models/builtin/llm/glm4-chat-1m.rst
  doc/source/models/builtin/llm/glm4-chat.rst
  doc/source/models/builtin/llm/index.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3887 ENH: Add context length limits and automatic truncation features to vLLM embedding models.
  doc/source/development/contributing_environment.rst
  xinference/model/embedding/vllm/core.py
  xinference/model/embedding/vllm/tests/test_vllm_embedding.py
Labels: enhancement

#3888 FEAT: Support Qwen3-Thinking
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3889 FEAT: Support Qwen3-Coder
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen3-coder.rst
  doc/source/models/builtin/llm/qwen3-instruct.rst
  doc/source/models/builtin/llm/qwen3-thinking.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3891 BUG: fix version checks for vllm
  doc/source/getting_started/using_xinference.rst
  doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_xinference.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/launch.po
  doc/source/models/virtualenv.rst
  doc/source/user_guide/launch.rst
  xinference/model/llm/vllm/core.py
Labels: bug

#3318 BLD: upgrade base image for dockerfile
  .github/workflows/docker-cd.yaml
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/Dockerfile.cpu
  xinference/deploy/docker/Dockerfile.cu128
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements/requirements-base.txt
  xinference/deploy/docker/requirements/requirements-ml.txt
  xinference/deploy/docker/requirements/requirements-models.txt
  xinference/deploy/docker/requirements_12.8/requirements-base.txt
  xinference/deploy/docker/requirements_12.8/requirements-ml.txt
  xinference/deploy/docker/requirements_12.8/requirements-models.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/deploy/docker/requirements_cpu/requirements_cpu-base.txt
  xinference/deploy/docker/requirements_cpu/requirements_cpu-ml.txt
  xinference/deploy/docker/requirements_cpu/requirements_cpu-models.txt
Labels: build

#3892 BLD: change dokcer build time to 240 minutes to pass 12.8 build
  .github/workflows/docker-cd.yaml
Labels: build

#3893 BLD：fix docker build for cu128
  .github/workflows/docker-cd.yaml
  xinference/deploy/docker/Dockerfile.cu128
Labels: gpu

#3895 BLD：fix cu128 build
  .github/workflows/docker-cd.yaml
Labels: gpu

#3900 ENH: Add qwen3 new model to tool call list
  xinference/model/llm/llm_family.json
  xinference/model/llm/utils.py
Labels: enhancement

#3862 DOC: Update xllamacpp doc
  doc/source/_static/xllamacpp_param.png
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
Labels: documentation

#3924 FEAT: [model] gpt-oss
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/gpt-oss.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
  xinference/ui/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#3939 feat: sglang support streaming function call
  xinference/api/restful_api.py
  xinference/core/model.py
  xinference/model/llm/sglang/core.py
Labels: feature

#3956 ENH: clean embedding model cache when using vllm engine
  xinference/model/embedding/vllm/core.py
  xinference/model/llm/tests/test_harmony.py
  xinference/model/llm/transformers/multimodal/core.py
  xinference/model/llm/transformers/utils.py
  xinference/model/utils.py
Labels: enhancement

#3977 BUG: fix rerank model creation
  xinference/model/rerank/core.py
  xinference/model/rerank/sentence_transformers/core.py
Labels: bug

#3996 FEAT: Wan 2.2
  doc/source/models/builtin/video/index.rst
  doc/source/models/builtin/video/wan2.2-a14b.rst
  doc/source/models/builtin/video/wan2.2-i2v-a14b.rst
  doc/source/models/builtin/video/wan2.2-ti2v-5b.rst
  xinference/model/video/model_spec.json
Labels: feature

#4003 DOC: add setting limitation of images for multi modal doc
  doc/source/_static/limit_mm_per_prompt.png
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/multimodal.po
  doc/source/models/model_abilities/multimodal.rst
Labels: documentation

#4015 ENH: Update the environment dependencies for cosyvoice2
  xinference/model/audio/model_spec.json
Labels: enhancement, gpu

#4014 FEAT: image2image and inpainting for qwen-image
  doc/source/gen_docs.py
  doc/source/models/builtin/image/qwen-image-edit.rst
  doc/source/models/builtin/image/qwen-image.rst
  doc/source/models/builtin/llm/kat-v1.rst
  doc/source/models/model_abilities/image.rst
  doc/templates/image.rst.jinja
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
  xinference/model/video/model_spec.json
  xinference/ui/gradio/media_interface.py
Labels: feature

#4000 FEAT: Support Custom vllm embedding dim
  xinference/model/embedding/vllm/core.py
  xinference/model/embedding/vllm/tests/test_vllm_embedding.py
  xinference/model/rerank/vllm/core.py
Labels: feature

#3965 FEAT: [embedding] support `dimensions` for embedding
  xinference/model/embedding/flag/core.py
  xinference/model/embedding/llama_cpp/core.py
  xinference/model/embedding/sentence_transformers/core.py
  xinference/model/embedding/sentence_transformers/tests/test_sentence_transformers.py
Labels: feature

#4002 BLD: fix CI failures
  .github/workflows/python.yaml
  xinference/core/model.py
  xinference/deploy/cmdline.py
  xinference/deploy/test/test_cmdline.py
  xinference/model/audio/tests/test_whisper.py
  xinference/model/embedding/vllm/tests/test_vllm_embedding.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/image/tests/test_got_ocr2.py
  xinference/model/image/tests/test_stable_diffusion.py
  xinference/model/llm/transformers/core.py
  xinference/model/tests/test_utils.py
Labels: build

#3988 ENH: support chat_template_kwargs for llama.cpp
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.json
  xinference/ui/gradio/chat_interface.py
Labels: enhancement

#4022 FEAT: [Model] Support DeepSeek-V3.1 Quantization and tool
  xinference/model/llm/llm_family.json
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#4020 FEAT: Seed-OSS-36B
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature
