Repository xorbitsai/inference, pull requests merged in 2025-05, with the labels that each got.

#3366 ENH: Qwen/Qwen2.5-Omni-3B
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#3375 BUG: fix qwen3 235b spec
  doc/source/models/builtin/llm/qwen3.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#3352 FEAT: [MODEL]XiYanSQL-QwenCoder-2504
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature, new model

#3353 FEAT: [Model]HuatuoGPT-o1
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature, new model

#3343 FEAT: [Model]DianJin-R1
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature, new model

#3380 ENH: Update the activated_steze_In_billions parameter in the deepseek-vl2 model
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#3397 BLD: isolate autoawq and GPTQModel into separate extra install
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  setup.cfg
  xinference/deploy/docker/requirements-ml.txt
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu-ml.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: build

#3394 BUG: fix the processing logic for inference content parsing and tool calls
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#3405 ENH: add mlx-community/Qwen2.5-VL-32B-Instruct
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#3386 FEAT: support image_to_video
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/video.po
  doc/source/models/builtin/video/index.rst
  doc/source/models/builtin/video/wan2.1-i2v-14b-480p.rst
  doc/source/models/builtin/video/wan2.1-i2v-14b-720p.rst
  doc/source/models/model_abilities/video.rst
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/model.py
  xinference/model/video/diffusers.py
  xinference/model/video/model_spec.json
  xinference/model/video/model_spec_modelscope.json
Labels: feature

#3414 BUG: fix stop word handling logic in vllm model generation configuration
  xinference/model/llm/vllm/core.py
Labels: bug

#3417 BUG: fix Model._get_full_prompt() takes 3 positional arguments but 4 were given
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/glm4v.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/qwen_vl.py
Labels: bug

#3411 ENH: [UI] add a documentation link button in side menu
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
Labels: enhancement

#3408 ENH: QwQ use unsloth gguf
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#3422 FEAT: Qwen3-235B-A22B GPTQ Quantization Int4 Int8
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#3412 ENH: llama.cpp backend use xllamacpp
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/workflows/python.yaml
  setup.cfg
  xinference/client/restful/restful_client.py
  xinference/core/tests/test_types.py
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/__init__.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/types.py
Labels: enhancement

#3423 ENH: [UI] display version info in side menu
  xinference/web/ui/src/components/MenuSide.js
  xinference/web/ui/src/components/versionLabel.js
Labels: enhancement

#3362 ENH: Worker env isolation
  doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po
  doc/source/models/virtualenv.rst
  setup.cfg
  xinference/core/worker.py
  xinference/deploy/docker/requirements-base.txt
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu-base.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/deploy/utils.py
  xinference/model/llm/transformers/qwen-omni.py
  xinference/model/llm/vllm/tests/test_distributed_executor.py
  xinference/model/llm/vllm/xavier/test/test_xavier.py
Labels: enhancement

#3434 BUG: fix potential stop hang
  xinference/core/model.py
Labels: bug

#3439 FEAT: use xo.wait_for instead of asyncio.wait_for for actor call
  setup.cfg
  xinference/core/model.py
  xinference/core/worker.py
  xinference/deploy/docker/requirements-base.txt
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu-base.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: feature

#3436 ENH: Use Qwen's official quantitative model repository
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: enhancement

#3431 BLD: pin transformers version at 4.51.3
  xinference/deploy/docker/Dockerfile
Labels: build

#3428 REF: support loading model config in function
  xinference/model/audio/__init__.py
  xinference/model/embedding/__init__.py
  xinference/model/image/__init__.py
  xinference/model/llm/__init__.py
  xinference/model/rerank/__init__.py
  xinference/model/video/__init__.py
Labels: refactor

#3448 FEAT: video UI
  xinference/api/restful_api.py
  xinference/core/media_interface.py
  xinference/core/model.py
  xinference/model/video/core.py
  xinference/model/video/diffusers.py
  xinference/model/video/tests/test_diffusers_video.py
  xinference/web/ui/src/scenes/running_models/index.js
Labels: feature

#3456 FEAT: auto add <think> tag when it is missed
  xinference/model/llm/core.py
  xinference/model/llm/reasoning_parser.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3365 ENH: Update cosyvoice
  doc/source/models/model_abilities/audio.rst
  setup.cfg
  xinference/core/model.py
  xinference/deploy/docker/requirements-base.txt
  xinference/deploy/docker/requirements-ml.txt
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu-base.txt
  xinference/deploy/docker/requirements_cpu-models.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/tests/test_cosyvoice.py
  xinference/thirdparty/cosyvoice/bin/average_model.py
  xinference/thirdparty/cosyvoice/bin/export_jit.py
  xinference/thirdparty/cosyvoice/bin/export_onnx.py
  xinference/thirdparty/cosyvoice/bin/export_trt.sh
  xinference/thirdparty/cosyvoice/bin/inference.py
  xinference/thirdparty/cosyvoice/bin/train.py
  xinference/thirdparty/cosyvoice/cli/cosyvoice.py
  xinference/thirdparty/cosyvoice/cli/frontend.py
  xinference/thirdparty/cosyvoice/cli/model.py
  xinference/thirdparty/cosyvoice/dataset/processor.py
  xinference/thirdparty/cosyvoice/flow/decoder.py
  xinference/thirdparty/cosyvoice/flow/flow.py
  xinference/thirdparty/cosyvoice/flow/flow_matching.py
  xinference/thirdparty/cosyvoice/flow/length_regulator.py
  xinference/thirdparty/cosyvoice/hifigan/discriminator.py
  xinference/thirdparty/cosyvoice/hifigan/f0_predictor.py
  xinference/thirdparty/cosyvoice/hifigan/generator.py
  xinference/thirdparty/cosyvoice/hifigan/hifigan.py
  xinference/thirdparty/cosyvoice/llm/llm.py
  xinference/thirdparty/cosyvoice/transformer/embedding.py
  xinference/thirdparty/cosyvoice/transformer/upsample_encoder.py
  xinference/thirdparty/cosyvoice/utils/class_utils.py
  xinference/thirdparty/cosyvoice/utils/common.py
  xinference/thirdparty/cosyvoice/utils/file_utils.py
  xinference/thirdparty/cosyvoice/utils/frontend_utils.py
  xinference/thirdparty/cosyvoice/utils/mask.py
  xinference/thirdparty/cosyvoice/utils/train_utils.py
  xinference/thirdparty/matcha/hifigan/xutils.py
Labels: enhancement

#3447 FEAT: Support Skywork-OR1
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3461 BUG: [UI] Added cpu_offload parameter to video model and fixed bug in audio model's filtering function.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/LaunchModel.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#3464 FEAT: Support Skywork-OR1 gptq for 32B
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#3467 BLD: fix setup.cfg
  doc/source/models/builtin/audio/cosyvoice2-0.5b.rst
  doc/source/models/builtin/llm/dianjin-r1.rst
  doc/source/models/builtin/llm/huatuogpt-o1-llama-3.1.rst
  doc/source/models/builtin/llm/huatuogpt-o1-qwen2.5.rst
  doc/source/models/builtin/llm/skywork-or1.rst
  doc/source/models/builtin/llm/xiyansql-qwencoder-2504.rst
  setup.cfg
Labels: build

#3440 BUG: fix input for jina clip
  xinference/model/embedding/core.py
Labels: bug

#3482 BUG: [ui] delete cache file white screen bug.
  xinference/web/ui/src/scenes/launch_model/LaunchModel.js
Labels: bug

#3453 ENH: [rerank] add instruction for minicpm-reranker
  xinference/model/rerank/core.py
  xinference/model/rerank/utils.py
Labels: enhancement

#3442 FEAT: llama.cpp backend support multimodal
  .github/workflows/python.yaml
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
  setup.cfg
  xinference/client/restful/restful_client.py
  xinference/client/tests/test_client.py
  xinference/conftest.py
  xinference/core/tests/test_restful_api.py
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/__init__.py
  xinference/model/llm/core.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llama_cpp/tests/test_gguf.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/tests/test_llm_family.py
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/data/data.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#3516 ENH: pass extra arguments for speech2text API.
  xinference/core/model.py
Labels: enhancement

#3521 FEAT: [UI] add hint for common parameters with support for custom input.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/components/addPair.js
Labels: feature

#3534 ENH: add modelscope support for kolors
  xinference/core/media_interface.py
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
Labels: enhancement

#3536 FEAT: add some other paraformer series models
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
Labels: feature

#3527 ENH: remove check when specified GPU index for vllm
  xinference/core/tests/test_worker.py
  xinference/core/worker.py
Labels: enhancement, gpu

#3538 ENH: Supports `HybridCache` in `transformers` lib, mainly for `gemma3` chat model
  xinference/core/scheduler.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/gemma3.py
  xinference/model/llm/transformers/utils.py
Labels: enhancement

#3541 ENH: support virtualenv for chattts
  xinference/core/media_interface.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
Labels: enhancement

#3552 FEAT: support deepseek-r1-0528-qwen3
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/deepseek-r1-0528-qwen3.rst
  doc/source/models/builtin/llm/deepseek-r1-0528.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/qwen-vl-chat.rst
  doc/source/user_guide/backends.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: feature
