Repository xorbitsai/inference, pull requests merged in 2025-06, with the labels that each got.

#3557 FEAT: support CogView4 image model
  doc/source/locale/zh_CN/LC_MESSAGES/models/model_abilities/image.po
  doc/source/models/builtin/image/cogview4.rst
  doc/source/models/builtin/image/index.rst
  doc/source/models/model_abilities/image.rst
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/image/stable_diffusion/core.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#3563 FEAT: [UI] support model_ability filter for image and video models.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/LaunchModel.js
Labels: feature

#3565 DOC: update links
  README.md
  README_ja_JP.md
  README_zh_CN.md
  doc/source/conf.py
Labels: documentation

#3587 FEAT: SeACoParaformer model
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
Labels: feature

#3589 BUG: Fix cmdline
  xinference/deploy/cmdline.py
Labels: bug

#3606 ENH: Support pcm response_format
  xinference/model/audio/chattts.py
  xinference/model/audio/cosyvoice.py
  xinference/model/audio/tests/test_chattts.py
  xinference/model/audio/tests/test_cosyvoice.py
  xinference/model/audio/utils.py
Labels: enhancement

#3609 FEAT:support MiniCPM4 Series
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3608 BUG: [UI] fixed the mobile language switching bug.
  xinference/web/ui/src/components/translateButton.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
Labels: bug

#3617 FEAT: [UI] add model_engine parameter to embedding model.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/ja.json
  xinference/web/ui/src/locales/ko.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#3622 FEAT: add kwargs for transripts client API
  xinference/client/restful/restful_client.py
Labels: feature

#3615 FEAT: support qwen3 embedding
  .github/workflows/python.yaml
  xinference/model/embedding/__init__.py
  xinference/model/embedding/core.py
  xinference/model/embedding/embed_family.py
  xinference/model/embedding/flag/core.py
  xinference/model/embedding/model_spec.json
  xinference/model/embedding/model_spec_modelscope.json
  xinference/model/embedding/sentence_transformers/core.py
  xinference/model/embedding/tests/test_embedding_models.py
  xinference/model/embedding/vllm/__init__.py
  xinference/model/embedding/vllm/core.py
  xinference/model/embedding/vllm/tests/__init__.py
  xinference/model/embedding/vllm/tests/test_vllm_embedding.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#3627 FEAT: support qwen3-reranker
  xinference/model/rerank/core.py
  xinference/model/rerank/model_spec.json
  xinference/model/rerank/model_spec_modelscope.json
  xinference/model/rerank/utils.py
Labels: feature

#3628 DOC: update models
  README.md
  README_zh_CN.md
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/seaco-paraformer-zh.rst
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/embedding/qwen3-embedding-0.6b.rst
  doc/source/models/builtin/embedding/qwen3-embedding-4b.rst
  doc/source/models/builtin/embedding/qwen3-embedding-8b.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/minicpm4.rst
  doc/source/models/builtin/rerank/index.rst
  doc/source/models/builtin/rerank/qwen3-reranker-0.6b.rst
  doc/source/models/builtin/rerank/qwen3-reranker-4b.rst
  doc/source/models/builtin/rerank/qwen3-reranker-8b.rst
Labels: documentation

#3630 BUG: fix qwen3-rerank to create model on GPU
  xinference/model/rerank/core.py
Labels: bug, gpu

#3640 ENH: add `enable_flash_attn` param for loading qwen3 embedding & rerank
  xinference/model/embedding/sentence_transformers/core.py
  xinference/model/rerank/core.py
Labels: enhancement

#3658 ENH: add more abilities for builtin model families API
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
Labels: enhancement

#3656 FEAT: [UI] enhance audio & rerank model registration params.
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
Labels: feature

#3664 REF: remove unused code
  xinference/client/common.py
Labels: refactor

#3669 BLD: pin flash-attn & flashinfer-python version and limit sgl-kernel version
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/requirements-ml.txt
Labels: build

#3642 ENH: improve local cluster startup reliability via child-process readiness signaling
  xinference/deploy/local.py
Labels: enhancement

#3677 BUG: fix custom embedding
  xinference/model/embedding/__init__.py
  xinference/model/embedding/custom.py
  xinference/model/embedding/embed_family.py
Labels: bug

#3680 ENH: FishSpeech support pcm
  xinference/model/audio/fish_speech.py
  xinference/model/audio/tests/test_fish_speech.py
  xinference/model/audio/utils.py
Labels: enhancement

#3685 BUG: [UI] rename the command-line argument from download-hub to download_hub.
  xinference/web/ui/src/scenes/launch_model/components/copyComponent.js
Labels: bug

#3702 FEAT: [UI] model registration supports packages.
  xinference/core/worker.py
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/ja.json
  xinference/web/ui/src/locales/ko.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/register_model/components/addVirtualenv.js
  xinference/web/ui/src/scenes/register_model/index.js
  xinference/web/ui/src/scenes/register_model/registerModel.js
Labels: feature

#3693 FEAT: support MLU device
  xinference/deploy/worker.py
  xinference/device_utils.py
  xinference/model/llm/core.py
Labels: feature

#3695 BLD: Update Dockerfile
  xinference/deploy/docker/Dockerfile
Labels: build

#3718 BUG: fix `<think>` wrongly added when set `chat_template_kwargs {"enable_thinking": False}`
  .github/workflows/python.yaml
  README_zh_CN.md
  setup.cfg
  xinference/model/llm/core.py
  xinference/model/llm/mlx/core.py
  xinference/model/llm/reasoning_parser.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/multimodal/cogagent.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#3743 BLD: pin transformers version at 4.52.4 to fix "Failed to import module 'SentenceTransformer'" error
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/using_docker_image.po
  xinference/deploy/docker/requirements-ml.txt
  xinference/deploy/docker/requirements_cpu-ml.txt
Labels: build
