Repository xorbitsai/inference, pull requests merged in 2025-03, with the labels that each got.

#2971 BLD: fix ffprobe library not imported
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
Labels: build

#2974 BUG: using jina-clip-v2, no attribute error when only text of image pass in
  xinference/model/embedding/core.py
Labels: bug

#2980 FEAT: [UI] add the reasoning_content parameter.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/LaunchModel.js
  xinference/web/ui/src/scenes/launch_model/components/pasteDialog.js
  xinference/web/ui/src/scenes/launch_model/data/data.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#2986 ENH: [UI] add model ability filtering feature to the audio model.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/LaunchModel.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: enhancement

#2993 BUG: fix compatibility of mlx-lm v0.21.5
  setup.cfg
  xinference/model/llm/mlx/core.py
Labels: bug

#2992 BUG: Fix tokenizer error in create_embedding
  xinference/model/embedding/core.py
Labels: bug

#2991 BUG: wrong kwargs passing to encode method when using jina-clip-v2
  xinference/model/embedding/core.py
Labels: bug

#3005 FEAT: Support QwQ-32B
  doc/source/getting_started/installation.rst
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3008 REF: [UI] move featureModels to data.js
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/web/ui/src/scenes/launch_model/data/data.js
  xinference/web/ui/src/scenes/launch_model/index.js
Labels: refactor

#3014 BUG: [UI] fix the white screen bug.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#3015 BLD: fix docker requirements for sglang
  xinference/deploy/docker/requirements.txt
  xinference/model/llm/llm_family_modelscope.json
Labels: build

#2997 ENH: Support xllamacpp
  .github/workflows/python.yaml
  setup.cfg
  xinference/client/tests/test_client.py
  xinference/conftest.py
  xinference/core/model.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/model/llm/__init__.py
  xinference/model/llm/llama_cpp/core.py
  xinference/types.py
Labels: enhancement

#3018 DOC: added new models
  README.md
  README_zh_CN.md
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internvl2.5-mpo.rst
  doc/source/models/builtin/llm/internvl2.5.rst
  doc/source/models/builtin/llm/moonlight-16b-a3b-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-instruct-1m.rst
  doc/source/models/builtin/llm/qwq-32b.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#3024 BUG: Fix reasoning content parser for qwq-32b
  xinference/core/chat_interface.py
  xinference/model/llm/core.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/reasoning_parser.py
  xinference/model/llm/reasoning_parsers/__init__.py
  xinference/model/llm/reasoning_parsers/abs_reasoning_parsers.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#3031 BUG: Failed to download model 'QwQ-32B' (size: 32, format: ggufv2) after multiple retries
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#3028 BUG: [UI] fix dark mode bugs.
  xinference/web/ui/src/scenes/launch_model/components/pasteDialog.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
  xinference/web/ui/src/scenes/register_model/registerModel.js
  xinference/web/ui/src/scenes/register_model/styles/registerModelStyle.css
Labels: bug

#3050 FIX: [UI] remove the restriction of model_format on n_gpu for llama.cpp
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug, gpu

#3053 ENH: xllamacpp backend raise exception if failed
  xinference/model/llm/llama_cpp/core.py
Labels: enhancement

#3072 BUG: fix max_tokens for MLX VL models.
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/tests/test_mlx.py
Labels: bug

#3078 ENH: [UI] change 'GPU Count' to 'GPU Count per Replica'.
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
Labels: enhancement, gpu

#3081 BUG:fix vLLM parameter "enable_prefix_caching"
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: bug

#3065 DOC: add auth usage guide for http request
  doc/source/user_guide/auth_system.rst
Labels: documentation

#3088 DOC: add xllamacpp related docs
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/auth_system.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/user_guide/backends.rst
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: documentation

#3090 BUG: fix first token error and support deepseek stream api
  xinference/core/chat_interface.py
  xinference/model/llm/reasoning_parser.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: bug

#3103 FEAT: add deepseek v3 function calling
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/mlx/core.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3116 FEAT: Support Fin-R1 model
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3120 FEAT: distributed inference for vLLM
  .github/workflows/python.yaml
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/model/llm/core.py
  xinference/model/llm/vllm/core.py
  xinference/model/llm/vllm/distributed_executor.py
  xinference/model/llm/vllm/tests/__init__.py
  xinference/model/llm/vllm/tests/test_distributed_executor.py
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#3131 BUG: Fix PyTorch TypeError: Make _ModelWrapper Inherit from nn.Module
  xinference/model/rerank/core.py
Labels: bug

#3146 DOC: update models
  README.md
  README_zh_CN.md
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/fin-r1.rst
  doc/source/models/builtin/llm/gemma-3-1b-it.rst
  doc/source/models/builtin/llm/gemma-3-it.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/user_guide/backends.rst
  xinference/deploy/docker/requirements.txt
Labels: documentation

#3147 BLD: use gptqmodel to replace auto-gptq
  setup.cfg
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: build

#3149 ENH: sglang supports gptq int8 quantization now
  xinference/model/llm/sglang/core.py
Labels: enhancement

#3157 FEAT: Support gptq(int4, int8) and fp8 for Fin-R1 model
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#3115 BUG: fix llm stream response
  xinference/client/tests/test_client.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/reasoning_parser.py
  xinference/model/llm/utils.py
Labels: bug
