Repository xorbitsai/inference, pull requests merged in 2025-04, with the labels that each got.

#3159 feat: fix the quantization parameter in the vLLM engine cannot work
  xinference/model/llm/vllm/core.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#3166 ENH: Add validation of n_worker
  xinference/core/supervisor.py
Labels: enhancement

#3164 BLD: resolve docker fail
  xinference/deploy/docker/requirements.txt
Labels: build

#3168 FEAT: support max_completion_tokens
  xinference/_compat.py
  xinference/api/restful_api.py
Labels: feature

#3180 BUG: prevent potential stop hang for distributed vllm inference
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/distributed_inference.po
  doc/source/user_guide/distributed_inference.rst
  xinference/core/worker.py
  xinference/model/llm/vllm/core.py
Labels: bug

#3181 ENH: Compatible with latest xllamacpp
  xinference/model/llm/llama_cpp/core.py
Labels: enhancement

#3195 BLD: fix compatibility for mlx-lm>=0.22.3
  xinference/model/llm/mlx/core.py
Labels: build

#3197 BLD: upgrade gradio version for docker
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: build

#3191 REF: simplify transformers model registration with decorators.
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/transformers/__init__.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/transformers/qwen2_vl.py
Labels: refactor

#3202 BUG: fix stop hang for vllm engine
  xinference/model/llm/vllm/distributed_executor.py
Labels: bug

#3207 BLD: fix docker build
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: build

#3212 BLD: remove setuptools limitation in project.toml
  pyproject.toml
Labels: build

#3232 BUG: Fix qwq gguf model path
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: bug

#3224 FEAT: Support megatts3
  .github/workflows/python.yaml
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/core.py
  xinference/model/audio/megatts.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/audio/tests/bbc_news.npy
  xinference/model/audio/tests/bbc_news.wav
  xinference/model/audio/tests/test_megatts.py
  xinference/thirdparty/megatts3/__init__.py
  xinference/thirdparty/megatts3/tts/frontend_function.py
  xinference/thirdparty/megatts3/tts/gradio_api.py
  xinference/thirdparty/megatts3/tts/infer_cli.py
  xinference/thirdparty/megatts3/tts/modules/aligner/whisper_small.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/ar_dur_predictor.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/commons/layers.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/commons/nar_tts_modules.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/commons/rel_transformer.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/commons/rot_transformer.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/commons/seq_utils.py
  xinference/thirdparty/megatts3/tts/modules/ar_dur/commons/transformer.py
  xinference/thirdparty/megatts3/tts/modules/llm_dit/cfm.py
  xinference/thirdparty/megatts3/tts/modules/llm_dit/dit.py
  xinference/thirdparty/megatts3/tts/modules/llm_dit/time_embedding.py
  xinference/thirdparty/megatts3/tts/modules/llm_dit/transformer.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/decoder/diag_gaussian.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/decoder/hifigan_modules.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/decoder/seanet_encoder.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/decoder/wavvae_v3.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/encoder/common_modules/conv.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/encoder/common_modules/lstm.py
  xinference/thirdparty/megatts3/tts/modules/wavvae/encoder/common_modules/seanet.py
  xinference/thirdparty/megatts3/tts/utils/audio_utils/align.py
  xinference/thirdparty/megatts3/tts/utils/audio_utils/io.py
  xinference/thirdparty/megatts3/tts/utils/audio_utils/plot.py
  xinference/thirdparty/megatts3/tts/utils/commons/ckpt_utils.py
  xinference/thirdparty/megatts3/tts/utils/commons/hparams.py
  xinference/thirdparty/megatts3/tts/utils/text_utils/dict.json
  xinference/thirdparty/megatts3/tts/utils/text_utils/ph_tone_convert.py
  xinference/thirdparty/megatts3/tts/utils/text_utils/split_text.py
  xinference/thirdparty/megatts3/tts/utils/text_utils/text_encoder.py
Labels: feature

#3235 FEAT: InternVL3
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3236 FEAT: support paraformer-zh
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
Labels: feature

#3248 FEAT:support SeaLLMs-v3
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3233 FEAT: support getting download progress and cancel download
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/core/progress_tracker.py
  xinference/core/supervisor.py
  xinference/core/tests/test_restful_api.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/model/tests/__init__.py
  xinference/model/tests/test_utils.py
  xinference/model/utils.py
  xinference/utils.py
Labels: feature

#3245 FEAT: add thinking process in gradio chat interface
  xinference/core/chat_interface.py
Labels: feature

#3242 FEAT: support min/max_pixels params for vision model
  xinference/model/llm/transformers/gemma3.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/qwen2_vl.py
  xinference/model/llm/vllm/core.py
  xinference/types.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#3261 BUG: Fix llama cpp backend load model with multiple parts
  xinference/model/llm/llama_cpp/core.py
Labels: bug

#3265 ENH: update gradio interface for chat model
  xinference/core/chat_interface.py
Labels: enhancement

#3274 FEAT: support skywork-or1-preview
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3278 ENH: Set gradio default concurrency to cpu count
  xinference/core/chat_interface.py
Labels: enhancement

#3276 FEAT: [UI] progress bar and functionality to cancel model launch.
  setup.cfg
  xinference/api/restful_api.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/utils.py
  xinference/web/ui/src/components/apiContext.js
  xinference/web/ui/src/components/successMessageSnackBar.js
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/components/progress.js
  xinference/web/ui/src/scenes/launch_model/index.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
Labels: feature

#3241 FEAT: Support virtualenv for models
  setup.cfg
  xinference/constants.py
  xinference/core/model.py
  xinference/core/worker.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/audio/core.py
  xinference/model/core.py
  xinference/model/embedding/core.py
  xinference/model/flexible/core.py
  xinference/model/image/core.py
  xinference/model/image/model_spec.json
  xinference/model/image/model_spec_modelscope.json
  xinference/model/llm/core.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/rerank/core.py
  xinference/model/video/core.py
  xinference/utils.py
Labels: feature

#3279 FEAT: support qwen2.5-omni
  setup.cfg
  xinference/core/chat_interface.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/qwen-omni.py
  xinference/model/llm/transformers/qwen2_audio.py
  xinference/model/llm/utils.py
  xinference/types.py
Labels: feature

#3287 DOC: add doc about virtual env & update models in README
  README.md
  README_zh_CN.md
  doc/source/getting_started/environments.rst
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/index.po
  doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po
  doc/source/locale/zh_CN/LC_MESSAGES/user_guide/backends.po
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/megatts3.rst
  doc/source/models/builtin/audio/paraformer-zh.rst
  doc/source/models/builtin/llm/deepseek-vl2.rst
  doc/source/models/builtin/llm/glm4-0414.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/internvl3.rst
  doc/source/models/builtin/llm/qwen2.5-omni.rst
  doc/source/models/builtin/llm/seallms-v3.rst
  doc/source/models/builtin/llm/skywork-or1-preview.rst
  doc/source/models/index.rst
  doc/source/models/virtualenv.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#3289 BLD: fix docker build
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/requirements-apps.txt
  xinference/deploy/docker/requirements-base.txt
  xinference/deploy/docker/requirements-ml.txt
Labels: build

#3296 BLD: fix cpu docker build
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/cpu.Dockerfile
  xinference/deploy/docker/requirements-models.txt
  xinference/deploy/docker/requirements_cpu-base.txt
  xinference/deploy/docker/requirements_cpu-ml.txt
  xinference/deploy/docker/requirements_cpu-models.txt
Labels: build

#3294 DOC: small fixes for doc
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po
  doc/source/models/builtin/llm/internvl3.rst
  doc/source/models/builtin/llm/seallms-v3.rst
  doc/source/models/builtin/llm/skywork-or1-preview.rst
  doc/source/models/virtualenv.rst
  doc/source/user_guide/backends.rst
  setup.cfg
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: documentation

#3297 FEAT: Wan 2.1 text2video
  doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po
  doc/source/models/builtin/video/index.rst
  doc/source/models/builtin/video/wan2.1-1.3b.rst
  doc/source/models/builtin/video/wan2.1-14b.rst
  doc/source/models/virtualenv.rst
  xinference/model/video/diffusers.py
  xinference/model/video/model_spec.json
  xinference/model/video/model_spec_modelscope.json
Labels: feature

#3301 BUG: [UI] fix the bug in the cancellation function.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: bug

#3304 BUG: fix gemma-3-it max_tokens
  xinference/model/llm/transformers/gemma3.py
Labels: bug

#3305 BUG: fix potential progress error
  xinference/core/supervisor.py
Labels: bug

#3311 BLD: support flash-attn at Dockerfile
  xinference/deploy/docker/Dockerfile
Labels: build

#3313 ENH: support setting sse ping attempts
  xinference/api/restful_api.py
  xinference/constants.py
Labels: enhancement

#3306 FEAT: [UI] highlight the input box content.
  xinference/web/ui/src/scenes/launch_model/components/addPair.js
  xinference/web/ui/src/scenes/launch_model/components/progress.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
  xinference/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
Labels: feature

#3308 FEAT: [UI] display the model_ability parameter.
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: feature

#3326 BUG: fix sglang chat
  xinference/constants.py
  xinference/model/llm/sglang/core.py
Labels: bug

#3331 BUG: Show engine options on UI even if the specific engine is not installed
  xinference/model/llm/core.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/lmdeploy/core.py
  xinference/model/llm/mlx/core.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/cogagent.py
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/cogvlm2_video.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/deepseek_v2.py
  xinference/model/llm/transformers/deepseek_vl.py
  xinference/model/llm/transformers/deepseek_vl2.py
  xinference/model/llm/transformers/gemma3.py
  xinference/model/llm/transformers/glm4v.py
  xinference/model/llm/transformers/glm_edge_v.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/transformers/internlm2.py
  xinference/model/llm/transformers/minicpmv25.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/omnilmm.py
  xinference/model/llm/transformers/opt.py
  xinference/model/llm/transformers/qwen-omni.py
  xinference/model/llm/transformers/qwen2_audio.py
  xinference/model/llm/transformers/qwen2_vl.py
  xinference/model/llm/transformers/qwen_vl.py
  xinference/model/llm/transformers/yi_vl.py
  xinference/model/llm/vllm/core.py
Labels: bug

#3325 ENH: Support GLM4-0414 MLX and GGUF
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/deepseek_vl.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: enhancement

#3259 FEAT: add ggufv2 support for vLLM
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3170 FEAT: ovis2
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/ovis2.py
Labels: feature

#3342 DOC: update troubleshooting.rst for the launch error caused by numpy
  doc/source/getting_started/troubleshooting.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/troubleshooting.po
Labels: documentation

#3347 FEAT: support Qwen3 and Qwen3MOE
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/vllm/core.py
Labels: feature

#3324 REF: Drop internal compression logic for `transformers` quantization, using bnb config instead
  xinference/deploy/cmdline.py
  xinference/model/llm/__init__.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_csghub.json
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/llm_family_openmind_hub.json
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/transformers/cogagent.py
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/cogvlm2_video.py
  xinference/model/llm/transformers/compression.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/deepseek_v2.py
  xinference/model/llm/transformers/deepseek_vl.py
  xinference/model/llm/transformers/deepseek_vl2.py
  xinference/model/llm/transformers/gemma3.py
  xinference/model/llm/transformers/glm4v.py
  xinference/model/llm/transformers/glm_edge_v.py
  xinference/model/llm/transformers/intern_vl.py
  xinference/model/llm/transformers/minicpmv25.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/qwen-omni.py
  xinference/model/llm/transformers/qwen2_audio.py
  xinference/model/llm/transformers/qwen2_vl.py
  xinference/model/llm/transformers/qwen_vl.py
  xinference/model/llm/transformers/yi_vl.py
  xinference/types.py
  xinference/web/ui/src/locales/en.json
  xinference/web/ui/src/locales/zh.json
  xinference/web/ui/src/scenes/launch_model/components/copyComponent.js
  xinference/web/ui/src/scenes/launch_model/components/drawer.js
  xinference/web/ui/src/scenes/launch_model/components/pasteDialog.js
  xinference/web/ui/src/scenes/launch_model/data/data.js
  xinference/web/ui/src/scenes/launch_model/modelCard.js
Labels: refactor

#3351 REF: Unify audio model abilities
  xinference/core/worker.py
  xinference/model/audio/core.py
  xinference/model/audio/model_spec.json
  xinference/model/audio/model_spec_modelscope.json
  xinference/model/video/diffusers.py
Labels: refactor

#3354 ENH: optimize qwen3, support chat_template_kwargs for all engines
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/llm/ovis2.rst
  doc/source/models/builtin/llm/qwen3.rst
  doc/source/user_guide/backends.rst
  xinference/core/utils.py
  xinference/deploy/docker/Dockerfile
  xinference/deploy/docker/requirements-ml.txt
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/llm_family_modelscope.json
  xinference/model/llm/mlx/core.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/tests/test_llm_family.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/cogagent.py
  xinference/model/llm/transformers/cogvlm2.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/minicpmv26.py
  xinference/model/llm/transformers/qwen_vl.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
  xinference/model/llm/vllm/distributed_executor.py
  xinference/model/llm/vllm/xavier/allocator.py
  xinference/model/llm/vllm/xavier/block_manager.py
  xinference/model/llm/vllm/xavier/block_tracker.py
  xinference/model/llm/vllm/xavier/executor.py
  xinference/model/llm/vllm/xavier/test/test_xavier.py
  xinference/types.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: enhancement

#3363 FEAT: Add support for Qwen3 GPTQ quantization format
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family_modelscope.json
Labels: feature

#3361 BUG: fix failure of clearing resources when loading model failed
  xinference/core/supervisor.py
Labels: bug
