Repository xorbitsai/inference, pull requests merged in 2025-09, with the labels that each got.

#4031 ENH: Update the environment dependencies for GOT-OCR2
  xinference/model/image/model_spec.json
Labels: enhancement

#4034 BUG: Fix Kokoro-82M can't run on GPU
  xinference/model/audio/kokoro.py
Labels: bug, gpu

#4039 BLD: bump funasr to 1.2.7
  .github/workflows/python.yaml
  setup.cfg
  xinference/deploy/docker/requirements_cpu/requirements_cpu-models.txt
Labels: build

#4042 FEAT: [model] Support Kokoro-82M-v1.1-zh
  xinference/model/audio/core.py
  xinference/model/audio/kokoro_zh.py
  xinference/model/audio/model_spec.json
Labels: feature

#4047 FEAT: IP restriction by env: XINFERENCE_ALLOWED_IPS
  xinference/api/restful_api.py
  xinference/constants.py
Labels: feature

#4052 BUG: [embeddings] fix parsing str type hf_overrides for vllm engine
  xinference/model/embedding/vllm/core.py
Labels: bug

#4062 BLD: update funasr
  xinference/deploy/docker/requirements/requirements-models.txt
  xinference/deploy/docker/requirements_12.8/requirements-cu128-models.txt
Labels: build

#3940 REF: [UI] refactor the launch model page.
  xinference/ui/web/ui/package-lock.json
  xinference/ui/web/ui/package.json
  xinference/ui/web/ui/src/components/copyComponent.js
  xinference/ui/web/ui/src/components/copyComponent/copyComponent.js
  xinference/ui/web/ui/src/components/copyComponent/style.css
  xinference/ui/web/ui/src/components/deleteDialog.js
  xinference/ui/web/ui/src/components/utils.js
  xinference/ui/web/ui/src/locales/en.json
  xinference/ui/web/ui/src/locales/ja.json
  xinference/ui/web/ui/src/locales/ko.json
  xinference/ui/web/ui/src/locales/zh.json
  xinference/ui/web/ui/src/scenes/launch_model/LaunchModel.js
  xinference/ui/web/ui/src/scenes/launch_model/components/addPair.js
  xinference/ui/web/ui/src/scenes/launch_model/components/addValue.js
  xinference/ui/web/ui/src/scenes/launch_model/components/cachedListDialog.js
  xinference/ui/web/ui/src/scenes/launch_model/components/commandBuilder.js
  xinference/ui/web/ui/src/scenes/launch_model/components/drawer.js
  xinference/ui/web/ui/src/scenes/launch_model/components/dynamicFieldList.js
  xinference/ui/web/ui/src/scenes/launch_model/components/editCustomModelDialog.js
  xinference/ui/web/ui/src/scenes/launch_model/components/launchModelDrawer.js
  xinference/ui/web/ui/src/scenes/launch_model/components/modelFormConfig.js
  xinference/ui/web/ui/src/scenes/launch_model/components/pasteDialog.js
  xinference/ui/web/ui/src/scenes/launch_model/data/data.js
  xinference/ui/web/ui/src/scenes/launch_model/modelCard.js
  xinference/ui/web/ui/src/scenes/launch_model/styles/modelCardStyle.css
  xinference/ui/web/ui/src/scenes/register_model/registerModel.js
Labels: refactor

#4070 FEAT: Openai API support sglang json structured output
  xinference/model/llm/sglang/core.py
  xinference/model/llm/vllm/core.py
Labels: feature

#4076 BUG: fix register_model when model name is duplicated
  xinference/core/supervisor.py
Labels: bug

#4081 FEAT: [UI] support request_limits parameter for all models.
  xinference/ui/web/ui/src/scenes/launch_model/components/modelFormConfig.js
Labels: feature

#3524 ENH: optimize MPS on Mac for Qwen2.5-VL
  xinference/model/llm/transformers/multimodal/qwen2_vl.py
Labels: enhancement

#4099 FEAT: [model] qwen-image-edit-2509
  xinference/api/restful_api.py
  xinference/client/restful/async_restful_client.py
  xinference/client/restful/restful_client.py
  xinference/model/embedding/sentence_transformers/tests/test_sentence_transformers.py
  xinference/model/image/model_spec.json
  xinference/model/image/stable_diffusion/core.py
  xinference/ui/gradio/media_interface.py
  xinference/ui/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#4100 BUG: Fix the issue where registered models cannot use tools
  xinference/model/llm/__init__.py
  xinference/model/llm/utils.py
  xinference/ui/web/ui/src/locales/en.json
  xinference/ui/web/ui/src/locales/ja.json
  xinference/ui/web/ui/src/locales/ko.json
  xinference/ui/web/ui/src/locales/zh.json
  xinference/ui/web/ui/src/scenes/register_model/components/addVirtualenv.js
  xinference/ui/web/ui/src/scenes/register_model/registerModel.js
Labels: bug

#4107 FEAT: [model] baichuan-M2
  xinference/model/llm/llm_family.json
  xinference/model/llm/vllm/core.py
Labels: feature
