Repository xorbitsai/inference, pull requests merged in 2025-07, with the labels that each got.

#3739 BUG: disable flash_attn for qwen3 embedding & rerank when no gpu available
  xinference/model/embedding/sentence_transformers/core.py
  xinference/model/rerank/core.py
Labels: bug, gpu

#3774 DOC: fix links
  README_zh_CN.md
  doc/source/getting_started/installation_npu.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation_npu.po
Labels: documentation

#3779 DOC: update info in docs
  doc/source/conf.py
  doc/source/getting_started/installation_npu.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation_npu.po
Labels: documentation

#3791 BUG: add message preprocessing to ensure that content is not null
  xinference/model/llm/vllm/core.py
Labels: bug

#3810 FEAT: support migrate from v1 to v2 for custom models
  xinference/model/audio/__init__.py
  xinference/model/custom.py
  xinference/model/embedding/__init__.py
  xinference/model/flexible/__init__.py
  xinference/model/flexible/core.py
  xinference/model/image/__init__.py
  xinference/model/llm/__init__.py
  xinference/model/rerank/__init__.py
Labels: feature

#3750 ENH: add modelscope for fish speech 1.5
  xinference/model/audio/model_spec.json
  xinference/model/llm/vllm/core.py
Labels: enhancement

#3812 FEAT: support ERNIE 4.5
  xinference/model/llm/llm_family.json
  xinference/model/llm/llm_family.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/vllm/core.py
  xinference/web/ui/src/scenes/launch_model/data/data.js
Labels: feature

#3768 BUG: resolve issue where AI output was lost when no tool was selected for function call #3767
  .github/workflows/python.yaml
  xinference/model/llm/tests/test_llm_model.py
  xinference/model/llm/utils.py
Labels: bug

#3756 FEAT: [model] support glm-4.1v-thinking
  xinference/core/chat_interface.py
  xinference/model/llm/llm_family.json
  xinference/model/llm/transformers/multimodal/glm4_1v.py
  xinference/model/llm/vllm/core.py
Labels: feature

#3815 DOC: update models
  README.md
  README_zh_CN.md
  doc/source/gen_docs.py
  doc/source/getting_started/installation.rst
  doc/source/models/builtin/embedding/index.rst
  doc/source/models/builtin/embedding/jina-embeddings-v4.rst
  doc/source/models/builtin/llm/code-llama-python.rst
  doc/source/models/builtin/llm/deepseek-prover-v2.rst
  doc/source/models/builtin/llm/deepseek-r1-0528-qwen3.rst
  doc/source/models/builtin/llm/deepseek-r1-0528.rst
  doc/source/models/builtin/llm/deepseek-r1-distill-llama.rst
  doc/source/models/builtin/llm/deepseek-r1-distill-qwen.rst
  doc/source/models/builtin/llm/deepseek-v3-0324.rst
  doc/source/models/builtin/llm/dianjin-r1.rst
  doc/source/models/builtin/llm/ernie4.5.rst
  doc/source/models/builtin/llm/gemma-3-1b-it.rst
  doc/source/models/builtin/llm/gemma-3-it.rst
  doc/source/models/builtin/llm/glm-4.1v-thinking.rst
  doc/source/models/builtin/llm/glm4-0414.rst
  doc/source/models/builtin/llm/huatuogpt-o1-llama-3.1.rst
  doc/source/models/builtin/llm/huatuogpt-o1-qwen2.5.rst
  doc/source/models/builtin/llm/index.rst
  doc/source/models/builtin/llm/llama-2-chat.rst
  doc/source/models/builtin/llm/llama-3-instruct.rst
  doc/source/models/builtin/llm/llama-3.1-instruct.rst
  doc/source/models/builtin/llm/minicpm-v-2.6.rst
  doc/source/models/builtin/llm/minicpm4.rst
  doc/source/models/builtin/llm/mistral-large-instruct.rst
  doc/source/models/builtin/llm/qwen2-vl-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-coder-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-instruct.rst
  doc/source/models/builtin/llm/qwen2.5-vl-instruct.rst
  doc/source/models/builtin/llm/qwen3.rst
  doc/source/models/builtin/llm/qwq-32b-preview.rst
  doc/source/models/builtin/llm/qwq-32b.rst
  doc/source/models/builtin/llm/skywork-or1.rst
  doc/source/models/builtin/llm/xiyansql-qwencoder-2504.rst
  doc/source/user_guide/backends.rst
Labels: documentation

#3794 BUG: fix error in `content` output at `reasoning_content`, when using `enable_thinking` in `chat_template_kwargs`
  xinference/model/llm/reasoning_parser.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/tests/test_llm_model.py
  xinference/model/llm/utils.py
  xinference/model/llm/vllm/core.py
Labels: bug

#3818 DOC: add experimental feature for virtualenv
  doc/source/locale/zh_CN/LC_MESSAGES/models/virtualenv.po
  doc/source/models/virtualenv.rst
  doc/source/user_guide/distributed_inference.rst
Labels: documentation

#3824 REF: move continuous batching scheduler into model
  xinference/core/model.py
  xinference/core/supervisor.py
  xinference/core/tests/test_continuous_batching.py
  xinference/model/image/scheduler/flux.py
  xinference/model/image/stable_diffusion/core.py
  xinference/model/llm/transformers/chatglm.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/gemma3.py
  xinference/model/llm/transformers/multimodal/glm4v.py
  xinference/model/llm/transformers/multimodal/minicpmv26.py
  xinference/model/llm/transformers/multimodal/qwen2_vl.py
  xinference/model/llm/transformers/opt.py
  xinference/model/llm/transformers/utils.py
  xinference/model/scheduler/__init__.py
  xinference/model/scheduler/batch.py
  xinference/model/scheduler/core.py
  xinference/model/scheduler/request.py
Labels: refactor

#3823 FEAT: kokoro mlx support
  doc/source/models/builtin/audio/index.rst
  doc/source/models/builtin/audio/kokoro-82m-mlx.rst
  doc/source/models/model_abilities/audio.rst
  setup.cfg
  xinference/model/audio/core.py
  xinference/model/audio/kokoro_mlx.py
  xinference/model/audio/model_spec.json
Labels: feature

#3838 BUG: fix compatibility for old vllm
  xinference/model/llm/vllm/core.py
Labels: bug

#3839 FIX: GLM4.1V Repository URL
  xinference/model/llm/llm_family.json
Labels: bug

#3846 BUG: Fix abnormal GPU memory usage in Qwen3 Reranker
  xinference/model/rerank/core.py
Labels: bug, gpu

#3859 FEAT: [UI] integrate user favorites into feature model output.
  xinference/ui/web/ui/src/locales/ja.json
  xinference/ui/web/ui/src/locales/ko.json
  xinference/ui/web/ui/src/locales/zh.json
  xinference/ui/web/ui/src/scenes/launch_model/LaunchModel.js
Labels: feature

#3865 BLD: remove sglang from pip install xinference[all] due to depedency conflicts with vllm
  doc/source/getting_started/installation.rst
  doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
  setup.cfg
Labels: build

#3864 ENH: Added mlx support for deepseek-v3-0324
  doc/source/models/builtin/llm/deepseek-v3-0324.rst
  xinference/model/llm/llm_family.json
Labels: enhancement

#3854 FEAT: support enable virtualenv and specify packages when lauching model
  .pre-commit-config.yaml
  setup.cfg
  xinference/api/restful_api.py
  xinference/client/restful/restful_client.py
  xinference/constants.py
  xinference/core/supervisor.py
  xinference/core/worker.py
  xinference/deploy/cmdline.py
  xinference/deploy/docker/requirements.txt
  xinference/deploy/docker/requirements_cpu.txt
Labels: feature

#3875 BUG: fix compatibility with vllm 0.10.0
  xinference/model/llm/vllm/core.py
Labels: bug

#3872 FEAT: setting max_tokens to maximum if not specified
  xinference/constants.py
  xinference/fields.py
  xinference/model/llm/llama_cpp/core.py
  xinference/model/llm/mlx/core.py
  xinference/model/llm/mlx/distributed_models/qwen3_moe.py
  xinference/model/llm/sglang/core.py
  xinference/model/llm/transformers/core.py
  xinference/model/llm/transformers/multimodal/cogagent.py
  xinference/model/llm/transformers/multimodal/deepseek_vl2.py
  xinference/model/llm/transformers/multimodal/gemma3.py
  xinference/model/llm/transformers/multimodal/glm4_1v.py
  xinference/model/llm/transformers/multimodal/glm4v.py
  xinference/model/llm/transformers/multimodal/intern_vl.py
  xinference/model/llm/transformers/multimodal/ovis2.py
  xinference/model/llm/transformers/multimodal/qwen-omni.py
  xinference/model/llm/transformers/multimodal/qwen2_audio.py
  xinference/model/llm/transformers/multimodal/qwen2_vl.py
  xinference/model/llm/transformers/tests/test_opt.py
  xinference/model/llm/transformers/utils.py
  xinference/model/llm/vllm/core.py
  xinference/model/scheduler/request.py
  xinference/types.py
  xinference/ui/gradio/chat_interface.py
Labels: feature
